### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by Avi1689** [MicrosoftDocs/windows-itpro-docs#7967] opened 2020-07-28 04:56 UTC
Hello Team,

With respect to Update compliance, the queried clients have DeploymentStatus as "Progress stalled" and DetailedStatus as "DetailedStatus" or "PreDownloadTasksPassed". I couldn't find what these values really indicate in the article. It would be great if the KB is updated with explanation of these values.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 630fda2d-f753-fd62-ff48-044c100afe71
* Version Independent ID: fd499bb8-ca66-672e-4326-4e1a0a0ebd23
* Content: [Update Compliance Schema - WaaSDeploymentStatus - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-schema-waasdeploymentstatus)
* Content Source: [windows/deployment/update/update-compliance-schema-waasdeploymentstatus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-schema-waasdeploymentstatus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment] 2020-07-28 15:23
@cinglis-msft can you advise?

**Comment by cinglis-msft** [comment] 2020-07-28 15:30
A definition of Pre-download Tasks Passed is available on the very page that is being referenced. It is a myriad of small tasks prior to beginning the download. Ensure the client is active (on & connected to internet) to get the client to progress.

**Comment by e0i** [comment] 2020-09-18 16:44
Hello @Avi1689 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered. Thanks.

**Comment by jaimeo** [comment] 2022-08-29 15:37
Assigning to @dougeby to find the right current writer (cinglis left MS some time ago and I'm in a different role).

**Comment by aczechowski** [comment] 2022-08-30 03:14
Oops...apologies for those that get notification from me reopening this issue...it'll close again momentarily via a community contribution.

**Closed** 2022-08-30 03:14 UTC
Labels: update, doc-enhancement
