### ISSUE TITLE
Warning at top of page no longer applies

### ISSUE THREAD

**Issue by pahuijbr** [MicrosoftDocs/windows-itpro-docs#6817] opened 2020-05-26 21:17 UTC
Hi, at the top of this page we have the following warning:

Warning

Micrsosoft Defender ATP currently does not support Windows Virtual Desktop multi-user session.

In fact we now do support it in preview: https://techcommunity.microsoft.com/t5/windows-virtual-desktop/microsoft-defender-atp-now-in-preview-on-windows-10-enterprise/m-p/1372007 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804f2883-5de4-9d54-d0b4-e64b04984aa8
* Version Independent ID: 0ab9ee92-c5e1-0455-92ba-ed07ed7bd140
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) machines - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment] 2020-07-05 04:07
Hello @pahuijbr ,
the issue is already fixed in https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c0e41df2f57f888d13c1ed9b80dcd92f0711c59c#diff-3684d7e81c25a8f6d2e8d45baca8d406

Dear @e0i , I believe the issue could be closed
Thank you

**Comment by illfated** [comment] 2020-07-05 04:18
( commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c0e41df2f57f888d13c1ed9b80dcd92f0711c59c )

**Closed** 2020-07-05 19:50 UTC
Labels: in progress, microsoft defender atp
