### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fullenw1** [MicrosoftDocs/windows-itpro-docs#4151] opened 2019-06-20 18:11 UTC
The link to  "Windows Update stuck at 0 percent on Windows 10 or Windows Server 2016" leads to a 404 error page.

https://support.microsoft.com/help/4039473/windows-update-stuck-at-0-percent-on-windows-10-and-windows-server-201

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349d337e-ca0f-a40a-a522-bd1ae71c7d1e
* Version Independent ID: 50f0c3b0-eaad-89c0-eb3c-878e7564d6f6
* Content: [Windows Update troubleshooting](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting#feedback)
* Content Source: [windows/deployment/update/windows-update-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by jvsam** [comment] 2019-06-20 23:03
@officedocsbot assign @jvsam

**Comment by illfated** [comment] 2019-06-21 17:16
Confirmed. https://support.microsoft.com/en-us/help/4039473 does not exist or has been removed (returns the Microsoft Support 404 page).

I have tried searching for a matching page containing all the words in the title, but it looks like there is no known page for that content. Only MSDN/community/answers.microsoft.com and similar pages with a partial match can be found.

**Comment by jvsam** [comment] 2019-06-23 13:02
Thanks @fullenw1 for bringing this to our attention. Same as @illfated, I've searched and did not find any related, similar articles or even cached Microsoft docs so I cannot confirm what the original support article contained. This is one of the [articles](https://answers.microsoft.com/windows/forum/windows_other-update/windows-updates-stuck-at-0-windows-server-2016/2ba2ceff-8258-4dff-b28e-9ecdb6d8ee09) I've found that partially matched the link's *anchor texts*. Similar information from the answers.microsoft.com post can be found in this documentation, please see *Issues related to HTTP/Proxy* section. Anyway, I agree that the broken link needs to be fixed so thank you again for your feedback.

Hi @greg-lindsay, is there a Microsoft doc resource where the broken link should go that is not accessible to the public? We need your input so we will know how to proceed. If there is none, we can suggest updates to this documentation to remove the broken link. Hoping to hear from you. Thank you.

**Comment by illfated** [comment] 2019-06-23 16:37
A very probable alternative solution will be to remove the link entirely, while also making sure to remove text indicating that the link was there in the first place.

**Comment by jvsam** [comment] 2019-06-29 08:02
Agreed, that's a good, interim solution @illfated. If there is an updated link that is not yet public, perhaps the author will update the documentation then.

@fullenw1 I will get this over to the Windows writing team for review (*suggestion is to remove the link including the anchor texts*). Thanks for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation! ﻿

**Comment by jvsam** [comment] 2019-07-07 01:36
Hi again @fullenw1, there's already a suggested update to this documentation via this [Pull Request (PR)](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4333). PRs are normally reviewed/merged in the order of submission and approval depends on the volume. But once the contributions are approved and merged, they will be displayed at docs.microsoft.com in the next scheduled publishing run. You can verify the changes at this URL: https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting. We will also update this issue to inform you when the changes are live.

Thanks for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-07-24 19:12
Hi again @fullenw1, we appreciate your patience. I'd like to inform you the the pull request (See #4333) has been approved and merged. The broken link has been removed from the content page and you can verify by visiting this URL: https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting. Thank you for your feedback to help improve the contents of this documentation and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-07-24 19:12
@officedocsbot close

**Closed by jvsam** 2019-07-24 19:12 UTC
