### ISSUE TITLE
So.

### ISSUE THREAD

**Issue by MoonGem** [MicrosoftDocs/windows-itpro-docs#1685] opened 2018-09-26 10:36 UTC
So what you're saying is basically copypasta something, then uninstall windows to get rid of candy crush saga.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b48c394-863e-9a54-6d5b-5f31ff07849f
* Version Independent ID: f5ddf9f4-c449-360c-107e-582f7d9df7fd
* Content: [Windows 10 connection endpoints](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-endpoints)
* Content Source: [windows/privacy/manage-windows-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-windows-endpoints.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment] 2018-09-26 18:19
Duplicate of https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1686.
@shortpatti please close as dup. Thanks!

**Closed** 2018-09-26 18:57 UTC
Labels: assigned-to-author, privacy
