### ISSUE TITLE
SAC, not CBB

### ISSUE THREAD

**Issue by rstenborg** [MicrosoftDocs/windows-itpro-docs#2468] opened 2019-01-11 21:20 UTC
CBB is the old terminology, should be SAC. "The default target version in Upgrade Readiness is set to the released version of the Current Branch for Business (CBB)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cba076c-90ab-62bf-dcac-0c4c528d250d
* Version Independent ID: eab2ef6b-1854-0859-199c-04fc9cc864c5
* Content: [Use Upgrade Readiness to manage Windows upgrades (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/use-upgrade-readiness-to-manage-windows-upgrades)
* Content Source: [windows/deployment/upgrade/use-upgrade-readiness-to-manage-windows-upgrades.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/use-upgrade-readiness-to-manage-windows-upgrades.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment] 2019-04-15 21:23
@officedocsbot assign @e0i

**Comment by jaimeo** [comment] 2019-04-15 21:31
Yes, thanks. We have a big list of all stray instances of "CBB" still hanging around and will be doing a cleanup as part of an upcoming update.

**Comment by e0i** [comment] 2019-08-15 11:58
@jaimeo Any updates with aforementioned cleanup? We would like to follow up and provide a PR at least for this document if necessary. Thanks.

**Comment by jaimeo** [comment] 2019-08-15 15:37
Revised topics are live.

**Comment by jaimeo** [comment] 2019-08-15 15:39
Oops, my mistake. This is a stray instance. Fixing now.

**Comment by jaimeo** [comment] 2019-08-15 16:56
Sorry about that! This instance escaped our string searches. Now fixed in https://github.com/MicrosoftDocs/windows-docs-pr/pull/909.

**Comment by illfated** [comment] 2019-08-17 02:18
@rstenborg : This issue seems to be resolved. Can you confirm that you see the corrected version too?

**Comment by e0i** [comment] 2019-08-21 08:39
@rstenborg 

The issue is being closed since it seems to be resolved. Feel free to re-open it if you feel it hasn't been resolved.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment] 2019-08-21 08:39
@officedocsbot close

**Closed by e0i** 2019-08-21 08:39 UTC
Labels: deployment
