### ISSUE TITLE
We had to add Administrator to the policy? Bug or feature ?

### ISSUE THREAD

**Issue by i5513** [MicrosoftDocs/windows-itpro-docs#5152] opened 2019-10-10 14:13 UTC
We needed to add "Administrator" user to this policy in order Administrator can shutdown system remotely via shutdown.exe /r /m \\xxx command. But this policy has "Administrators" group as allowed. Administrator is in Administrators group.

Do you know what is happening here ?

If Administrator is not in the list of the policy "Access Denied (5)" is show and not action is taken.

Thank you very much

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1f6bded-a1b2-1ef0-90a8-f313afa73557
* Version Independent ID: 4a55f951-788c-cac1-5bd6-496ef533cfd6
* Content: [Force shutdown from a remote system (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/force-shutdown-from-a-remote-system#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/force-shutdown-from-a-remote-system.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/force-shutdown-from-a-remote-system.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment] 2019-10-25 06:41
Hello @i5513 ,
from my experience, there is no need to add Administrator account to the policy separately.
are you sure you are running command by account that has admin permission for the remote machine?
Thank you

**Comment by i5513** [comment] 2019-10-25 07:33
I'm sure, When I add the user "administrador" to the policy it works.
Administrador user si in administrators group (Administradores) .

(Windows Spanish localization)

Thanks

**Comment by MaratMussabekov** [comment] 2019-10-28 06:02
Hello @i5513 ,
I have made several checks and was unable to reproduce your issue (it worked fine without adding Administrator to the policy separately). 
I would recommend you to check other applied GPOs (may be there are some conflicts?) and create a request in [Microsoft Support](https://support.microsoft.com)
Thank you

**Comment by i5513** [comment] 2019-10-28 09:53
Thanks Marat, I will escalate the issue, so maybe somebody at my organization open the request, or review the applied GPOs.

**Comment by e0i** [comment] 2019-11-01 18:55
@i5513 

The issue is being marked as resolved as the problematic behavior couldn't be reproduced.

Feel free to re-open this issue if there is still something you'd like to suggest to improve the document.

Thank you for taking the time to provide feedback and follow-up.

**Closed by e0i** 2019-11-01 18:55 UTC
