### ISSUE TITLE
enroll and auto enroll for WHFB User Group

### ISSUE THREAD

**Issue by rrsit** [MicrosoftDocs/windows-itpro-docs#5258] opened 2019-10-24 00:51 UTC
in the review section  "The Windows Hello for Business Users group, or equivalent has the allow enroll and allow auto enroll permissions"
but in the  section "Configure the Windows Hello for Business Authentication Certificate template", step 12, only enroll is mentioned.
which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment] 2019-10-27 20:23
Hello, @rrsit 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by illfated** [comment] 2019-11-20 21:22
@rrsit : The PR content (text removal) has been merged into the [`public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch. I presume this will solve your issue. Please comment and confirm whether this solves the case or not.

**Closed** 2019-11-20 22:31 UTC
