### ISSUE TITLE
Which subscription is referred to?

### ISSUE THREAD

**Issue by dancs85** [MicrosoftDocs/windows-itpro-docs#5167] opened 2019-10-12 04:59 UTC
It's not clear which subscription should have Microsoft.Insights resource provider enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7c9a2b-c6a2-0c0b-3718-a9c0d2cbbf05
* Version Independent ID: 86974870-2d23-e7e0-e7fb-9a58e4957b00
* Content: [Stream Microsoft Defender Advanced Threat Protection events.](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment] 2019-10-12 11:28
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment] 2019-10-21 09:19
@dancs85. I think its Azure subscription

**Comment by jvsam** [comment] 2019-11-02 07:14
Hi @dancs85 if you don't have a subscription, you can choose *Free Trial* and you'll have full access to all the services or choose *Pay-As-You-Go* and pay only for the resources you use. Once your subscription is confirmed, you can add the *Microsoft.insights* under *Resource Providers*.

![image](https://user-images.githubusercontent.com/18371314/68066795-9dfcbd00-fd78-11e9-8c06-ba0985a5917f.png)

Is this the information you are looking for? If not, kindly clarify. Thank you.

**Comment by jvsam** [comment] 2019-11-10 23:15
Hello again @dancs85, we hope the information we've provided helped. It would seem that as long as you have an active and paying subscription, you can get microsoft.insights. 

We will now close this issue, but if you have feedback or suggestions to help improve the quality of the technical documentation of Microsoft Docs, please use the doc's *feedback feature*.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-11-10 23:15
@officedocsbot close

**Closed by jvsam** 2019-11-10 23:15 UTC

**Comment by dancs85** [comment] 2019-11-11 04:56
@jvsam Just to clarify, we have 26 subscriptions. The subscription you want is only 1 of them, and is the one that was selected when MS Defender ATP was set up (you also create a Log Analytics workspace in it)

**Comment by illfated** [comment] 2019-11-11 09:00
Fair point, looks like something that could have been noted in the document to avoid confusion (unless it is specified somewhere else in a different document).
