### ISSUE TITLE
List outdated, does not include Foxit

### ISSUE THREAD

**Issue by avbski12** [MicrosoftDocs/windows-itpro-docs#6043] opened 2020-02-12 19:57 UTC
Foxit PDF reader is showing as an enlighten app under the Enterprise Context column in task manager after adding it as an allowed app in my WIP policy.

Are there any other apps that are enlighten missing from this list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment] 2020-02-13 15:51
Hello, @avbski12 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by VLG17** [comment] 2020-03-24 08:17
@avbski12 The article you mentioned contains the list of Microsoft enlightened / unenlightened apps, not third party apps.

You can find the information needed [in this article](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers).

![image](https://user-images.githubusercontent.com/41186174/77403223-99cd4c80-6db8-11ea-819b-267132ab9761.png)

**Comment by e0i** [comment] 2020-03-31 09:07
@avbski12 

Closing via the above comment that we hope answers your question. Thank you for reaching out.

**Closed by e0i** 2020-03-31 09:07 UTC
Labels: information protection
