### ISSUE TITLE
Commercial ID Key?

### ISSUE THREAD

**Issue by lXbalanque** [MicrosoftDocs/windows-itpro-docs#2981] opened 2019-03-20 01:02 UTC
The article has some old screenshots and mentions a Commercial ID key but it doesn't exist anywhere. It seems like it needs to be updated to the new terminology that's being used in the Azure portal. This is a recurring problem across all of MS documentation.

**Comment by illfated** [comment] 2019-03-20 01:09
Looks like your post did not get linked to any particular docs.microsoft.com page.
Could you link the page(s) your are making a reference to?

**Comment by lXbalanque** [comment] 2019-03-20 01:12
Oh, oops! That would be helpful. Here's the link: https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started#feedback

I'm attempting to pull log information about Windows 10 updates in my environments using Windows Intune and Log Analytics. I **think** this is what I should be doing but if there's another path I should be going down, I'm all ears. I just need to report on patch compliance and make sure all of my machine are adhering to the update rings I've assigned. Hopefully it contains the ability to drill down into specific machines and see what's installed.

**Comment by illfated** [comment] 2019-03-20 01:33
Thanks. To sum up, the article is:

Docs / Windows / Deployment : Get started with Update Compliance
- https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started

Github page to improve / update:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-get-started.md

**Comment by e0i** [comment] 2019-05-09 14:05
Hello, @IXbalanque

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment] 2019-05-27 19:04
@lXbalanque A PR is under delivery for this issue. Thank you.

**Comment by illfated** [comment] 2019-05-27 19:05
@e0i : Could you link the PR you refer to, so we may link the PR back here too?

**Comment by VLG17** [comment] 2019-07-23 14:10
@lXbalanque I have tested and the Commercial ID Key is there...i guess you don't see it under the Log Analytics Workspace because you haven't created an Upgrade Readiness resource before doing that.

In order to reach your goal of pulling log information about Windows 10 updates in your environments your need to take advantage of [Upgrade Readiness](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started) (or even the newer [Device Health](https://docs.microsoft.com/en-us/windows/deployment/update/device-health-monitor)), which leverages Log Analytics Workspace.

After you configure Upgrade Readiness in Azure, you'll see that the Commercial Id Key will be generated in the Analytics Workspace under "Upgrade Readiness Settings":

![image](https://user-images.githubusercontent.com/41186174/61718929-933f8e80-ad6c-11e9-9100-ab1971bae1fd.png)

**Comment by e0i** [comment] 2019-07-30 14:57
Hello @lXbalanque,

We are closing this issue since your question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment] 2019-07-30 14:57
@officedocsbot close

**Closed by e0i** 2019-07-30 14:57 UTC
