### ISSUE TITLE
Delete doesn't work

### ISSUE THREAD

**Issue by LadtoHelp** [MicrosoftDocs/windows-itpro-docs#10728] opened 2022-07-27 02:22 UTC
> VPNv2/ProfileName
> Unique alpha numeric identifier for the profile. The profile name must not include a forward slash (/).
> 
> Supported operations include Get, Add, and Delete.

I can confirm 100% that the delete function does not work when you un-assign the profile from a device. Is that by design ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/vpnv2-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment] 2023-01-13 19:32
Closing this as this seems a duplicate of https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10754. We'll track this issue there, as it has more details.

**Closed by vinaypamnani-msft** 2023-01-13 19:32 UTC
Labels: client management, mdm, VPN, product-question
