### ISSUE TITLE
Correction for Win10 Pro and M365B

### ISSUE THREAD

**Issue by davebirr** [MicrosoftDocs/windows-itpro-docs#4994] opened 2019-09-22 18:57 UTC
Article incorrectly states Windows Enterprise is required for baseline protection.  This is also included in Windows 10 Pro and Windows 10 Business when used with Microsoft 365 Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0238a73f-da06-ae17-c61d-85ae54e0f7cb
* Version Independent ID: e5bb4a25-a7c3-3a16-bd95-d6f2513402e0
* Content: [Windows Defender Credential Guard Requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment] 2019-09-23 05:28
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-09-29 18:15
Thank you again for pointing this out @davebirr, much appreciated. Similar to ASR rules (see #4993), *Windows Defender Credential Guard* is available on my Microsoft 365 Business subscription/Windows 10 Pro.

![image](https://user-images.githubusercontent.com/18371314/65837218-5b823380-e327-11e9-899d-f8e6421e18ba.png)

Hello @DulceMontemayor, if you are not busy, can you please confirm Credential Guards's availability on Windows 10 Pro with Microsoft 365 Business subscription? Thank you in advance.

**Comment by jvsam** [comment] 2019-10-06 20:20
Hello again @DulceMontemayor, I'd like to follow-up on this issue. Can you please confirm if *Windows Defender Credential Guard* is *officially* available on Microsoft 365 Business subscription + Windows 10 Pro? Thank you so much.

**Comment by jvsam** [comment] 2019-10-19 02:23
Hello again @DulceMontemayor, do you have any update on this? Can you please confirm if the information on this doc is accurate?  Thank you,

**Comment by illfated** [comment] 2019-10-20 17:54
Maybe you could get this confirmed by the document manager (Daniel Simpson), in case he is more available than the original author?

**Comment by jvsam** [comment] 2019-10-27 22:31
Will follow-up via email and escalate @illfated, thanks.

@officedocsbot assign @DulceMontemayor

**Comment by jvsam** [comment] 2019-11-08 19:37
Hi @DulceMontemayor just a friendly follow-up. We'd appreciate if you could provide feedback on this issue so we can move forward. Thank you.

**Comment by jvsam** [comment] 2019-11-18 02:05
Hi again @DulceMontemayor, hoping you'll have time to review this and provide some insights. Thank you.

CC: @Dansimp, will you be able to assist? Thank you,

**Comment by jvsam** [comment] 2019-12-01 16:19
Hi @davebirr, we appreciate your patience on this matter. Since there is no update yet from the author related to your question, what I would recommend is to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) instead if you have time. They'll be able to provide you a more definitive answer. Personally, I'd assume the answer may be similar to the answer to you other question (see #4993), it's not Windows Pro per se' but the subscription to Microsoft 365 (E5 specifically) that provides you access to the feature. I am sorry that we cannot provide you more information. If you do contact support, kindly keep us informed on the resolution or any relevant information that can be incorporated into this documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. 

Thank you so much!

**Comment by jvsam** [comment] 2019-12-08 18:04
Hi again @davebirr, hoping you were able to contact support since it's your best option to get immediate and definitive answer. There have been no further action or changes on the docs from the author, hence, it may be safe to assume that the content is still accurate (*Please see my comment regarding E5 subscription*). For now, we will close this issue. Again, please keep us informed (*and you can reopen this issue*) of any relevant information from other *MS* resources that can be incorporated into this documentation, e.g. confirmation about the baseline requirements, etc. Thank you.

**Comment by jvsam** [comment] 2019-12-08 18:05
@officedocsbot close

**Closed by jvsam** 2019-12-08 18:05 UTC
