### ISSUE TITLE
Removal / De-Provisioning of APPs not functional

### ISSUE THREAD

**Issue by gruppenrichtlinien** [MicrosoftDocs/windows-itpro-docs#873] opened 2018-05-08 06:07 UTC
1.) 1507-1709:
Get-AppxProvisionedPackage -Online | Where-Object {$_.PackageName -Like "Microsoft.BingNews"} | ForEach-Object { Remove-AppxProvisionedPackage -Online -PackageName $_.PackageName}

This command is wrong, should be corrected to: [...] | Where-Object {$_.Displayname [...] or shorten it completly to: Get-AppxProvisionedPackage -Online | where {$_.DisplayName -eq "Name.of.The.App"} |
Remove-AppxProvisionedPackage -online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8228962-7158-6be1-e791-e6535b88f343
* Version Independent ID: 46e4c7f3-e8b0-ebc9-da58-b69149803937
* Content: [Manage connections from Windows operating system components to Microsoft services (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services)
* Content Source: [windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic-msft**

**Comment by shortpatti** [comment] 2018-06-06 17:52
Duplicate of issue [874](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/874)

**Closed by shortpatti** 2018-06-06 17:52 UTC
Labels: configuration
