### ISSUE TITLE
link 404'ing

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/windows-itpro-docs#6940] opened 2020-06-12 04:30 UTC
The link "How to manage Surface driver updates in Configuration Manager"
https://docs.microsoft.com/surface/manage-surface-driver-updates-configuration-manager.md
gives a 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Manage and deploy Surface driver and firmware updates - Surface](https://docs.microsoft.com/en-us/surface/manage-surface-driver-and-firmware-updates)
* Content Source: [devices/surface/manage-surface-driver-and-firmware-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/manage-surface-driver-and-firmware-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **greglin**

**Comment by illfated** [comment] 2020-06-12 15:03
The error is caused by an unwanted `.md` at the end of the link. I will make sure to clarify that in the PR.
Correct link: https://docs.microsoft.com/surface/manage-surface-driver-updates-configuration-manager

**Comment by RAJU2529** [comment] 2020-06-12 16:13
committed changes

**Comment by VLG17** [comment] 2020-09-25 16:08
@Conan1989 Thank you for providing this feedback. The broken link was fixed with the help of @RAJU2529

**Comment by illfated** [comment] 2020-09-25 21:04
#please-close

**Closed** 2020-10-07 13:31 UTC
Labels: devices
