### ISSUE TITLE
Change In Behavior If NTLMv1 Is Disabled?

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/windows-itpro-docs#4955] opened 2019-09-18 00:13 UTC
Hello!  We recently disabled NTLMv1 in one of our environments and then attempted a connection from a client using NTLMv1.  When we did this, we were obviously denied, but the information from Event ID 4625 wasn't consistent with the information on this page.  

Per https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4625, **Package Name (NTLM only)** should be populated if **Authentication Package** = **NTLM**.  However, what I observed was that **Package Name (NTLM only)** was blank when an NTLMv1 connection was attempted (and failed), even though **Authentication Package** did equal **NTLM** for that event.  

Based on my observation, this page needs to be updated to clarify that if NTLMv1 is disabled (by setting LmCompatibilityLevel=5), then **Package Name (NTLM only)** will _not_ be populated even if **Authentication Package** = **NTLM**.

Below is the sanitized event entry:
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          DateTime
Event ID:      4625
Task Category: Logon
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      dcname.fqdn
Description:
An account failed to log on.

Subject:
	Security ID:		NULL SID
	Account Name:		-
	Account Domain:		-
	Logon ID:		0x0

Logon Type:			3

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		user@upn
	Account Domain:		

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xC000006D
	Sub Status:		0xC000006A

Process Information:
	Caller Process ID:	0x0
	Caller Process Name:	-

Network Information:
	Workstation Name:	TEST-COMPUTER
	Source Network Address:	192.168.1.50
	Source Port:		50871

Detailed Authentication Information:
	Logon Process:		NtLmSsp 
	Authentication Package:	NTLM
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

If I have missed something, please let me know.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80307c25-b809-e9b8-bab2-d37d3de7e920
* Version Independent ID: 24c32be1-2fc3-f22f-7e6c-da4049bf8458
* Content: [4625(F) An account failed to log on. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4625)
* Content Source: [windows/security/threat-protection/auditing/event-4625.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4625.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment] 2019-11-01 23:24
Hello, @aakash-shah  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by aakash-shah** [comment] 2019-11-07 04:50
Hello!  My comment wasn't intended to be a support ticket - the documentation listed on this page doesn't appear to be accurate based on my test and so I wanted to report it so this can be fixed to avoid confusion for other people.

**Comment by illfated** [comment] 2019-11-10 01:01
Fair enough. May be worth looking into, if we can acquire some feedback from other testers to verify the correctness of the feedback on this page.

@e0i : Do you concur that the feedback above (and possible corrections to the document) could be worth verifying?

**Comment by e0i** [comment] 2019-11-16 21:44
@aakash-shah Thank you for the clarification. 

The issue is under investigation and you will be notified with any changes on the way.

**Comment by joinimran** [comment] 2020-02-13 08:06
@aakash-shah - Thank you for your feedback. Few queries from my side. Can you please confirm what is the host and client environment. What was the status when the connection was successful?

**Comment by e0i** [comment] 2020-03-17 15:38
@aakash-shah 

We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Closed by e0i** 2020-03-17 15:38 UTC
Labels: auditing
