### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by tju-pwsh** [MicrosoftDocs/windows-itpro-docs#5655] opened 2019-12-11 12:34 UTC
"Enteprise" should be "Enterprise"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment] 2019-12-11 14:56
@illfated. @jvsam  This user  @tju-pwsh  created earlier PR #5654.  so close this duplicate issue

**Comment by illfated** [comment] 2019-12-11 22:34
@RAJU2529 : The pages are different, so not a duplicate even if the title and the issue ticket comment is the same.
- [`windows/client-management/mdm/device-update-management.md`](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/device-update-management.md) (#5654 )
- [`windows/client-management/mdm/policy-csp-update.md`](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md) (#5655 = this page)

**Comment by RAJU2529** [comment] 2019-12-12 03:15
@illfated . Thanks for your Intelligent analysis In this article. After reading your reply. I also confirmed current issue is different..

I learnt new thing from you sir. I keep  this intelligent analysis and I use  this while Teaching mathematics subject.

just I created new PR. 
verify and approve. 

one thing I need to say  finding the wrong word and  replacing is too difficult.

**Comment by illfated** [comment] 2019-12-12 11:30
> @illfated . Thanks for your Intelligent analysis In this article. After reading your reply. I also confirmed current issue is different..
> 
Thank you for seeing the difference. Some details are sometimes more important than the title and message.

> I learnt new thing from you sir. I keep this intelligent analysis and I use this while Teaching mathematics subject.
> 
Very good, thank you for your kind reply. All the best for your teaching job, sir, that is an important skill to teach & learn.

> just I created new PR.
> verify and approve.
> 
Very well, I have approved & commented in your PR. All we need to do is to wait for the document manager to merge the correction.

> one thing I need to say finding the wrong word and replacing is too difficult.

Too difficult? Maybe, but I don't see exactly how that should affect us following up on it when it gets reported. There is only 1 occurrence of the misspelling of the word. I can only assume that it is difficult enough to find the typos except for when reading through the text where the typo occurs. I know, the human brain is often very good at correcting typos in our minds while reading, so even if 2 characters are swapped (wrong order), the brain tends to autocorrect the misspelling. Missing characters may take a more detail-focused brain like mine to notice, because my slight autism is very focused on details. Even so, the material we are dealing with here is too vast and technical to read it all to find all the typos, that is why it is so good to have this community where typos can be reported.

**Comment by e0i** [comment] 2019-12-22 21:27
@tju-pwsh The issue has been addressed via PR #5669. Thank you for providing feedback.

**Closed by e0i** 2019-12-22 21:27 UTC
