### ISSUE TITLE
The AppLocker CSP page is really unconventional

### ISSUE THREAD

**Issue by tr5tn** [MicrosoftDocs/windows-itpro-docs#4919] opened 2019-09-11 15:07 UTC
This page has tons of great additional content beyond what I would normally expect to find on a CSP page, but it's really difficult to work with this page accordingly. The structure is completely atypical relative to other CSP pages. Most pages seem to follow the format you might find on a page like [SmartScreen CSP](https://docs.microsoft.com/en-gb/windows/client-management/mdm/policy-csp-smartscreen), which uses comments really effectively to partition the content within each section with these elements: 

```
<!--Policies-->
<!--Policy-->
<!--SupportedSKUs-->
<!--Scope-->
<!--Description-->
<!--ADMXMapped-->
<!--SupportedValues-->
```
All of this also seems to vaguely match up with the DDF files, whereas this AppLocker page seems to be completely distinct from the DDF file. This page is one of a handful of CSP pages that stand out for their inconsistency. Can I suggest that the additional content is moved to its own page and this page contracts to conform with the most common format of these pages?

**Comment by illfated** [comment] 2019-09-11 21:04
Which page do you mean by "**This page is really unconventional**" ?
(I presume it is not the SmartScreen CSP page you use as an example.)

**Comment by tr5tn** [comment] 2019-09-13 10:42
> Very well. So this is about the following page in the Docs pages and its Github source:
> 
> https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp
> https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/applocker-csp.md

Yes. If you look at the majority of the CSP pages, there is some conformity to their structure, whereas this page really breaks that mould. There are other pages with variances but this page is quite different. I have a separate issue open for the BitLocker CSP page, which could benefit from simply adding the tags that are commonly used, but this page has a structure that deviates quite far beyond the norm.

**Comment by illfated** [comment] 2019-09-13 11:54
Fair enough. I don't have any strong opinions on this matter, so I hope this can be followed up by any of the MS Docs team members, authors or managers who know this topic well enough to reply, give feedback and follow up your questions. @ManikaDhiman : Do you have any recommendations regarding who might be well suited for this task, besides @lomayor ?

**Comment by lomayor** [comment] 2019-09-13 17:07
@Dansimp kindly help point to the right SME.

**Comment by tr5tn** [comment] 2019-09-16 10:09
Thanks both.

**Comment by tr5tn** [comment] 2019-09-16 10:10
This is [the BitLocker commentary](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4918), for reference, as the topics are quite similar.

**Comment by illfated** [comment] 2019-09-16 17:03
Just a note for future PR creation: the [`master`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master) branch has been substituted with the [`public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch for pull requests from regular users.

**Comment by illfated** [comment] 2019-10-05 17:04
Updated my Github document link above to point to the [`public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch instead of the [`master`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master) branch.

**Comment by illfated** [comment] 2019-10-05 17:07
I am not sure if I can contribute with anything for this page yet, so it would be really helpful with a comment from the document author or one of the MS Docs team members experienced in this.

**Comment by lomayor** [comment] 2019-10-16 15:48
@Dansimp please help point to the right writer.

**Comment by e0i** [comment] 2019-10-17 00:04
@tr5tn @illfated 

The issue is under investigation. Thank you.

**Comment by ManikaDhiman** [comment] 2019-11-19 20:01
Hi @e0i, I've updated the AppLocker CSP doc structure to align with other CSPs. The updates are now available in live docs.

Please note that the following tags mentioned by @tr5tn are currently implemented only in Policy CSP areaname docs:
```
<!--Policies-->
<!--Policy-->
<!--SupportedSKUs-->
<!--Scope-->
<!--Description-->
<!--ADMXMapped-->
<!--SupportedValues-->
```
Hope this helps. Thanks!

**Comment by tr5tn** [comment] 2019-11-20 10:22
Hi @ManikaDhiman . Thanks. I think this page is still really unusual though. Basically most of the content from **Find publisher and product name of apps** downwards breaks the mould. This content is all "how to", references, recommendations and examples, rather than the pure settings and options content that I would expect to find on a CSP page. To try to be extra clear, I think there are a number of examples where CSP content is present on some other page, and the CSP content links off to the supporting content. I have spent a few months reviewing all of the CSP content, and I am confident this page is exceptional in trying to contain all of the content for the topic.

**Comment by ManikaDhiman** [comment] 2019-12-03 20:45
Hi @tr5tn, thanks for the feedback. We are in line with your suggestions and tracking this doc improvement internally. However, it may take a while before the updates are available in live docs. Thanks!

**Comment by e0i** [comment] 2020-02-11 22:40
Closing via document author's remarks. Thanks.

> Hi @tr5tn, thanks for the feedback. We are in line with your suggestions and tracking this doc improvement internally. However, it may take a while before the updates are available in live docs. Thanks!

**Closed by e0i** 2020-02-11 22:40 UTC
