### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by hoffimar** [MicrosoftDocs/windows-itpro-docs#4146] opened 2019-06-20 09:38 UTC
The link to https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview.md (Overview of Windows as a service) results in a 404 page not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684ab805-b732-043b-9d4c-e8c02660557a
* Version Independent ID: 5c288d08-f2cb-3927-93cb-acb2412fc62c
* Content: [Windows 10 Enterprise LTSC](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/#feedback)
* Content Source: [windows/whats-new/ltsc/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/ltsc/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by jvsam** [comment] 2019-06-20 23:03
@officedocsbot assign @jvsam

**Comment by illfated** [comment] 2019-06-22 08:06
Yes, it should have been https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview (without `.md` at the end).
This needs to be handled by MS internals with write access to the docs.microsoft.com pages,
because the Github page works just fine -- as expected and intended.
(Not much we regular users can do about it, there is no need to change the Github page.)

**Comment by jvsam** [comment] 2019-06-23 10:14
Hi @hoffimar, thank you for letting us know about the broken link. As pointed out by @illfated, the link to the *[Overview of Windows as a service](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-overview.md)* page in the Github doc is correct. However, this doesn't reflect on docs.microsoft.com.

Hello @greg-lindsay, would you be able to assist us here when time permits? Or is it already in the *doc updates* pipeline and just waiting to be implemented? If not, can you please advise on how to proceed and if action is required from our end? Thank you very much for your help.

**Comment by jvsam** [comment] 2019-06-29 07:34
Hi @hoffimar I'd like to let you know that the broken link has been corrected. We will now close this issue. Thank you again for taking the time to share your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-06-29 07:37
@officedocsbot close

**Closed by jvsam** 2019-06-29 07:37 UTC

**Comment by illfated** [comment] 2019-06-29 14:58
Issue solved by internal update publicized 06/25/2019 (4 days ago as of the time of this comment). Thank you for keeping us updated on this issue.

**Comment by illfated** [comment] 2019-06-29 15:05
Sad to say, the page has been changed to work on docs.microsoft.com, but not on Github.
The docs.microsoft.com now works as intended, but at the cost of breaking the Github link.
