### ISSUE TITLE
VM TPM Error code

### ISSUE THREAD

**Issue by lanatmwan** [MicrosoftDocs/windows-itpro-docs#4766] opened 2019-08-22 19:44 UTC
The documentation indicates you will get a 0x800705B4 timeout error if you try self deployment to a VM due to the unsupported hyper-v TPM. I am not sure if that is an error displayed somewhere, but it is not the error I experienced. During the OOBE setup on a VM that I had targeted for self deployment I got a 0x801c03ea error during the "Device preparation" phase.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6867cc8c-868d-d472-8aa5-1ed5b94ced2c
* Version Independent ID: 6822e12d-7474-9e49-1e8b-88f7eec3b22c
* Content: [Windows Autopilot Self-Deploying mode](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/self-deploying)
* Content Source: [windows/deployment/windows-autopilot/self-deploying.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment] 2019-08-22 20:12
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-08-26 13:09
@lanatmwan 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by illfated** [comment] 2019-08-28 16:11
@lanatmwan : You have closed the issue, but nothing has been done to resolve the issue yet.
Please consider reopening the issue ticket so we can follow up on this issue.

**Comment by greg-lindsay** [comment] 2019-10-15 20:41
Hi, the error code mentioned is not specific to a VM and the note is correct as written. However, I could add some more detail here about other codes.

See https://www.petervanderwoude.nl/post/windows-autopilot-self-deploying-mode/


Error | Description
-- | --
0x800705B4 | This error means that the device is either a virtual machine, or does not have TPM 2.0, and is not capable of running Autopilot self-deploying.
0x801c03ea | This error means that the device is TPM 2.0 capable, but that the TPM still needs to be upgraded from 1.2 to 2.0.
0xc1036501 | This error means that the device cannot do an automatic MDM enrollment, because there are multiple MDM configurations in Azure AD.

**Comment by greg-lindsay** [comment] 2019-10-15 20:43
I'm closing the issue for now. I will update the article to add more codes and describe the other reasons.

**Comment by illfated** [comment] 2019-10-15 20:44
Thank you for the follow-up and comments. Appreciated.

**Closed by greg-lindsay** 2019-10-15 20:43 UTC

**Comment by greg-lindsay** [comment] 2019-10-17 21:59
Update: The article linked above actually turns out to be a little off.  I've added these three codes to our documentation with explanations. The first code (0x800705B4) is more accurately a timeout that can be caused by many issues, one of which is that the device does not have TPM 2.0.

The second code (0x801c03ea) - which is what this post asked about - means that the device couldn't join Azure Active Directory using a device token because TPM attestation failed.  One possible cause might be that the device is using TPM 1.2 rather than 2.0.

**Comment by illfated** [comment] 2019-10-18 12:41
👍 Thank you for the update. Looks very useful (although not directly affecting my line of work).
