### ISSUE TITLE
Broken link for the Trust model status

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/windows-itpro-docs#5847] opened 2020-01-15 14:29 UTC
Surface Hub and the Skype for Business Trusted Domain List link is broken - it leads to non-existent page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483bb152-c6ff-978f-297d-89b1fdb12350
* Version Independent ID: daefe8d1-0f6e-09e1-c1d8-90444f8c0c88
* Content: [Using the Surface Hub Hardware Diagnostic Tool to test a device account - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/use-surface-hub-diagnostic-test-device-account#feedback)
* Content Source: [devices/surface-hub/use-surface-hub-diagnostic-test-device-account.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/use-surface-hub-diagnostic-test-device-account.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by RAJU2529** [comment] 2020-01-15 14:49
Issue conformed.

**Comment by RAJU2529** [comment] 2020-01-15 14:54
I think for every users , they might add different  domains as trusted.
So you must add your own list.

**Comment by Larryngolog** [comment] 2020-01-15 14:58
I'm not sure if you understand me correctly - when I click on the Reference link for the Trust Model Status (https://blogs.technet.microsoft.com/y0av/2017/10/25/95/) I get an error that server IP is unknown. Looks like the the URL should be https://y0av.me/2017/10/25/surface-hub-and-the-skype-for-business-trusted-domain-list-2/

**Comment by RAJU2529** [comment] 2020-01-15 16:01
@Larryngolog .
Both the links are opened in edge browser on  my windows 10  1909  18363.592 laptop
![001](https://user-images.githubusercontent.com/3296790/72449290-6bdaf300-37de-11ea-9dfe-3a724491a71c.JPG)
![002](https://user-images.githubusercontent.com/3296790/72449291-6c738980-37de-11ea-99b2-c9115167f9c2.JPG)

**Comment by Larryngolog** [comment] 2020-01-15 16:09
Interesting - I'm using Edge Microsoft Edge 44.18362.449.0 on Win 10, Edge on Chromium beta 79.0.309.65 and IE 11.535.18362.0. The url https://blogs.technet.microsoft.com/y0av/2017/10/25/95/ redirects to https://y0av.me2017/10/25/95/ which is incorrect (two issues - first there is no slash between me and 2017. Even if I fix it it does not display the page - states that page does not exist.

**Comment by RAJU2529** [comment] 2020-01-15 16:42
@Larryngolog . below site is opening fine 

https://y0av.me/2017/10/25/surface-hub-and-the-skype-for-business-trusted-domain-list-2/

**Comment by RAJU2529** [comment] 2020-01-16 02:16
@illfated. PR is closed with unmerged.  reason told by @e0i is third party link it seems.
the link embedded in the article does opening

**Comment by illfated** [comment] 2020-01-16 16:58
@RAJU2529 : That much is true, the link https://blogs.technet.microsoft.com/y0av/2017/10/25/95/ opens fine for me too, even though the page does not look as well formatted as traditional Microsoft pages. And yes, it is not accepted to add non-Microsoft links (only *.microsoft.com domain) in Microsoft documentation pages, unless the documentation shows that it is referencing a partner page outside of the microsoft.com domain.

For now, it does not seem to be much we can do about this, seeing that the link works for most of us, which makes it more likely that this may be a local problem to the original issue reporter (@Larryngolog ).

If anything at all should be done to change the link, I am fairly certain we need to have it confirmed first by any of the Microsoft Docs team members, documentation authors or members of the technical team.

**Comment by e0i** [comment] 2020-02-01 15:53
The links are being removed because they are third party. Thank you for the discussion.

**Comment by e0i** [comment] 2020-02-11 19:09
Closing via #5863. @Larryngolog Thank you for feedback.

**Closed by e0i** 2020-02-11 19:09 UTC
Labels: devices
