### ISSUE TITLE
Autoplay/TurnOffAutoPlay 

### ISSUE THREAD

**Issue by okieselbach** [MicrosoftDocs/windows-itpro-docs#1626] opened 2018-09-12 18:39 UTC
Hi,
I tested the Autoplay/TurnOffAutoPlay on latest Insider, 1803 and 1709 and it's not working when targeted to ./Device it only works only for ./User/Vendor/MSFT/Policy/Config/Autoplay/TurnOffAutoPlay. I tested it with a value of: &lt;enabled/&gt;&lt;data id="Autorun_Box" value="255"&gt;

can this be clarified if it should work with ./Device, my tests have shown it's working only with ./User. Thanks.

best,
Oliver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b604877-d2f9-a8eb-e986-48be52e55250
* Version Independent ID: 60a7b06f-25bb-91aa-9d99-76525506e2a7
* Content: [Policy CSP - Autoplay](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-autoplay)
* Content Source: [windows/client-management/mdm/policy-csp-autoplay.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-autoplay.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by okieselbach** [comment] 2019-04-24 14:54
nothing happened... closing now.

**Comment by illfated** [comment] 2019-04-24 18:31
I'm sorry to see that your feedback has waited for feedback so long without receiving any. That is not your fault.

Would you mind re-opening the issue, so we can evaluate the feedback and maybe provide corrections to the documentation page?

@MaratMussabekov : Do you have any experience with this topic, that you could suggest some improvement to the article?

**Comment by illfated** [comment] 2019-04-25 03:59
@Heidilohr : Would you be able to follow up on this issue ticket?
(Maybe assign someone else if your work tasks have changed.)

**Comment by MaratMussabekov** [comment] 2019-04-25 05:25
Dear @illfated , sorry I do not have any improvements for this article...
Thank you

**Comment by jvsam** [comment] 2019-06-07 01:48
@officedocsbot assign @jvsam

**Comment by somacoder** [comment] 2020-06-04 03:01
You don't have the closing forward slash at the end of the value, which could be why you saw the difference between ./User and ./Device .

<enabled/><data id="Autorun_Box" value="255"/>

**Comment by illfated** [comment] 2020-06-04 05:01
@somacoder : Thank you for pointing to what could be wrong here.

Is there anything we can do to correct the documentation, if the slash is missing somewhere? 
I tried to find the string you referenced in the page, but I can't find where it is located.
( `<enabled/><data id="Autorun_Box" value="255"/>` )

**Comment by joinimran** [comment] 2020-10-22 16:14
The page contains all of the required information. @okieselbach make sure you are properly using the commands using SyncML format. @somacoder provided example is the correct format while writing in SyncML.

Thanks
Imran.

**Comment by nam31** [comment] 2020-11-04 13:20
@okieselbach Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2020-11-04 13:20 UTC
Labels: assigned-to-author, client management
