### ISSUE TITLE
Filepath rules not available on Windows Server - Enforcement mode appears unusable

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/windows-itpro-docs#9383] opened 2021-04-01 05:41 UTC
This particular page states it "Applies to: Windows Server 2016". However a key to operation is this series of lines:

```
$PathRules += New-CIPolicyRule -FilePathRule "%windir%\*"
$PathRules += New-CIPolicyRule -FilePathRule "%OSDrive%\Program Files\*"
$PathRules += New-CIPolicyRule -FilePathRule "%OSDrive%\Program Files (x86)\*"
```

Unfortunately, "FilePathRule" is noted on this page: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create that the parameter is `Beginning with Windows 10 version 1903`. This appears accurate, as running on an up to date Windows 2019 Server will produce the output 
`New-CIPolicyRule : A parameter cannot be found that matches parameter name 'FilePathRule'.`

The simple description of this issue is that the "Applies to" is incorrect for this page. However as far as I can see there are some implications for the whole WDAC here.

Unfortunately on a totally base Windows installation, tonnes of legitimate operation generates assemblies with audit alerts such as below:

```
Code Integrity testing module \Windows\assembly\NativeImages_v4.0.30319_64\System.Serv759bfb78#\bd8e43b787e96a398951bc00e217015b\System.ServiceProcess.ni.dll against policy DefaultMicrosoftEnforced. Status System Integrity policy has been violated.
```

These files are generated on the fly by the Windows OS, have changing file paths and are not signed. I cannot see a feasible way of actually using any of the WDAC functionality without a FilePathRule for C:\Windows\assembly\. In the absence of the FilePathRule or an alternate way to allow such assemblies, the whole WDAC feature doesn't feature doesn't appear to be usable on Windows Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebdf50c3-2221-5d9e-6823-7827e5c7de47
* Version Independent ID: 845470fb-17a6-1fd5-d79a-7b83950b9527
* Content: [Create a WDAC policy for lightly-managed devices (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-lightly-managed-devices)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-lightly-managed-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-lightly-managed-devices.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by technion** [comment] 2021-04-06 10:59
For a trivial example, opening services.msc fills the event log with errors and fails to render properly. Without the ability to create a FilePathRule I don't believe this can be fixed.

**Comment by jsuther1974** [comment] 2021-04-06 18:01
It is not necessary to use file path rules to make WDAC work. WDAC was introduced in the original Windows 10 release without any file path rule type. File path rules were added in 1903 and will arrive on Server Edition with the upcoming Windows Server 2022 release. The topic mentioned, Create WDAC policy for lightly managed devices, does include a note that some of the steps are specific to 1903+ features and you may need to implement your policy differently on older versions of the OS using other types of rules to achieve your policy goals.

Specific to .Net generated images, you may see false positive block messages on some files when running a WDAC audit mode policy. .Net native images are generally backed by a non-native (IL or interpreted language) version of the binary. When WDAC "blocks" a native image, you should actually see the system fallback to the IL image and no actual functional block occurs on the system. .Net schedules these native images to be regenerated at the next servicing window after which both the native images and the IL image should function without any errors. We have done work in WDAC to filter these false positives in later updates so the events generated are more reflective of the actual results.

**Comment by e0i** [comment] 2021-04-07 23:01
It seems that the question has been answered by the community,  and the issue is being marked as resolved. 

Thanks.

**Closed by e0i** 2021-04-07 23:01 UTC
Labels: application control
