### ISSUE TITLE
Is Credential Guard supported on W10 Pro

### ISSUE THREAD

**Issue by JonZeolla** [MicrosoftDocs/windows-itpro-docs#4025] opened 2019-06-13 20:38 UTC
The guidance on this doc appears to conflict with [this](https://www.microsoft.com/en-us/windowsforbusiness/compare) with regard to Credential Guard.  Is CG available on Windows 10 Pro or only Enterprise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0238a73f-da06-ae17-c61d-85ae54e0f7cb
* Version Independent ID: e5bb4a25-a7c3-3a16-bd95-d6f2513402e0
* Content: [Windows Defender Credential Guard Requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment] 2019-06-13 23:17
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment] 2019-06-15 08:20
@Jonzeolla on enterprise OS those feathers are  available.
Check the recommend requirements again

**Comment by JonZeolla** [comment] 2019-06-15 11:45
I'm pretty sure I have reviewed it properly.  I also see another [issue](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3255) which whose root cause may also be the unclear documenation.

**Comment by RAJU2529** [comment] 2019-06-15 11:58
@JonZeolla 

just now i checked on system information .On my machine Credential Guard is running fine .
enable LSA.exe. 
i attached  screenshots and  device guard registry settings with this reply

![credentialguard](https://user-images.githubusercontent.com/3296790/59551143-c6834680-8f92-11e9-9fd6-932d254a9e3a.JPG)
![rek1](https://user-images.githubusercontent.com/3296790/59551144-c71bdd00-8f92-11e9-9401-e66f5697e757.JPG)
![rek2](https://user-images.githubusercontent.com/3296790/59551145-c71bdd00-8f92-11e9-9ee8-ff032630b02b.JPG)
![rek3](https://user-images.githubusercontent.com/3296790/59551146-c7b47380-8f92-11e9-9db8-f0f5d8079887.JPG)
![rek4](https://user-images.githubusercontent.com/3296790/59551147-c7b47380-8f92-11e9-9736-166be4782c53.JPG)

**Comment by RAJU2529** [comment] 2019-06-15 12:01
[Desktop.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3293062/Desktop.zip)
try to enable  device guard in group policy editor.
Note if  you enable device guard , then you wont be able u to use  virtualization technology  ,eventhough if you enable intel VT d VTx enaled in bios

**Comment by JonZeolla** [comment] 2019-06-15 12:43
Win 10 Pro?

**Comment by RAJU2529** [comment] 2019-06-15 13:10
Sir I am using enterprise . But pro edition I dont have. Check with group policy editor.

**Comment by JonZeolla** [comment] 2019-06-15 17:20
Okay.  I'm not concerned about Enterprise, it's whether or not Pro supports it that is my question

**Comment by RAJU2529** [comment] 2019-06-15 18:29
Sir did you Checked with group policy editor. Or add the registry key that I was mentioned. and then restart the Windows. and see credential gurad is running or Not .

Without trying any ways, then there is No point to answer

**Comment by JonZeolla** [comment] 2019-06-15 18:39
I don't have a Windows 10 Pro license to test any of this out.  I'm opening this ticket because someone who is looking to decide between Pro and Enterprise doesn't have a clear answer on this feature from Microsoft

**Comment by jvsam** [comment] 2019-06-15 19:34
Hi @JonZeolla we appreciate you taking the time to open this issue and ask your question. As you have indicated, in the [Windows 10 Editions Comparison](https://www.microsoft.com/en-us/windowsforbusiness/compare) table, Windows 10 Pro supports Windows Defender Credential Guard (*x64 version of Windows*) and it should also reflect on related documentations to avoid confusion. Though I'd like to point out as well that the article states it applies to *Windows 10* in general. 

I will forward this issue to the Windows writing team for review and if the documentation needs to  be updated, then amendments will  be submitted (*pending approval*). Thank you and we appreciate your feedback. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date.

**Comment by RAJU2529** [comment] 2019-06-21 11:05
@JonZeolla , Today I confirmed that I enabled credential guard by gpo and working fine on windows 10 pro 1809 64bit.

**Comment by JonZeolla** [comment] 2019-06-23 00:04
Thank you for the clarification and testing!  Closing this ticket.

**Comment by jvsam** [comment] 2019-06-23 03:12
Hi @RAJU2529 thank you so much for your assistance. Keep up the good work!

@JonZeolla since you have closed this issue, then it's considered *resolved*. However, feel free to re-open if you have suggestions to improve the quality of this documentation and we will submit them for review. Thanks for being part of the Microsoft Docs community!

**Comment by JonZeolla** [comment] 2019-07-24 14:27
FYI this is related to https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d34ec3dade35a269ded076d327ffc473873e76d8

**Comment by jvsam** [comment] 2019-08-04 15:44
Thanks for referencing that issue @JonZeolla, however, that documentation is for Windows Defender Application Control (WDAC) and looking at the [comparison table](https://www.microsoft.com/windowsforbusiness/compare), WDAC is not available for Windows 10 Pro, which is the same as the suggested update on #3255 (*Although on #2430, the Intune team confirmed that WDAC policies will work on Windows 10 Pro*).

As for this documentation, I missed this part before, but it does explicitly mention the baseline protection requirements for OS—*Windows 10 Enterprise, Windows 10 Education, Windows Server 2016, or Windows 10 IoT Enterprise* (*and as of Windows 10, Version 1607, Credential Guard is an integrated enterprise feature*). There goes your answer to your original question. Now the comparison table, which shows Windows Defender Credential Guard's availability on Windows 10 Pro, is not part of the docs and there is nothing that we can do to request amendments. Perhaps submitting it through [the Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) may be your best option. Let me know if I have misunderstood your concern. Thanks.

**Comment by JonZeolla** [comment] 2019-08-05 10:23
Thank you, the pointer to the feedback hub was helpful.

**Comment by jvsam** [comment] 2019-08-07 14:34
You're welcome @JonZeolla. Thank you again for taking the time to share your feedback and for being part of the Microsoft Docs community!

**Comment by tecxx** [comment] 2020-10-01 13:26
based on my experience, Windows 10 PRO DOES NOT support credential guard, to the contrary of some of the things people wrote in this thread - we have tested this 2 years ago, and today again.

just checking the output of msinfo32 or regedit is not enough, yes it's correct it shows that CG is running. but you need to actually test the functionality of CG with hacking tools like mimikatz. here is the result:

win10 enterprise, 2004, patchlevel 2020-09, 10.0.19041
![image](https://user-images.githubusercontent.com/4305825/94813836-cf529280-03f8-11eb-8d74-6637a4f95c4e.png)


win10 pro, 2004, patchlevel 2020-09, 10.0.19041
![image](https://user-images.githubusercontent.com/4305825/94813878-da0d2780-03f8-11eb-9a73-ce3d128b9681.png)


as you can see, 

in win10 **enterprise the credentials are encrypted** by credential guard and therefore not readable by mimikatz (LSA Isolated Data)
in win10 **pro however the ntlm hash is not encrypted** and can therefore be stolen and abused for lateral movement.

i do not know if this is a bug, or a misconfiguration on our end somewhere, but we specifically tested this already 2 years ago and made the decision to invest into the enterprise edition because of this finding. and i'm pretty sure back then the docs clearly said "enterprise only".
this may have been changed in the meantime, but then something isn't working correctly.

**Comment by RAJU2529** [comment] 2020-10-01 13:57
@tecxx . Which command did you entered  in mimikartz for getting Above screen shot result

**Comment by tecxx** [comment] 2020-10-01 14:00
# gain debug rights
privilege::debug 
# read credentials
sekurlsa::logonpasswords

in case you run other protections like PPL as well additional steps might be necessary, but that's the very basic command to extract your secrets.

**Comment by beerisgood** [comment] 2020-10-01 14:19
So Windows itself display the result wrong.
This should be fixed too!

Thanks for a real test @tecxx

**Comment by RAJU2529** [comment] 2020-10-01 14:40
@tecxx . @beerisgood . Even in my windows 10 os , even mimikatz cannot retrieve my logon passwords  . so my credentials are safe

**Comment by tecxx** [comment] 2020-10-01 14:47
can you post a screenshot of this? are you connected to a domain?

**Comment by RAJU2529** [comment] 2020-10-01 14:51
@Tecxx . IAM eating food

**Comment by beerisgood** [comment] 2020-10-01 15:13
> @tecxx . @beerisgood . Even in my windows 10 os , even mimikatz cannot retrieve my logon passwords . so my credentials are safe

Why ?

**Comment by RAJU2529** [comment] 2020-10-01 15:18
> > @tecxx . @beerisgood . Even in my windows 10 os , even mimikatz cannot retrieve my logon passwords . so my credentials are safe
> 
> Why ?

Because i  have certain settings by using group policy editor and by registry key.

**Comment by tecxx** [comment] 2020-10-01 15:21
@RAJU2529  is your computer connected to a domain?

**Comment by RAJU2529** [comment] 2020-10-01 15:22
@tecxx. @beerisgood , My windows 10 laptop does not connected to the domain, it's a  standard alone computer.
below are the screenshots of the mimikatz 

![add01](https://user-images.githubusercontent.com/3296790/94829309-01c7b400-0428-11eb-9045-dc55f537fa52.JPG)
![add02](https://user-images.githubusercontent.com/3296790/94829340-08eec200-0428-11eb-914a-55c15563f2f5.JPG)
![add03](https://user-images.githubusercontent.com/3296790/94829356-0db37600-0428-11eb-8277-c5b1b48f64e9.JPG)

**Comment by tecxx** [comment] 2020-10-01 15:24
you have abviously no idea what you are talking about. 
credential guard protects DOMAIN CREDENTIALS only and has no effect on local credentials.
the screenshot error you posted is the error message when mimikatz can not open the lsass memory space, which can either be because you are not running mimikatz as admin, you have an AV/EDR blocking it, or you are running PPL protection, which, as i mentioned above, must first be removed with additional steps.

anyway. since your pc is not in a domain it does not matter what you test. your credentials will never be protected by CG.

**Comment by tecxx** [comment] 2020-10-01 15:53
@RAJU2529 alright, good we could clarify this, but again, with a standalone system making any statement about CG is pointless, as it only protects domain credentials ([see limitations](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-protection-limits)). thanks for following through though.

**Comment by tecxx** [comment] 2020-10-05 18:33
on friday i opened a case with microsoft, here is their response from today:

![image](https://user-images.githubusercontent.com/4305825/95117923-a2c8ae80-0749-11eb-88ec-06a59660a27e.png)

**Comment by beerisgood** [comment] 2020-10-05 19:09
But even if Pro would be supported, it wouldn't work on non-domain PC right? @tecxx 
So normal users like us can't benefit from that anyway.

**Comment by tecxx** [comment] 2020-10-05 19:57
@beerisgood correct ([link](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-protection-limits)) currently it's a feature designed to [protect domain credentials](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard).

**Comment by nam31** [comment] 2020-10-08 14:18
I guess as per last conversations we are good to close this issue now. Correct @tecxx @beerisgood

**Comment by beerisgood** [comment] 2020-10-08 14:55
Yeah everything is written, also thanks for the great help.
Now this research should be used in DG_Readiness_Tool too

**Comment by nam31** [comment] 2020-10-08 16:29
Thank you

**Closed by nam31** 2020-10-08 16:29 UTC

**Comment by tecxx** [comment] 2020-10-08 16:37
not sure i understand - the documentation still does not mention Enterprise SKU as a requirement (https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements) ?

**Comment by tecxx** [comment] 2020-10-08 16:39
and this documentation still is unclear as well:
https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage
![image](https://user-images.githubusercontent.com/4305825/95488157-7d2fe500-0995-11eb-85b3-22f9944d9cb2.png)

"Windows 10 >=1909" suggests any SKU works, which is not correct.

**Comment by tecxx** [comment] 2020-10-08 16:46
@nam31 don't get me wrong but why all this effort to test, and open tickets with MSRC, and stuff - when then the documentation is not updated accordingly. can you please reopen and have this changed for good?

**Comment by illfated** [comment] 2020-10-09 13:17
Thank you for doing all the work to prove that only Enterprise & Education is covered by Credential Guard. I will open a Pull Request to have that text changed accordingly.

Please suggest additional changes or additional sections in need of this detail, besides the "Applies to" section.

**Comment by illfated** [comment] 2020-10-09 13:43
Feel free to comment & add suggestions for further improvements in my pull requests #8435 & #8436 .
