### ISSUE TITLE
typo in FQDN

### ISSUE THREAD

**Issue by ruffy91** [MicrosoftDocs/windows-itpro-docs#8873] opened 2020-12-27 20:50 UTC
The FQDN "1storecatalogrevocation.storequality.microsoft.com" does not exist, it should probably be "storecatalogrevocation.storequality.microsoft.com"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 86af6b9e-99a1-3626-0ba9-285ddf3681d0
* Version Independent ID: 455af345-7fc9-24d6-f554-b78cbccd3419
* Content: [Verbindungsendpunkte für Windows 10 Enterprise, Version 20H2 - Windows Privacy](https://docs.microsoft.com/de-de/windows/privacy/manage-windows-20h2-endpoints)
* Content Source: [windows/privacy/manage-windows-20H2-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-windows-20H2-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Gental-Giant
* Microsoft Alias: **v-hakima**

**Comment by illfated** [comment] 2020-12-27 22:27
Fair point, it looks like a sloppy transfer of the digit 1 from the previous column there:

|Area|Description|Protocol|Destination|
|----------------|----------|:--------:|:----------:|
||The following endpoints are used to revoke licenses for malicious apps in the Microsoft Store. To turn off traffic for this endpoint, either uninstall the app or disable the Microsoft Store. If you disable the Microsoft Store, other Microsoft Store apps cannot be installed or updated. Additionally, the Microsoft Store won't be able to revoke malicious apps and users will still be able to open them|TLSv1.2|1storecatalogrevocation.storequality.microsoft.com|
|||HTTPS/HTTPS/HTTP|storecatalogrevocation.storequality.microsoft.com|

By the way, do you know why the 3rd column in the last row (in the excerpt above) contains the protocol value `HTTPS/HTTPS/HTTP` ?
Does that make sense in this context? I would have thought it could just as easily be merged with the row above and be shortened to `HTTPS/HTTPS` and placed on a second line beneath `TLSv1.2`, but I could easily be mistaken since I don't know this topic well enough.

**Comment by illfated** [comment] 2020-12-27 22:33
Reading the table again, I start wondering if the hostname (`1storecatalogrevocation`) for some unknown reason would only responding to TLSv1.2 (as described in the table) and that the hostname `storecatalogrevocation` responds to `HTTP/HTTPS` — but I don't know. (Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.)

**Comment by ruffy91** [comment] 2020-12-27 22:36
Ah yes, as you mention it.
It would probably make sense to merge the lines and use "TLSv1.2/HTTPS/HTTP" as the protocol like on other lines.
I did not see any use of 1storecatalogrevocation.storequality.microsoft.com in my tests, also there is no A or AAAA DNS record for this endpoint, which makes me assume this is a typo.

**Comment by illfated** [comment] 2020-12-27 22:41
Fair enough, thanks for the clarifying follow-up and useful reasoning. I can make a PR for that change, then we'll see what the MS Docs team say about it. (Needs to be confirmed by document author/team manager, or similar authority.

**Comment by illfated** [comment] 2020-12-27 23:02
There you go. PR #8877 is ready for review, comments and suggestions.

**Closed** 2021-01-08 16:50 UTC
Labels: privacy
