### ISSUE TITLE
Silent Administrative installation

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/windows-itpro-docs#3398] opened 2019-04-29 17:59 UTC
Is it supported to have the dock firmware pushed out through a management system like SCCM to administratively update many docks quickly? Having trouble finding documentation for or against this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Updater (Surface)](https://docs.microsoft.com/en-us/surface/surface-dock-updater#feedback)
* Content Source: [devices/surface/surface-dock-updater.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-dock-updater.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment] 2019-05-01 10:01
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-05-01 10:02
@Typhoon87 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment] 2019-05-01 10:30
A similar question has been asked in #1679, but not received any news or updates yet. It has only been communicated to the Surface engineering team to be considered in their future product plans. (ref. https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1679#issuecomment-424808499)

**Comment by illfated** [comment] 2019-05-01 10:36
@Typhoon87 : I can only make educated guesses for why we are not seeing any information about this type of feature yet. There may be a need for further development to make the software package support silent administrative application, to avoid issues with missing connection with the Surface dock, handling errors and so on. I hope the Surface engineering team can provide some kind of confirmation of the status of this feature request. (@mypil : Maybe you could check which one in the Docs team has a working connection with the Surface engineering team?)

**Comment by Typhoon87** [comment] 2019-05-02 15:32
I read the comment that you had mentioned above and it is the same basic question. So I would take that as its not officially supported as of now. 
The issue doing this type of process is not easy to convince non technical users to do this. Once you have even a small fleet of these docks this becomes very difficult to ensure the firmware is updated in a timely and organized manner.

Thank you for looking further into this issue for me.

**Comment by mypil** [comment] 2019-05-02 16:18
@illfated - Thanks for your inputs. @Malind19 is currently investigating on this issue. Thanks.

**Comment by Malind19** [comment] 2019-05-02 19:51
@mypil I too find no proper answer as it is officially supported. Every source I found looks like had no good experience with that. So my suggestion is also it is not officially supported. May be we shall confirm with the author.

**Comment by mypil** [comment] 2019-05-03 10:18
@DaniHalfin @BRecords - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment] 2019-05-10 10:07
@DaniHalfin @BRecords - We would like to follow up. Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment] 2019-05-17 08:30
@DaniHalfin @BRecords @jaimeo @Justinha @mjcaparas @greg-lindsay - Can you please share your insights on this issue?

Thank you.

**Comment by vsk2005** [comment] 2019-05-20 20:31
We have around 1000 docks and looking for solution as well

**Comment by DaniHalfin** [comment] 2019-05-20 20:34
@robmazz might be able to take a look at this.

**Comment by robmazz** [comment] 2019-05-20 21:10
@CoveMiner  - John Kaiser, can you help with this? Or do you have a contact that can help?

**Comment by Typhoon87** [comment] 2019-05-21 19:19
I don't know if it has to be totally silent but it would need to take into account non admin users if pushed by SCCM or similar system administration tool. If not totally silent needs user education tools first.

**Comment by mypil** [comment] 2019-05-23 16:41
@robmazz @CoveMiner - Do you have any updates on this?

**Comment by vsk2005** [comment] 2019-05-24 13:55
I couldn't find any code snippet or ways to do this programmatically. I don't know how MS is doing through Firmware driver update for Surface Pro. Manually updating each dock is not viable.

**Comment by illfated** [comment] 2019-05-24 19:20
@Typhoon87 , @vsk2005 : Have you tested if it is possible to get some form of output in a CMD window on a test computer, when using either `/?` or `--help` as arguments to the program file name command?
(I assume you may have tested it already, just asking in case you have not.)
I thought maybe if there would be a way to add arguments / parameters to run it as a login script command, but it is a long shot, really.

**Comment by mypil** [comment] 2019-05-28 14:30
@robmazz @CoveMiner - We would like to follow up. Do you have any updates?  Thanks.

**Comment by Typhoon87** [comment] 2019-05-28 19:02
> 
> 
> @Typhoon87 , @vsk2005 : Have you tested if it is possible to get some form of output in a CMD window on a test computer, when using either `/?` or `--help` as arguments to the program file name command?
> (I assume you may have tested it already, just asking in case you have not.)

Hell @illfated so I just tested this and the dock installer does not have any custom tips it just shows the generic MSIExec command list. This implies it supports every single switch under the sun which we know for most installers is not true or at least they are not all officially tested.

**Comment by illfated** [comment] 2019-05-29 01:24
Fair enough, thanks for the reply & feedback with your results.

**Comment by CoveMiner** [comment] 2019-05-29 03:58
Thanks everyone for the feedback. We'll be discussing this in weekly triage Wednesday morning to identify next steps for the documentation.

**Comment by Typhoon87** [comment] 2019-05-29 13:03
> 
> 
> Fair enough, thanks for the reply & feedback with your results.

Hello again @illfated No problem testing it. The other issues that brings up is the switches might allow you to install the firmware utility but how does it handle actually updating the firmware. The hard part about testing this with no documentation is you get one shot. You can take a dock that is behind in its FW deploy the updater then if it works that dock is updated (good) but you cant try to restest and ensure you get repeatable results until you get another different dock (bad). Its actually sort of amazing the Surface team did not foresee this becoming an issue.

**Comment by illfated** [comment] 2019-05-30 09:33
Fair and good point. Thank you for the extra insight. Judging by the feedback here, the firmware update software seems to be at a stage where it is not yet developed enough to be used in a corporate environment with more than a dozen users, where all docking stations need to be tested for upgradability or even all of them need to be upgraded for stability or functionality to work as intended and expected. I wish someone from the engineering team could provide some added insight or maybe even some information about any future plans for development of the software.

**Comment by mypil** [comment] 2019-06-06 10:55
@CoveMiner - We would like to follow up on this. Do you have any updates on how we can close this issue?

Thank you.

**Comment by mypil** [comment] 2019-06-10 09:32
@CoveMiner - Any updates on this?

**Comment by BRecords** [comment] 2019-06-10 17:32
Hi all, thank you for your interest in the Surface Dock Updater tool and process. As of today, we do not support silent update of Surface Dock firmware via the Surface Dock Updater tool or other channels. To update Surface Dock firmware, the Surface Dock Updater must be run with full UI and process.

Your feedback regarding a scalable update mechanism is heard, however I would encourage you also to provide feedback via the Feedback Hub, which is the best way to ensure your feedback is seen and heard by the product team(s).

**Comment by illfated** [comment] 2019-06-10 17:52
@BRecords : Thank you for your conclusive reply.

@Typhoon87 : Looks like it comes down to we thought it would be from the beginning, although there is hope you can affect the development in a positive way by using the Feedback Hub, as recommended above.

**Comment by mypil** [comment] 2019-06-12 09:48
@Typhoon87 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-06-12 09:49
@officedocsbot close

**Closed by mypil** 2019-06-12 09:49 UTC

**Comment by Typhoon87** [comment] 2019-06-12 22:25
@mypil I looked in the feedback hub and found a request to have the firmware in an SCCM package. There are a whopping 3 upvotes including mine in 5 months. Something like this needs a better way to give feedback RIP Connect

If anyone else finds this please see this feedback https://aka.ms/AA5bx7g

**Comment by vsk2005** [comment] 2019-09-27 18:35
https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update

finally a MSI released
