### ISSUE TITLE
Update Compliance - Documentation indicates that "Cloud-delivered protection" is required for Windows Defender Antivirus reporting

### ISSUE THREAD

**Issue by asdalmeida** [MicrosoftDocs/windows-itpro-docs#6194] opened 2020-03-10 08:45 UTC
In the "Confirm prerequisites" section above, "Cloud-delivered protection is enabled" is listed as a prerequisite for devices to properly show up in Update Compliance. However, it then goes on to state that "for E5 licenses, you need to use the Microsoft Defender ATP portal".
The problem is that "Cloud-delivered protection" is (as far as I can determine) a part of the E5 license benefit. Having it enabled will, 1) cause devices to not show up in Update Compliance and 2) probably lead customers into a non-compliant licensing situation.
Can you please confirm whether this a documentation error and "Cloud-delivered protection" is not required *OR* is the documentation correct and "Cloud-delivered protection" is a requirement for Windows Defender Antivirus reporting in Update Compliance?
(NOTE: If "Cloud-delivered protection" is needed, the Update Compliance documentation (at https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-wd-av-status) needs to be corrected to indicate this as well.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c83b7aed-5621-4b90-6eab-2fadbfe72586
* Version Independent ID: 06cfa791-6755-38f7-ca98-3d13c7c2ce7d
* Content: [Troubleshoot problems with reporting tools for Windows Defender AV - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/troubleshoot-reporting#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/troubleshoot-reporting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/troubleshoot-reporting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment] 2020-03-22 04:58
Hello @asdalmeida,
**The problem is that "Cloud-delivered protection" is (as far as I can determine) a part of the E5 license benefit**  - according to [this article](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-in-windows-10), it is a part of Windows Defender Antivirus, so it is available for any license that includes Windows Defender Antivirus.
Also, as on March 31, 2020, the Windows Defender Antivirus reporting feature of Update Compliance will be removed, I think there is a need to add this note to the article.
Thank you

**Comment by asdalmeida** [comment] 2020-03-23 09:06
Hello @MaratMussabekov,

I agree that with the removal of the Windows Defender Antivirus reporting feature of Update Compliance this question becomes irrelevant (as does this page?).

As for the article you linked, it is not clear *to me* from the text whether "cloud-delivered protection" is a base part of Windows Defender Antivirus or whether it is part of the "next generation protection" that you get when you have Windows Defender Advanced Threat Protection licensing (E5).
Either way, the question on whether it needs to be enabled or not is now irrelevant as the Windows Defender Antivirus reporting feature of Update Compliance is going away as of March 31, 2020.

Thank you for your time on this.

**Comment by MaratMussabekov** [comment] 2020-03-25 04:31
Hello @asdalmeida,
I believe it is a base part, because it is listed [here](https://www.microsoft.com/en-us/windows/comprehensive-security). 

Thank you

**Comment by asdalmeida** [comment] 2020-03-25 08:29
Hello @MaratMussabekov,
Thank you for the additional link. That clarifies it for me.
Thank you again!

**Comment by mypil** [comment] 2020-03-25 21:38
@asdalmeida  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-03-25 21:38 UTC
Labels: windows defender antivirus
