### ISSUE TITLE
Перевод констант

### ISSUE THREAD

**Issue by rekby** [MicrosoftDocs/windows-itpro-docs#4933] opened 2019-09-13 10:47 UTC
Не надо константы писать русскими буквами

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
* Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
* Content: [Список кодов ошибок Центра обновления Windows по компонентам](https://docs.microsoft.com/ru-ru/windows/deployment/update/windows-update-error-reference#feedback)
* Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-error-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by illfated** [comment] 2019-09-13 11:34
Keeping the code names together with underscore
between the various parts of the keywords does not
seem to be enough to keep them from being auto translated.
I think we need to implement stronger delimitations, for example
MarkDown code block fences to show the text as monospaced typeface.

@TinaMcN : Would you like to have a PR with code blocks made to the EN-US version,
that it might transfer to the translated pages and hopefully block translations?

**Comment by jvsam** [comment] 2019-09-13 13:36
@officedocsbot assign @jvsam

**Comment by TinaMcN** [comment] 2019-09-13 18:01
Yes @illfated that sounds good.

**Comment by illfated** [comment] 2019-09-13 18:11
Fair enough. I hope my suggestion will not go against Greg Lindsay's view of how the content should be presented.
As usual, we need patience before the changes go live and migrate to the affected pages.

**Comment by jvsam** [comment] 2019-09-15 21:21
Thanks @illfated. Let us suggest it then.  Will you create a PR? 

Thanks too @TinaMcN. Should I assign this to you?

**Comment by illfated** [comment] 2019-09-16 01:01
PR created. It was somewhat delayed, partly because of a cold that I caught at the end of the week, partly because of some minor redecoration going on at home.

**Comment by e0i** [comment] 2019-09-16 18:38
cc @jvsam

**Comment by jvsam** [comment] 2019-09-21 04:59
Awesome, thanks @illfated.

**Comment by illfated** [comment] 2019-10-28 17:16
The PR has been merged just about 35 minutes ago, but that is only into the public branch. I presume we will have to wait about a week for the migration to docs.microsoft.com and the subsequent translation (unless the translation is merely "on-the-fly" translation each time the page is loaded).

**Comment by TinaMcN** [comment] 2019-10-28 20:21
@illfated machine translation is run on updated files once per day (after 6pm PST) after they have been published to docs.microsoft.com

**Comment by jvsam** [comment] 2019-10-31 18:27
Thank you @illfated and @TinaMcN. There are still constant values that were machine translated, e.g. GetClientError(). Are those in the process of getting corrected (*human translated*)?

**Comment by TinaMcN** [comment] 2019-10-31 22:53
I see what you mean @jvsam  The values that are not in tables but in the middle of sentences are still being overlocalized, like the references in this example.
![image](https://user-images.githubusercontent.com/53281468/67991452-80074f00-fbf6-11e9-8d26-afcc014ac9c2.png)
I'll send this topic to be human translated.   It will take 2-3 weeks to be completed.

**Comment by illfated** [comment] 2019-10-31 23:35
I was thinking about suggesting to add back ticks around the extra constants in the non-table text, but seeing that my related PR took 6 weeks from start to finish, it seems faster to have the page manually translated for the remaining surplus translations by MT.

**Comment by jvsam** [comment] 2019-11-08 19:10
Thanks @TinaMcN. 

I agree with you @illfated!

**Comment by jvsam** [comment] 2019-11-13 06:17
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment] 2019-11-13 21:37
Статья теперь человек переведен.  Пожалуйста, убедитесь, что проблема исправлена.  Еще раз спасибо за обратную связь. (The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by jvsam** [comment] 2019-11-18 01:33
Looks great! Thank you so much for the update @TinaMcN.

@rekby, we can now consider this issue resolved. Thank you for your feedback and patience on this matter. We will now close this issue, but please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation through the doc's *feedback feature*.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-11-18 01:33
@officedocsbot close

**Closed by jvsam** 2019-11-18 01:33 UTC
Labels: deployment
