### ISSUE TITLE
Sidebar overlaying content in German version of article

### ISSUE THREAD

**Issue by d-Rickyy-b** [MicrosoftDocs/windows-itpro-docs#8075] opened 2020-08-17 08:09 UTC
Hi there,

sadly I can't use the "report on github" button, because of the issue I am reporting now.
The layout of the site mentioned below is broken in the German version. The left sidebar is overlaying part of the actual content of the site. See the attached screenshot:

![screenshot](https://i.imgur.com/N4V2wYR.png)

Also the 'Report bug on GitHub' button does not work, because it is overlayed. Editing the HTML so that the sidebar is gone, also doesn't help.

___
https://docs.microsoft.com/de-de/windows/security/threat-protection/auditing/event-4688

**Comment by RAJU2529** [comment] 2020-08-17 09:34
@d-Rickyy-b . did you able to see **This Page** at bottom

**Comment by illfated** [comment] 2020-08-17 18:15
Sure, I have confirmed this issue in 4 different browsers. It seems to be an issue with the scripting (CSS or JS) on this page, making the TOC part on the left side behave different than normal pages do.

The Google Chrome inspect feature informs me that the /de-de/ page contains 171 errors and 2 warnings, whereas the /en-us/ version of the page only contains 3 errors and 3 warnings. There is definitely something script-related to be fixed on the de-de page.

Unfortunately, regular users can't submit GitHub suggestions for how to correct this issue. The problem needs to be handled by the Microsoft web technicians.

**Comment by denisebmsft** [comment] 2020-08-17 19:40
@TinaMcN is this issue something your team can help resolve?

**Comment by illfated** [comment] 2020-08-17 22:25
@denisebmsft : I admit that I don't know what the translation team is capable of, but seeing that this is a website issue (CSS/JS scripting, HTML shaping) it would not be the first thing that comes to mind.

Nevertheless, we may as well wait for @TinaMcN to confirm whether the localization team is able to find any root causes in the translation layer.

**Comment by TinaMcN** [comment] 2020-08-17 22:44
@d-Rickyy-b thank you very much for reporting this.   The same issue occurs for all the translated pages.  I logged a bug for the localization engineers to investigate.

**Comment by e0i** [comment] 2020-08-25 23:19
@TinaMcN Has there been any developments regarding this issue? Thank you for letting us know.

**Comment by TinaMcN** [comment] 2020-08-25 23:34
@e0i it is still under investigation.  We thought it was fixed but it is not.   Hope to have more news in the next couple of days.

**Comment by TinaMcN** [comment] 2020-12-12 00:54
@d-Rickyy-b this issue is fixed now.  Thanks again for reporting it.  Please close if it looks ok for you too.

**Comment by illfated** [comment] 2020-12-12 01:30
Yay! Thank you for the good news. The page looks good now, that is for sure.

**Comment by d-Rickyy-b** [comment] 2020-12-12 04:31
Hi @TinaMcN, indeed much better now. The initial issue (sidebar overlaying content) is actually fixed. But I noticed some smaller issues:

There are some missing spaces and added slashes (left: English, right: German):
![grafik](https://user-images.githubusercontent.com/5798157/101975200-0a641400-3c3b-11eb-8185-5fbfe929f5fe.png)

![grafik](https://user-images.githubusercontent.com/5798157/101975198-0801ba00-3c3b-11eb-9290-7ee82d546a39.png)

Might even be worth its own issue.

**Comment by TinaMcN** [comment] 2020-12-14 23:10
@d-Rickyy-b thanks for letting us know about these issues, I sent them over to the localization vendors to fix.

**Closed** 2021-03-13 11:03 UTC
Labels: auditing, localization
