### ISSUE TITLE
Cant' SSO to windows server from AAD joined device after logging on with key.

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6355] opened 2020-03-27 23:58 UTC
Followed instructions.
I can logon to my AAD joined machine just fine with my AAD synced MFA account using a hardware key. I have AD Connect working perfectly.

When i try and access my AD domain joined server with \\myserver.mydomian.tld\share i get the following:
![image](https://user-images.githubusercontent.com/11369180/77809181-dc5a8780-704b-11ea-838f-07ab72d1a6c3.png)

The hardware key option doesn't show up.
The pin doesn't work (this is the OS pin not the key pin)
Using a different account does work

If i chose pin i get this error

![image](https://user-images.githubusercontent.com/11369180/77809152-b1703380-704b-11ea-85e5-d2617f90aa40.png)

I am at a loss what the issue is.
The smart card shows up because my key is smartcard capable but not provisioned.

(note if i logon to windows10 client with AAD username and password that works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d45db5-5172-45cb-2c4d-d73a9e15d699
* Version Independent ID: fa08e81d-3307-514e-129a-843e812e97a9
* Content: [Hybrid Windows Hello for Business key trust Provisioning (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment] 2020-03-28 09:16
@scyto . I dont azure id.  Your azure admin might enabled some restrictions to use only valid CA based smart card. or admin might denied access to your username.

Let wait for few days  expert azure users will give solutions

**Comment by scyto** [comment] 2020-03-29 21:55
Thanks @RAJU2529  i am my admin :-)

This ultimately came down to this:

- the CRL path on the DC cert (installed locally on win10 machine was right)
- this referenced a HTTP accessible CRL like http://myserver/path/mycaname.crl
-the  CRL like http://myserver/path/mycaname.crl had its own CRL attribue pointing to this referenced a HTTP accessible CRL like http://myserver/path/mycaname+.cr
- this file no longer existed, it had right file extension of .crl no cr
- this came about because I fat fingered the CA extension for the CRL CDPS, i corrected that and it worked for all other certs, however it was not corrected in the CRL attibute on the CRL itseld.
- republishing the CRLs didn't seem to fix this
- in the end i renewd the CA cert and then republished the CRLs and this fixed the incorrect CRL path attribute on the CRL
- this would appear to be a server 2019 CA bug!

Doc writers can you make sure in all the cert guidance for WHfB that you tell people to make sure any path in the CRL attribute field on the CRL list itself is correct.  This took me 2 days of work and doing wire-shark network traces to figure out!

Also consider condensing this article into a symptoms / fix flow chart or trouble shooting doc - it was right about what my issue was for these symptoms!

https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-mailbag-windows-hello-for-business/ba-p/445349

**Comment by e0i** [comment] 2020-05-06 15:23
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-05-06 15:23 UTC
Labels: hello-for-business
