### ISSUE TITLE
Collect logs remotely from Windows 10 PCs: Title misleading

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/windows-itpro-docs#3519] opened 2019-05-06 10:59 UTC
The title "Collect logs remotely from Windows 10 PCs" is misleading imho. I would expect the possiblity to upload the logs to the intune portal but as far as I can read, we can enable Admin and Debug logging remotely. In order to access the output though, we still need to connect to the event viewer of the machine, correct? or enable the export of the outcome to a file? ("Example: Export the Debug logs") - which the user should then email ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738225b2-66a4-e0dd-47fb-faf333ed52d1
* Version Independent ID: d9d3274c-3ee7-ed3a-6cd8-6b387027562c
* Content: [Diagnose MDM failures in Windows 10](https://docs.microsoft.com/en-gb/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10#collect-logs-remotely-from-windows-10-pcs)
* Content Source: [windows/client-management/mdm/diagnose-mdm-failures-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment] 2019-05-08 19:02
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-08 21:02
@kennethvs Thank you for providing feedback.

The issue is under investigation and you will be notified with updates along the way.

Thanks.

**Comment by e0i** [comment] 2019-05-27 18:50
Please ignore the accidental reference above.

**Comment by VLG17** [comment] 2019-07-23 12:12
@kennethvs What the title states actually works with the help of the [DiagnosticLog CSP](https://docs.microsoft.com/en-gb/windows/client-management/mdm/diagnosticlog-csp), which is used for generating **and collecting diagnostic information from the device**: Event Tracing for Windows (ETW) log files and current MDM configured state of the device.

Although not a Microsoft article, you can find more information regarding the actual remote collection of logs here: https://oliverkieselbach.com/2019/04/23/on-demand-windows-diagnostic-logs-via-intune/ (the article is 3 months old, so keep in mind that some things will not look/be the same)

**Comment by e0i** [comment] 2019-07-30 14:55
Hello @kennethvs  ,

We are closing this issue since your question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment] 2019-07-30 14:56
@officedocsbot close

**Closed by e0i** 2019-07-30 14:56 UTC
