### ISSUE TITLE
Domain/ComputerName -2016281112 (Remediation failed)

### ISSUE THREAD

**Issue by xonaecom** [MicrosoftDocs/windows-itpro-docs#1753] opened 2018-10-04 14:44 UTC
After applying this MDM policy to change the workstations name, the process is completed successfully (checked and the machine name is changed), but I get the "-2016281112 (Remediation failed)" error.

Using Windows 10 1803 and Windows 10 1809.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309bae29-c769-5051-6c3f-aebeb455cd34
* Version Independent ID: bbdfad82-025e-8aee-b3fc-bcfb8b110674
* Content: [Accounts CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/accounts-csp)
* Content Source: [windows/client-management/mdm/accounts-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/accounts-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by dzejzipl** [comment] 2018-10-14 19:27
Yep, i have this same issue. I'm using this to create new user account, set password and add to local admin groups.

**Comment by Heidilohr** [comment] 2018-10-16 17:54
@xonaecom and @dzejzipl Please show me the logs from **Settings** > **Accounts** > **Work or school account** > **Export your management logs** and the syncml you sent to the device. I can use that information to set up a bug report for the dev team so they can address this issue as soon as possible.

**Comment by Heidilohr** [comment] 2018-10-16 23:12
@xonaecom @dzejzipl I'm currently consulting the team regarding how best to address this, as this is the first time this issue has come up. I will let you know when they reply.

**Comment by xonaecom** [comment] 2018-10-17 08:42
Hello @Heidilohr ,
Because both tickets were merged, I'm gonna put both settings in here.
How can I share with you the exported logs? The logs have client info that I don't want to put here in the wild. :)

**Computer Name change settings:**
**OMA-URI used:** ./Device/Vendor/MSFT/Accounts/Domain/ComputerName
**Data Type:** String
**Value:** OS-%SERIAL%

**User as admin settings:**
**OMA-URI used:** ./Device/Vendor/MSFT/Accounts/Users/<UserAccount>/Password
**Data Type:** String
**Value:** <Password>
**OMA-URI used:** ./Device/Vendor/MSFT/Accounts/Users/ITSD/LocalUserGroup
**Data Type:** Integer
**Value:** 2

Thank you.

**Comment by Heidilohr** [comment] 2018-10-17 16:17
Hi @xonaecom,

Please refrain from sending any log information for now. The team is still figuring out how to solve your problem. It may have something to do with Intune, but I will let you know once I get more information.

Thanks,
Heidi

**Comment by aavdberg** [comment] 2018-10-31 08:10
Have the same problem with the username en password.

**Comment by kufang** [comment] 2018-11-02 05:45
@Heidilohr I have a case where a customer reports this issue. Have you received any information from dev? How should we explain this issue to the customer? Thank you.

**Comment by Heidilohr** [comment] 2018-11-02 16:07
@kufang I'm still waiting to hear back from the dev team, but I'll be sure to let you know when they do.

**Comment by SureshVijayaraghavan** [comment] 2018-11-16 18:09
Hi All, Do you have any update on this above thread. We are trying to configure the same in our environment and getting the same error code. It is causing Non-Compliant in the intune console for the devices. Please let me know is there anything to solve the problem.

**Comment by kufang** [comment] 2018-12-10 06:40
I am sharing some updates from @Rob Lane, who discussed it with PG about the issue. The error here is due to the status check mechanism that is implemented within. In general, when Intune tries to determine if the policy takes effect on the target device, it calls Get Operation of the interested OMA-URI, which basically queries the registry key value from the client. And then compare the result with the policy value. 

The problem is that this CSP only supports Add Operation, which means the Get Operation will always fail because it has not been implemented. That's why we get the error even if it successfully applied.

Even if we have the Get Operation implemented, we still need extra care for those Macros used since a simple strcmp would not be smart enough to identify if the results are expected. But that will be the dev's problem to solve.

**Comment by Jakub-Urban** [comment] 2019-03-05 21:36
Hi, I have similar issue - setting the local user account password sets the flag for "change password on next logon".

**Comment by dbdmora** [comment] 2019-04-19 13:07
Any update on getting this fixed?

**Comment by Jakub-Urban** [comment] 2019-04-19 13:32
I solved this by using script, since Microsoft did not corrected this. Mail me if someone want the script.

**Comment by bertrsh** [comment] 2019-05-01 15:22
Can you please post your script here? Very interested. Also interested in forcing the "change password on next logon" flag. Is there a CSP to set this option?

**Comment by dbdmora** [comment] 2019-05-01 16:56
> I solved this by using script, since Microsoft did not corrected this. Mail me if someone want the script.

I could no find your email on your profile.  Can you paste the script here?  Do you execute the script via powershell or intune32 app?  Thanks

**Comment by Jakub-Urban** [comment] 2019-05-10 08:20
cmd.exe /c 'net user | find /i "LocalAdmin" || Net user LocalAdmin StrongPasswordHere  /add /fullname:"LocalAdmin"'

cmd.exe /c 'net user | find /i "LocalAdmin" | Net user LocalAdmin StrongPasswordHere'

cmd.exe /c 'net localgroup administrators | find /i "LocalAdmin" || net localgroup Administrators LocalAdmin /add'

cmd.exe /c 'WMIC USERACCOUNT WHERE Name="LocalAdmin" SET PasswordExpires=FALSE'

**Comment by Jakub-Urban** [comment] 2019-05-10 08:22
> cmd.exe /c 'net user | find /i "LocalAdmin" || Net user LocalAdmin StrongPasswordHere /add /fullname:"LocalAdmin"'
> 
> cmd.exe /c 'net user | find /i "LocalAdmin" | Net user LocalAdmin StrongPasswordHere'
> 
> cmd.exe /c 'net localgroup administrators | find /i "LocalAdmin" || net localgroup Administrators LocalAdmin /add'
> 
> cmd.exe /c 'WMIC USERACCOUNT WHERE Name="LocalAdmin" SET PasswordExpires=FALSE'

The script checks whether the account does exist so the error code is not reported wrongly. There are possibly more ways how to achieve this but for me, this worked. 

Save it as a powershell script and run as a script within the Intune.

**Comment by LeThijs** [comment] 2019-05-16 09:48
> > cmd.exe /c 'net user | find /i "LocalAdmin" || Net user LocalAdmin StrongPasswordHere /add /fullname:"LocalAdmin"'
> > cmd.exe /c 'net user | find /i "LocalAdmin" | Net user LocalAdmin StrongPasswordHere'
> > cmd.exe /c 'net localgroup administrators | find /i "LocalAdmin" || net localgroup Administrators LocalAdmin /add'
> > cmd.exe /c 'WMIC USERACCOUNT WHERE Name="LocalAdmin" SET PasswordExpires=FALSE'
> 
> The script checks whether the account does exist so the error code is not reported wrongly. There are possibly more ways how to achieve this but for me, this worked.
> 
> Save it as a powershell script and run as a script within the Intune.

Beware with this approach, the password is logged in plaintext (https://oliverkieselbach.com/2018/02/12/part-2-deep-dive-microsoft-intune-management-extension-powershell-scripts/#sensitive-data)

I would not use a script for this

Is there any update for this problem? Getting this error on all my devices

**Comment by hkusulja** [comment] 2019-05-24 09:27
Have same error on multiple tenants/intune , on multiple windows 1803, 1809 , 1903 ...
it works (new users is deployed and added to local admin group), but the error in portal is visible as -2016281112 (Remediation failed)

**Comment by jvsam** [comment] 2019-06-06 23:55
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-06-16 22:56
Hi @xonaecom @dzejzipl @aavdberg @SureshVijayaraghavan @dbdmora @LeThijs @hkusulja @bertrsh we appreciate your patience and thank you for bringing this to our attention. Thanks for sharing updates @kufang and for your workaround @Jakub-Urban.

Although we would love to help resolve this issue, however, this Github site is intended for product documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Hence, if there is anything in this documentation that you think should edited or new (*and relevant*) information that needs to be added, please let us know or you can also suggest changes via pull requests.

What we would recommend, if you are still experiencing the problem, is to utilize the proper channel by contacting support and opening a [service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get this issue resolved ASAP. Thank you!

**NOTE**: Please keep us posted here on the resolution for it may be something we can incorporate to the docs.

**Comment by hkusulja** [comment] 2019-06-17 06:51
@jvsam - please understand, that Microsoft support through service ticket is sometimes very slow etc.
Please update documentation what this number means about error so we can troubleshoot further and resolve issue by our self, since you are also documenting error codes, and this error code is unclear.

**Comment by xonaecom** [comment] 2019-06-17 10:00
@jvsam I have to agree with @hkusulja. I already opened a ticket because of this problem using Premier, and the support has no idea what the problem is and how to respond to this. So your solution is not a solution.

**Comment by jvsam** [comment] 2019-06-23 02:10
Hi @hkusulja and @xonaecom, we do understand that this *Github site* is also another *way/means* of informing the community about this issue and in case someone is aware of a resolution, we hope it can be shared here. Although without the information coming from the right team, we will not be able to determine if this documentation needs to be updated or not. If yes, with *what*. But we do appreciate your patience on this matter.

Hello @lomayor, how are you? I hope you can help us with this issue. Can you please let us know if there has been any information from the Dev team related to the *2016281112 (Remediation failed)* error since this has been reported? Thank you and we look forward to your feedback.

**Comment by hkusulja** [comment] 2019-06-24 08:02
@jvsam there is a docs site with listed codes and what it means and how to troubleshoot further. (currently i am unable to find it), but this code was missing there. It would be great to provide information about details on error so we can proceed troubleshooting further. Also MS Support does not know how to proceed since lack of information...

**Comment by jvsam** [comment] 2019-07-07 08:01
Hi @xonaecom and @hkusulja I'm wondering if you had a chance to look at the [Troubleshooting Windows 10 Intune Policy Failures](https://blogs.technet.microsoft.com/configmgrdogs/2018/08/09/troubleshooting-windows-10-intune-policy-failures/) blog article? 

**Excerpts:**

> One of our customers recently reached out with an issue where a policy for Windows 10 wasn’t applying correctly, and we were returning a very unhelpful error message “-2016281112 Remediation failed”.

>Unfortunately, the Remediation failed error message is all that is returned by the client when we issue the SET command on the OMA-URI’s required to configure the target setting. We’re partnering with Windows to improve this experience, so watch this space. But for now, we have to settle for what we have.

@lomayor just following up. Do you have any update regarding the status of this issue and if it's something that can be called out in the docs? Tagging you here as well @ManikaDhiman, hoping you have information about this since you are updating the contents of CSPs? Thank you so much.

**Comment by ManikaDhiman** [comment] 2019-07-08 22:59
Hi @jvsam, thanks for tagging me here. I will get in touch with the product team to see if we should include the details about "-2016281112 (Remediation failed)" error message in Accounts CSP doc. Thanks!

**Comment by jvsam** [comment] 2019-07-09 12:43
Thank you so much @ManikaDhiman. We appreciate your help.

**Comment by jvsam** [comment] 2019-07-27 07:07
Hi @ManikaDhiman, just want to ask if you got the confirmation. Will the doc be updated? Thank you again.

**Comment by ManikaDhiman** [comment] 2019-07-30 08:26
Hi @jvsam, I am awaiting confirmation. I will update the status as soon as I hear from them. Thanks!

**Comment by ManikaDhiman** [comment] 2019-08-01 03:47
Hi @jvsam, Product team suggested not to add any note in the CSP doc for this error as it is specific to Intune, other MDM ISVs may have different results. Hope this helps. Thanks!

**Comment by hkusulja** [comment] 2019-08-01 05:02
@ManikaDhiman then specify this error and details about it into Intune documentation...

**Comment by jvsam** [comment] 2019-08-04 07:45
Thank you for the update @ManikaDhiman. We appreciate all your effort.

@hkusulja there are different topic owners/authors. And with this new feedback system at docs.microsoft.com, it is easier to create an issue on the actual content page and provide feedback for better issue management. Please use the submit feedback option on the documentation where you think your suggestion is best applied since as per the Dev team and the author, this is not the right topic for that. 

Also, there's already an existing Intune doc that lists all the common [error codes and descriptions in Microsoft Intune](https://docs.microsoft.com/intune/troubleshoot-company-resource-access-problems). Although, please note that as per the author, the doc only lists the codes, and for troubleshooting, you can utilize the [TechNet user forum](https://social.technet.microsoft.com/Forums/home?forum=microsoftintuneprod) or contact the dedicated [Intune Support](https://docs.microsoft.com/intune/get-support). You can also check the [Intune Tech Community](https://techcommunity.microsoft.com/t5/Intune-Customer-Success/bg-p/IntuneCustomerSuccess) where you can ask questions and interact with other users, experts and also Microsoft engineers. Also looking into the different posts, *it appears* that the *Remediation Failed* error may vary based on different scenarios. So even the explanation from @kufang may not be a *catch-all* answer. But again, it is worth suggesting on the **correct doc**. 

> ...The error here is due to the status check mechanism that is implemented within. In general, when Intune tries to determine if the policy takes effect on the target device, it calls Get Operation of the interested OMA-URI, which basically queries the registry key value from the client. And then compare the result with the policy value.
> The problem is that this CSP only supports Add Operation, which means the Get Operation will always fail because it has not been implemented. That's why we get the error even if it successfully applied.
> Even if we have the Get Operation implemented, we still need extra care for those Macros used since a simple strcmp would not be smart enough to identify if the results are expected. But that will be the dev's problem to solve.

I believe we can consider this as resolved and no changes to doc as of this time. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-08-04 07:45
@officedocsbot close

**Closed by jvsam** 2019-08-04 07:45 UTC
Labels: assigned-to-author, client management, mdm

**Comment by hkusulja** [comment] 2019-08-04 19:14
Ref: https://github.com/MicrosoftDocs/IntuneDocs/issues/2773
