### ISSUE TITLE
Diagnostic data viewer shows no data

### ISSUE THREAD

**Issue by mcp111** [MicrosoftDocs/windows-itpro-docs#1687] opened 2018-09-26 11:09 UTC
[Enter feedback here]
Even when diagnostic data has been enabled for several months, why is the diagnostic data viewer showing nothing???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54254070-539b-6cf2-f988-c80ad685c5fa
* Version Independent ID: 5bbe5140-eee5-abc3-1a26-1c0d13eab358
* Content: [Diagnostic Data Viewer Overview (Windows 10)](https://docs.microsoft.com/en-in/windows/privacy/diagnostic-data-viewer-overview)
* Content Source: [windows/privacy/diagnostic-data-viewer-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/diagnostic-data-viewer-overview.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by DaniHalfin** [comment] 2018-09-26 18:07
Hi @mcp111 , thanks for reaching out. This sounds like a problem with DDV. Please use feedback hub (Win+F) when you have DDV open to report the issue. 
Thanks.

**Comment by jvsam** [comment] 2019-06-07 00:08
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment] 2019-06-23 15:36
@mcp111. I reproduced this issues on windows 10  v1803 pro and windows 10 v1903 ent. At last i conformed, diagnostics data viewer works fine. I can be able to see data's. 
From my testing, i will confirm no issues.

To get to solve your issues, please do the following 

You must enable the following privacy settings.
01. under diagnostic data, select  full or enhanced 
02. view diagnostic data viewer should be enabled
03. under feedback frequency, select automatic

You must  enable the following services
01. allow telemetry and data collection
02. enable windows  log reporting service and set as automatic 
03. enable windows   event collector service and  set as automatic 
04. enable windows  event  log service and set as automatic

**Comment by jvsam** [comment] 2019-07-28 15:17
Thanks you so much for sharing that information @RAJU2529. Just to clarify, you were able to reproduce the issue on 1803 and 1903 and also found a fix, right? It appears like a privacy or setting issue, at least based on your testing. 

Hi @mcp111 hoping all is well. I know it's been a while since this issue was opened so thank you for your patience. I just wanted to follow up if you were able to resolve it? If you are still having problems, I would also recommend that you [contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-07-28 15:18
@officedocsbot close

**Closed by jvsam** 2019-07-28 15:18 UTC
Labels: assigned-to-author, privacy
