### ISSUE TITLE
0x80070520 doesn't seem to be listed.

### ISSUE THREAD

**Issue by mgrizenko** [MicrosoftDocs/windows-itpro-docs#1634] opened 2018-09-13 20:44 UTC
User keeps getting this even though they have a pin configured.

**Comment by shortpatti** [comment] 2018-10-24 22:50
@mgrizenko, thanks for the feedback.  Can you provide me a link to the topic where this error should be listed?

**Comment by Nacimota** [comment] 2019-01-24 12:56
After a bit of searching, I suspect (though I can't know for sure) that this issue refers to the following page:

* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)

It's probably also related to (or a duplicate of) #1801, which also concerns the above page.

**Comment by illfated** [comment] 2019-01-24 20:08
Good point. I wonder, though, why this issue wasn't closed with the same reasoning as https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1801#issuecomment-454187068 .
Maybe because the issue wasn't created from a comment on the doc page, but directly here on Github.

**Comment by e0i** [comment] 2019-03-05 20:04
@mgrizenko Thank you for your feedback. From our understanding this issue has already been resolved (see: #1801)

@illfated Thank you a dozen for your contribution across the repository :)

@AndreaBarr This issue has had already been resolved and can be closed. Thanks.

**Closed** 2019-03-05 22:06 UTC
