### ISSUE TITLE
Wrong/Contradicting info in the document about Microsoft Defender Scan options

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-itpro-docs#11790] opened 2023-11-01 09:34 UTC
# Description of the problem

In this part of the document: https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#allowscanningnetworkfiles

<br>

<img width="496" alt="image" src="https://github.com/MicrosoftDocs/windows-itpro-docs/assets/118815227/386baedc-8a57-46bc-b118-ab1cdde5de86">

<br>

<br>

The description of the Network Files Scanning is:

This policy setting allows you to configure real-time scanning for files that are accessed over the network. It is recommended to enable this setting.

- If you enable this setting or do not configure this setting, network files will be scanned.
- If you disable this setting, network files will not be scanned.

<br>

Meanwhile, The group policy description of the same policy in Windows 11 latest version is this:

<br>

<img width="515" alt="image" src="https://github.com/MicrosoftDocs/windows-itpro-docs/assets/118815227/a591944a-9777-4791-8267-99da076838fe">

<br>

<br>

This policy setting allows you to configure scanning for network files. It is recommended that you do not enable this setting.

- If you enable this setting, network files will be scanned.

- If you disable or do not configure this setting, network files will not be scanned.

<br>

# Contradictions

* As you can see, the document indicates that the setting is enable by default but the Group policy in Windows indicates that the setting is disabled by default.

* Moreover, the document mentions that it's recommended to enable the setting, but the Group policy does not recommend doing so.

<br>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Defender Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#allowfullscanonmappednetworkdrives)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment] 2023-11-01 19:22
Closing as duplicate of #11313 - see comments there for more info.

Also since then we've published this article with more information: [Contributing to the CSP reference articles](https://learn.microsoft.com/en-us/windows/client-management/mdm/contribute-csp-reference)

**Comment by HotCakeX** [comment] 2023-11-01 19:35
> Closing as duplicate of #11313 - see comments there for more info.
> 
> Also since then we've published this article with more information: [Contributing to the CSP reference articles](https://learn.microsoft.com/en-us/windows/client-management/mdm/contribute-csp-reference)

I read your comment in there, but the problem is that the Group Policy description is correct, it's only the doc that is not up to date.

So It's not a group policy problem that I can file a feedback for in the feedback hub. You can see that in the screenshot I uploaded above.

**Comment by aczechowski** [comment] 2023-11-01 20:41
Oh I see, my apologies.
@vinaypamnani-msft the current description for AllowScanningNetworkFiles is in the editable section because the source is manual forced. Perhaps revisit whether the string was fixed in the latest ADMX? Or just fix the editable string. 😄

**Comment by vinaypamnani-msft** [comment] 2023-11-01 21:30
@HotCakeX @aczechowski I had a discussion with the Defender PG earlier this year about this policy, and it is enabled by default, and it is recommended to enable this policy. Some more info on this policy here: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-advanced-scan-types-microsoft-defender-antivirus?view=o365-worldwide#settings-and-locations

I overwrote the automation to manually provide the description for this policy. The GPO description needs to be updated, so I suggest submitting feedback via the Windows Feedback app.

**Closed** 2023-11-01 21:55 UTC
Labels: mdm

**Comment by HotCakeX** [comment] 2023-11-01 22:05
Thanks for checking, I submitted a feedback for it
https://aka.ms/AAnbl52
