### ISSUE TITLE
Dead Link under Related Topics

### ISSUE THREAD

**Issue by mwolzak** [MicrosoftDocs/windows-itpro-docs#10735] opened 2022-07-28 12:58 UTC
[Enter feedback here]

The second link to the technet gallery under "Related Topics" is a dead link and redirects to the gallery main page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment] 2022-07-28 14:38
Duplicate of #10726

**Closed** 2022-07-28 14:38 UTC
Labels: threat-protection, doc-bug
