### ISSUE TITLE
msert (32-bit) error issue

### ISSUE THREAD

**Issue by hyung-seop** [MicrosoftDocs/windows-itpro-docs#5331] opened 2019-11-01 08:38 UTC
Hello,

There's an error message of running msert(32-bit), i looked through the msert.log following your direction, it was 0x4 something and says 'The signanutre was not signed'. 
Could you help with this?

Thank you in advance.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft 안전 검사 프로그램 다운로드](https://docs.microsoft.com/ko-kr/windows/security/threat-protection/intelligence/safety-scanner-download#feedback)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by jvsam** [comment] 2019-11-02 01:46
@officedocsbot assign @jvsam

**Comment by illfated** [comment] 2019-11-02 02:45
From a computer support agent viewpoint (myself), I would need more information to be able to even start to answer your question. A verbatim copy of the log file (`%SYSTEMROOT%\debug\msert.log`) would be a start. I would also recommend that you read the page https://support.microsoft.com/kb/2520970 (**How to troubleshoot an error when you run the Microsoft Safety Scanner**).

Regarding your mention of an error code starting with `0x4` (not listed in the support page for the tool), I would need to see the log file content (in English) to have any remote chance of estimating what the issue could be caused by. On the other hand, I presume it would be more productive to get help from a local Microsoft Support department (Seoul, Korea?) to find out what the root cause of your issue is.

**Comment by illfated** [comment] 2019-11-02 02:49
Also: regarding your comment about the error message saying something like "The signature was not signed", just as a guess on my part, it looks like it could possibly be related to either a device driver or other software package not being supported because it has not been digitally signed by Microsoft. (This is just a guess, I have no evidence to back it up.)

**Comment by jvsam** [comment] 2019-11-03 22:41
Thank you for sharing that information @illfated 👍! Just to add @hyung-seop, please note that the Microsoft Safety Scanner signatures will expire ten days after downloading. You will need to download a new version of the tool to get the latest malware definitions. Downloading the Microsoft Safety Scanner again is also one of the troubleshooting steps, so that's what I will recommend. 

You can also try to run File Signature Verification (SigVerif) tool to see what files are not digitally signed (Use *SigVerif* command on command prompt or try *SigVerif* in search). Of course, contacting [Windows 10 Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) is still your best option.

**Comment by illfated** [comment] 2019-11-03 22:44
@jvsam : Thank you for your reply & follow-up. I had completely forgotten about the Microsoft Safety Scanner signatures.

**Comment by RAJU2529** [comment] 2019-11-04 07:38
Yesterday I scanned with msert64.exe, but I Don't got any above issue.

**Comment by illfated** [comment] 2019-11-04 10:27
It is possible that some 32-bit systems behave differently from 64-bit systems, even if, in theory, they should be the same.

**Comment by hyung-seop** [comment] 2019-11-06 15:14
Thank you for all giving kind support and replys, first of all. 
But, Unfortunately, i just tried re-installing following you guy's solutions above all, but it still keeps showing me same error message with it.
I've worked on with our companie's other computers(32-bits) and my colleagues are having same problem like me. (It was okay in the past few months)

In detail, 
0x8050A005 | The signatures are not signed. | Download the Microsoft Safety Scanner again.

@jvsam Would you mind if i wonder how to use 'Sigverif' tool to make it right about 'signing' in detail?

here are captured pics of this symptom for your deeply understanding.

![KakaoTalk_20191106_234807281](https://user-images.githubusercontent.com/57239653/68308425-33d57680-00f0-11ea-8793-b95f82fbc208.jpg)
![KakaoTalk_20191106_234808984](https://user-images.githubusercontent.com/57239653/68308433-36d06700-00f0-11ea-8ad0-620328325b50.jpg)

I'm cautiously curious about the actual program is messed with any lately 'updating' of it, please look into it's history one more time.

**Comment by RAJU2529** [comment] 2019-11-06 15:51
@hyung-seop.  sigverif.exe verifies the .exe and .dll files under the system32 and syswow64 folders. 
copy the msert.exe file to system32 folder.
go to cmd run as administrator
type  sigverif
press enter
click start

**Comment by jvsam** [comment] 2019-11-13 08:32
> Would you mind if i wonder how to use 'Sigverif' tool to make it right about 'signing' in detail?

I haven't tried @RAJU2529's suggestion since it's built into Windows. Have you tried it? I don't have a 32 bit version to verify.

![image](https://user-images.githubusercontent.com/18371314/68746029-ac798d00-0632-11ea-824b-6013173c89c7.png)

![image](https://user-images.githubusercontent.com/18371314/68746127-e185df80-0632-11ea-9c1d-c8a757fa4dd7.png)

Is that the information that you are looking for @hyung-seop?

**Comment by jvsam** [comment] 2019-12-08 18:20
Hi again @hyung-seop, we hope you were able to resolve your concern. We will now close this issue, but if you have feedback or suggestions to help improve the quality of the technical documentation of Microsoft Docs, please let us know by using the feedback feature. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-12-08 18:20
@officedocsbot close

**Closed by jvsam** 2019-12-08 18:20 UTC
