### ISSUE TITLE
Do SSUs and LCUs really still "ship separately"?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#10899] opened 2022-09-28 10:57 UTC
"Servicing stack updates must ship separately from the cumulative updates because they modify the component that installs Windows updates."

Is that true in view of:

[https://techcommunity.microsoft.com/t5/windows-it-pro-blog/deploy-windows-ssus-and-lcus-together-with-one-cumulative-update/ba-p/1967887](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/deploy-windows-ssus-and-lcus-together-with-one-cumulative-update/ba-p/1967887)

?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by RAJU2529** [comment] 2022-10-17 12:50
@BR77BE , From windows 11, SSU is embedded in CL  updates, when you extract the .msu file , you will get SSU file separately.

**Comment by BR77BE** [comment] 2022-10-18 12:38
My comment/question was about the accuracy of the statement in this document that SSU must SHIP SEPARATELY from CU.

The link I provided (about Windows 10+, not just 11) says they DO NOT ship separately.

Please delete the inaccurate statement in this document "... must ship separately ..." and provide proper guidance in the next paragraph.

P.S. What's a CL update?

**Comment by RAJU2529** [comment] 2022-10-18 12:42
@BR77BE . CL means cumulative updates in the form of .msu

**Comment by aczechowski** [comment] 2023-01-12 00:00
This is a dupe of #10582 which was fixed by #10985
Closing

**Closed by aczechowski** 2023-01-12 00:00 UTC
Labels: product-question, writer-input-required
