### ISSUE TITLE
FileExplorerNamespaceRestrictions 

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#1866] opened 2018-10-15 17:32 UTC
Is this supported in InTune \ CSP or only via provision xml currently? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#fileexplorernamespacerestrictions)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment] 2018-10-15 17:58
@Niglb The first part of the topic explains how to configure it in Intune: https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#configure-a-kiosk-in-microsoft-intune

**Comment by Niglb** [comment] 2018-10-15 18:20
Sure - just looking for the FileExplorerNamespaceRestrictions "Downloads" option - I could configure with a custom xml via intune. I assume FileExplorerNamespaceRestrictions will come to the portal interface.

**Comment by fdebout** [comment] 2018-10-23 02:44
I've just tested it using CSP custom config : ./Device/Vendor/MSFT/AssignedAccess/Configuration and it does work, I can now access it from my Kiosk apps, however I cannot browse to it from File Explorer as it is hidden/disable in the Kiosk configuration. Is there a way to turn file explorer back on/provision start menu link for it?

**Comment by jdeckerms** [comment] 2018-10-23 12:53
@fdebout The FileExplorerNamespaceRestrictions setting only allows access to the Downloads folder from a file dialog box. Did you try adding File Explorer as one of the kiosk apps? Although I'm not clear why you'd want to -- a user can do a lot from File Explorer, it might defeat the purpose of locking the device down as a kiosk.

**Comment by Niglb** [comment] 2018-10-23 19:14
My client has an ask to allow USB drives in a kiosk - I'm testing various policies but cannot do this yet. Downloads may do the trick. Is this only available via XML or could we use the WMI bridge to hit the CSP?

**Comment by micheltenhove** [comment] 2018-10-23 21:08
Does the Downloads folder clear itself after a while or is this a manual action to perform?

**Comment by fdebout** [comment] 2018-10-23 22:51
@jdeckerms Yes I have a File Explorer app link in my start menu but it doesn't work, nothing happens when you select it. In our scenario Kiosk users often need to lookup brochures and specs for the products they sell on the suppliers websites and email or share it with their customers. 
So far in my testing I can download the files to the downloads folder, and then as you mentioned, browse to it with a file dialog box in OWA for example.  It's fine with Office documents as you can save them to OneDrive but for pdf docs there's no easy other way to re-open the downloaded file.

**Comment by jdeckerms** [comment] 2018-10-25 14:30
@Niglb I don't have a date when to expect the setting to be in Intune, but they do plan to add it.

**Comment by Niglb** [comment] 2018-10-25 14:38
Ok thank you -  even as a standalone CSP we can hit outside the main assigned access XML. 

My client would love to see USB drives too.

**Comment by seanyen-msft** [comment] 2019-03-09 00:54
> So far in my testing I can download the files to the downloads folder, and then as you mentioned, browse to it with a file dialog box in OWA for example. It's fine with Office documents as you can save them to OneDrive but for pdf docs there's no easy other way to re-open the downloaded file.

@fdebout Hi, can you elaborate more the use case in details steps? That would help understand the pain points.

**Comment by fdebout** [comment] 2019-03-11 23:11
@seanyen Hi, We are using a multi app kiosk profile on new PoS devices.
In this use case the staff using the PoS device occasionally has to download product brochures/tech specs from supplier's website (mostly pdf documents).
They can email this from Outlook web access as an attachment, opening a dialog box and browsing to the download location.
They cannot however access the document directly from explorer once it has been downloaded.
Typically what we would like is a shortcut on the start menu or task bar opening the download folder to make access to downloaded documents easier.
Florian

**Comment by seanyen** [comment] 2019-03-12 07:16
@fdebout Would it be useful to pin a shortcut (`.lnk` file) to Downloads folder in [StartLayout](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#startlayout) in multi-app kiosk profile?

**Comment by RescueWhale** [comment] 2019-03-12 15:51
> @Niglb I don't have a date when to expect the setting to be in Intune, but they do plan to add it.

Hi,

Have your team given any update on this? Or is it possible to add it via OMA URI reference in the interim?

Many thanks

**Comment by fdebout** [comment] 2019-03-13 00:07
@seanyen I did try to add a shortcut to the download folder in the start menu but nothing happens when you click on the link.
I believe Explorer is blocked by default in the Kiosk AssignedAccess config. I also tried adding explorer to the authorised applications list which did not help either.

**Comment by Spefx** [comment] 2019-03-19 05:25
This is a huge pain point for me aswell.

Have many use cases where File Explorer is required on a kiosk be it for media playback or as a printing station.

FileExplorerNamespaceRestrictions seems to be the way to go but this is limited due to the fact it cannot be accessed directly by File Explorer

**Comment by micheltenhove** [comment] 2019-03-20 13:44
@Spefx @fdebout , I've been able to make this work. I've added a Shortcut of the downloads folder that links to the Kiosk account, after that I've added the shortcut to start menu. Note that I managed to get this working on a Kiosk machine that automatically logs in.

**Comment by jtorres3** [comment] 2019-03-20 21:15
Has anybody ever done with a shared computer,  version 1809?  I have the built in kiosk profile with a standard exported start layout .xml applied.  I then created another profile with custom uri ./Device/Vendor/MSFT/AssignedAccess/Configuration applied.  I also had a default filenamespace restriction .xml.  When I apply both at the same time I get a device conflict.  

Can anybody possibly share their custom .xml for filenamespace ?  I have the kiosk working as I want minus the saving to the downloads folder that I desperately need.  

Any help would be appreciated.  Thanks

**Comment by jtorres3** [comment] 2019-03-20 21:16
I forgot to mention I used this url successfully for just a normal kiosk.  
https://www.robinhobo.com/how-to-configure-windows-10-in-multi-app-kiosk-mode-with-microsoft-intune/

**Comment by jvsam** [comment] 2019-06-06 23:34
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-06-09 23:53
Hi @jdeckerms, based on the ongoing discussion, will there be any updates to the documentation that will address issues raised here? Thank you.

**Comment by Spefx** [comment] 2019-06-10 00:11
This Issue has been for a few different things over its life-cycle. 

Originally it was raised to determine if the "FileExplorerNamespaceRestrictions" could be controlled inside a intune device configuration profile - The answer at the time was no however the "Allow access to Downloads folder" can now be configured directly inside of a intune profile. 

![image](https://user-images.githubusercontent.com/15935255/59166010-e364e780-8b56-11e9-8fcb-221f31442d1a.png)

The question then morphed into the use of File Explorer when a machine was in kiosk mode - specificly accessing the now enabled Downloads folder/USB Drives. i can confirm that the downloads folder can be accessed through File Explorer by adding "Explorer.exe" to a list of allowed apps and pinning a file explorer shortcut to the kiosk start menu. The question about USB/DVD Drives is still outstanding, i currently have an open Premier support call investigating USB/DVD Drives and will update this issue with any findings.

**Comment by jvsam** [comment] 2019-06-12 02:10
That's great to hear @Spefx and we definitely need to update the documentation. Thank you for clarifying this for us.

@Niglb, I will get this issue over to the Windows writing team for review. We want users to have the best Windows experience by ensuring the contents of the Microsoft Docs are accurate and up-to-date. Thanks.

**Comment by NigelbrownIBM** [comment] 2019-06-19 16:52
@jvsam Perfect! I found love to be able to leverage FileExplorerNamespaceRestrictions for locations beyond Downloads - currently my client is asking for USB drive access while in Kiosk mode.

**Comment by TokyoScarab** [comment] 2019-06-24 18:59
@Spefx Touching base and seeing if you had any new information on that support call you mentioned?  I will be updating the information to add what's been discussed so far in here and would love to be able to add the USB/DVD information if possible.  Thanks!

**Comment by Spefx** [comment] 2019-06-24 23:04
@NigelbrownIBM @TokyoScarab  

Almost have enough to write a blog post about the tweaks i have needed to make to draw out the more complex kiosk requirements, Shame i dont have a blog. For the "External Media Access" issue Premier support was able to get it working, the "Workaround" revolved around changing some of the registry keys set when applying AssignedAccess. 

Assigned Access sets the following registry keys, these need to be reversed or removed:
1) `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer` “NoRun”=dword:00000001” 
2) `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\AllowedNavigation` "AllowedStorageLocations" =dword:00000000
3) `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\AllowedEnumeration` "AllowedStorageLocations" =dword:00000000

The following are caveats of this solution:
- Changing the above three registry keys will also open up the entire C:\ Drive, in my instance this was not desirable and as such i applied the following key to remove C:\ Drive access:
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer`
"NoDrives"="dword:00000004"
- Need to acknowledge that allowing External Media increases the attack surface of the kiosks and should only be enabled on systems where there is a specific requirement.
- The "NoRun" key will come back - i enforced the registry keys through a Group Policy targeting the specific systems that needed External Media access
- Hopefully in the future this workaround gets tied up in a nice little bow with a provisioning package/intune flag to allow External Media.

Thanks
Spefx

**Comment by Niglb** [comment] 2019-06-25 04:03
@spefx this is fantastic - I had a call open as well but they didn't get me a work around. Any good methods to enforce these in an Intune only environment ? I can deploy a PowerShell script to set, but enforce my be a trick.

**Comment by TokyoScarab** [comment] 2019-06-25 19:53
@Spefx That's really cool.  I might not add those steps and wait for Microsoft to include a more streamlined way of adding USB / DVD support.

**Comment by Niglb** [comment] 2019-06-27 01:34
Haven't been able to get this work around to function - my devices are cloud only intune managed self deploying kiosk devices.

**Comment by Spefx** [comment] 2019-06-27 01:37
@TokyoScarab Agree, not really ready for Microsoft Docs as it is quite nuanced solution. Please note that my Premier Support call did not indicate if a more streamline solution was in scope to be developed.

**Comment by Spefx** [comment] 2019-06-27 01:45
> Haven't been able to get this work around to function - my devices are cloud only intune managed self deploying kiosk devices.

Intune should not really have a huge impact, happy to troubleshoot further but this is not likely to be the best format.

**Comment by Niglb** [comment] 2019-06-27 01:49
Thank you - more being able to apply these reg keys without group policy.

**Comment by jvsam** [comment] 2019-06-28 21:57
Hi @Spefx and @Niglb, just an update in case you haven't seen it, @TokyoScarab's [suggested content update](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4250/files) in the *FileExplorerNamespaceRestrictions* (_Microsoft Intune_) section is already deployed on the site. Although a lot of issues were discussed on this thread, do you have other suggestions for improvement related to this documentation before I close it?

**Comment by jvsam** [comment] 2019-07-01 04:30
Hi @Spefx and @Niglb, I believe we can consider this issue *resolved*, at least based on what we can support (*related to how we can improve this documentation*). For now we will close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-07-01 04:31
@officedocsbot close

**Closed by jvsam** 2019-07-01 04:31 UTC
Labels: assigned-to-author, configuration

**Comment by Niglb** [comment] 2019-07-03 17:57
@Spefx my email is niglbrown@gmail.com - I would love to get this working.

**Comment by Niglb** [comment] 2019-07-08 22:40
> > Haven't been able to get this work around to function - my devices are cloud only intune managed self deploying kiosk devices.
> 
> @Niglb Intune should not really have a huge impact, happy to troubleshoot further but this is not likely to be the best format.

I've attempted setting logon scripts, scheduled tasks, nothing has stuck...

**Comment by NigelbrownIBM** [comment] 2019-07-25 15:02
Looks like Preview Builds now have this capability via XML! https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml#preview-folder-access-sample-xml
