### ISSUE TITLE
TPM2.0 + Windows Server 2019 v1809

### ISSUE THREAD

**Issue by mikegan** [MicrosoftDocs/windows-itpro-docs#8144] opened 2020-08-26 02:15 UTC
Hi all,
I see a situation that I can't select "change owner passoword" in **tpm.msc**. There is no this option.
After install WS2016 , the option is exist.
Refer to [https://docs.microsoft.com/zh-tw/windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings](url)
Tried to modify "OSManagedAuthLevel" in **regedit**.  The default velue is "5" . means keep the lockout authorization.
How can I show "change owner passoword" option in "tpm.msc" with TPM2.0??

System boot mode is legacy bios.

**Comment by RAJU2529** [comment] 2020-08-26 03:33
@mikegan , Is your system compatible latest UEFI mode , did you  formated the hdd or ssd as GPT partition type with ntfs mode.

you can not change tpm owner password with tpm.msc normal command.

**Comment by mikegan** [comment] 2020-08-26 03:41
@RAJU2529  , Yes, My System is support UEFI mode. it's a system under test.  Select Legacy mode since the test requirement.
I just wonder that why WS2016 can Change Owner Password, but WS2019. (Use the same System)

**Comment by beerisgood** [comment] 2020-08-26 04:37
tpm.msc is deprecated
Use Defender TPM overview

**Comment by e0i** [comment] 2020-08-26 10:06
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-08-26 10:06 UTC
