### ISSUE TITLE
Script link not working

### ISSUE THREAD

**Issue by markstan** [MicrosoftDocs/windows-itpro-docs#9129] opened 2021-02-11 23:07 UTC
Is there an alternative download site for the script?  Gallery was recently decommissioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment] 2021-02-11 23:11
Working on it. We'll put them on PowerShell Gallery or in a particular GitHub repo for that purpose, as appropriate.

**Comment by RAJU2529** [comment] 2021-02-12 04:49
@jaimeo . I am waiting to see new links .

**Comment by jaimeo** [comment] 2021-02-12 16:24
@RAJU2529 you don't need to worry about it. I'll update the article when we get the scripts set up.

**Comment by illfated** [comment] 2021-02-12 16:30
See also ticket #9129 regarding the same issue.

**Comment by illfated** [comment] 2021-02-21 21:16
Duplicate of #9104

#please-close

**Closed** 2021-02-22 20:17 UTC
Labels: Microsoft submitter, deployment
