### ISSUE TITLE
Documentation is wrong and does not work get this error

### ISSUE THREAD

**Issue by JonBrekhus** [MicrosoftDocs/windows-itpro-docs#2840] opened 2019-03-05 22:44 UTC
Any information would be helpful in solving these errors.

Event ID 7211 - The Secondary Account Primary Refresh Token prerequisite check failed.

Followed by
Event ID 7206 - Windows Hello for Business failed to locate a certificate registration authority.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d45db5-5172-45cb-2c4d-d73a9e15d699
* Version Independent ID: fa08e81d-3307-514e-129a-843e812e97a9
* Content: [Hybrid Windows Hello for Business key trust Provisioning (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by joinimran** [comment] 2019-03-27 08:09
Hello @JonBrekhus , Thank you for your feedback. For Event ID 7211, please refer to the following link (https://social.technet.microsoft.com/Forums/en-US/7625faf1-1641-4293-b629-51a56595a1b1/helloforbusiness-the-secondary-account-primary-refresh-token-prerequisite-check-failed-id-7211?forum=win10itprosecurity)

Also, can you please share details for Event ID 7206 so that we can further help you.

Thanks.

**Comment by mypil** [comment] 2019-04-03 13:03
@JonBrekhus - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment] 2019-04-03 13:05
@JonBrekhus - We would like to follow up on this. Can you please respond to the query of joinimran? 

Thank you.

**Comment by mypil** [comment] 2019-04-05 10:25
@JonBrekhus - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment] 2019-04-05 10:25
@officedocsbot close

**Closed by mypil** 2019-04-05 10:25 UTC

**Comment by EdgeSN** [comment] 2019-04-11 17:45
Hi can we reopen this case ?
I'm having exactly the same issue :)

Event ID 7211 - The Secondary Account Primary Refresh Token prerequisite check failed.

Followed by
Event ID 7206 - Windows Hello for Business failed to locate a certificate registration authority.

**Comment by illfated** [comment] 2019-04-12 03:22
@EdgeSN : did you read the TechNet forum post provided by **joinimran** ?
- https://social.technet.microsoft.com/Forums/en-US/7625faf1-1641-4293-b629-51a56595a1b1/helloforbusiness-the-secondary-account-primary-refresh-token-prerequisite-check-failed-id-7211?forum=win10itprosecurity

Judging by the posts there, it could either be caused by a missing entry for “https://login.windows.net” which needs to be added to the “IE trusted site” list, or it could be a time-out issue, solved by waiting and new retry attempts.

**Comment by IlyaTeplitski** [comment] 2020-04-20 22:22
Same problem. "Login.windows.net" is in IE trusted sites.
