### ISSUE TITLE
Clarity on registry settings for under spec machines

### ISSUE THREAD

**Issue by XEASACJ1** [MicrosoftDocs/windows-itpro-docs#2629] opened 2019-02-06 09:58 UTC
The entries required for the registry for lower number of cores, ram etc isn't clear. 
e.g. Do we add DWORD (32-bit) Value, are the values decimal 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb9445a-681d-24b6-5241-4ebe311f5236
* Version Independent ID: aea60f74-212c-e24e-f164-28a555bc1727
* Content: [Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-gb/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment] 2019-05-09 15:43
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-09 15:43
Hello, @XEASACJ1 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by lindspea** [comment] 2019-05-10 09:55
@XEASACJ1 Thank you for reaching out. It is DWORD value, and it should be the decimal value of the ram, cpu, disk space.

**Comment by e0i** [comment] 2019-05-15 17:19
Hello @XEASACJ1  ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment] 2019-05-15 17:20
@officedocsbot close

**Closed by e0i** 2019-05-15 17:20 UTC
Labels: windows defender application guard
