### ISSUE TITLE
Windows Hello Error 0x80070490

### ISSUE THREAD

**Issue by rcooley77** [MicrosoftDocs/windows-itpro-docs#1747] opened 2018-10-03 19:57 UTC
Error Code: 0x80070490
No idea why this matches the Update Error Code, but... I got it trying to set up my PIN.

**Comment by DaniHalfin** [comment] 2019-01-14 22:36
Hi @rcooley77 , thanks for reaching out. Sorry it took us so long to respond.
While I realize this might be no longer relevant - for error codes unlisted here, in most cases those are transient error codes being surfaced by other services in the Windows Hello dependency chain.
We are working on something to improve the user experience in that regard, but that will not solve the issues you are experiencing.
If we find a reoccurring error codes that isn't covered here and should be (meaning, in most cases, it is coming from Windows Hello and not other components) we'll make sure to add it to this page.
For any issue you're seeing, please either file a problem through Feedback Hub, or reach out through our various support channels. Both avenues allow us to properly investigate the issue in ways we could never do through a comments section on a GitHub issue.
The feedback section in the topic is generally meant for feedback on the content, and we can't really use it for in-depth troubleshooting.
We thank you for taking the time to reach out, but we also want you to have the best time to resolution of the issue, and going through this feedback channel won't get us there.
I'll be closing this issue, but feel free to respond if you feel we missed something. We can always re-open.

**Closed by DaniHalfin** 2019-01-14 22:36 UTC
Labels: assigned-to-author, hello-for-business

**Comment by rcooley77** [comment] 2019-04-24 19:36
Sorry for not getting back to you.
I'm still getting the error. This is on a Windows 10 for Education running 1809.
I'm wondering if this is an Azure-related problem, since these machines do get registered in Azure in our environment. Perhaps it is looking for an Azure piece we don't have set up properly.

**Comment by illfated** [comment] 2019-04-25 04:05
@rcooley77 : Have you tried to contact Microsoft Support in your region to open a ticket with them to get direct help with your specific issue?

**Comment by Anooprayas** [comment] 2019-08-02 08:37
Greetings,
Even I am facing the same issue. Any input to resolve this issue?

**Comment by illfated** [comment] 2019-08-02 18:40
@Anooprayas : if you search the issue pages in this repository (https://github.com/MicrosoftDocs/windows-itpro-docs), you will find some information, although not exactly what the error code means. Here is a list of current issue pages (closed issues) where people have asked about the error code 0x80070490:
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3897
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3317
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2804
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2409
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1748

An example image of the error message can be found here:
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3897#issuecomment-516830270
- https://answers.microsoft.com/en-us/windows/forum/all/we-cant-connect-to-server-to-setup-you-pin-right/a0536687-7db8-4ab4-95e6-be2ff7d97dd7?auth=1 (Microsoft user account login needed)

One of the more common explanations seems to be that **a time-out occurs** (the service takes too long time to respond), either from other background tasks running with higher priority or that it takes too long to get a response from the Windows Hello service connector, especially external online sources. Please read through the issue pages to make up your own mind about what this could be caused by, because it does not necessarily happen the same way to all the users who experience this error message.
