### ISSUE TITLE
中文翻译问题 Chinese Translate Issue

### ISSUE THREAD

**Issue by dzvision** [MicrosoftDocs/windows-itpro-docs#6116] opened 2020-02-25 03:17 UTC
In the "Windows Autopilot 的优势"

The First paragraph mension "IT 专业人员通常会花费大量时间生成和自定义稍后将部署到设备的图像。"

Original text was "Traditionally, IT pros spend a lot of time building and customizing images that will later be deployed to devices. Windows Autopilot introduces a new approach."

So "customizing images" was translated as "自定义... ...图像。"
That is wrong.

The correct way is "自定义... ...镜像。"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 83582e61-22b0-fb99-43c7-65a6694affef
* Version Independent ID: 61cc2546-2074-08b2-a6ed-e73da4825bfd
* Content: [Windows Autopilot 概述](https://docs.microsoft.com/zh-cn/windows/deployment/windows-autopilot/windows-autopilot#feedback)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment] 2020-02-25 18:17
@TinaMcN : I presume this issue needs to be handled by manual translators, seeing that the original text does not contain code text which otherwise could have used MarkDown backticks as encapsulation.

**Comment by TinaMcN** [comment] 2020-02-27 00:54
@dzvision thank you for reporting this issue.  @illfated you are correct, this seems to be an issue caused by machine translation.   I sent it to be human translated and I hope it will be fixed in a few days.

**Comment by illfated** [comment] 2020-03-04 18:08
I am unable to read kanji, but from what I can see, the original text seems to be still unchanged:

## Windows Autopilot 的优势
IT 专业人员通常会花费大量时间生成和自定义稍后将部署到设备的图像。 Windows Autopilot 引入了新方法。
***
Judging by the issue ticket report in comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6116#issue-570282976 , the second to last kanji ( **图** ) in the first sentence (directly before "。 Windows Autopilot ") remains unchanged.

**Comment by TinaMcN** [comment] 2020-03-05 21:43
@illfated thanks for checking, I see what you mean.  I passed on the localization vendor to fix it.

**Comment by TinaMcN** [comment] 2020-03-07 01:56
@dzvision @illfated the issue has now been fixed, please confirm and close.

**Comment by illfated** [comment] 2020-03-07 02:03
Confirmed. The character has been corrected as requested in the opening issue ticket comment.

**Comment by mypil** [comment] 2020-03-07 14:16
@dzvision - Thank you for submitting feedback.

From our understanding, the issue you raised has been resolved so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-03-07 14:16 UTC
Labels: deployment, localization
