### ISSUE TITLE
GCC High specific URLs for Defender ATP API to be added

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/windows-itpro-docs#8310] opened 2020-09-18 23:58 UTC
There are a handful of docs that would benefit from including the GCC High specific URLs for Defender ATP API. 

|Service category|Service name|Azure Public|Azure Government GCC High|Notes|
|-----------|-----------|-------|----------|----------------------|
|Windows Defender ATP|Integration, Response, Entities, and Streaming APIs|api.securitycenter.windows.com|api-gov.securitycenter.microsoft.us||
|Windows Defender ATP|SIEM API|wdatp-alertexporter-**{region}**.windows.com|wdatp-alertexporter-us.securitycenter.us|Public **{region}** options: eu/us/uk|

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/commercial-gov
https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-webapp
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80d72583-7d75-5ff9-89fe-d19b0ed0b1fc
* Version Independent ID: c0b3ce8b-866b-adb9-9e79-3329fc68ad9e
* Content: [Create an app to access Microsoft Defender ATP without a user - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-webapp)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-webapp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-webapp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment] 2020-09-23 13:25
Duplicate of #8311

**Closed by e0i** 2020-09-23 13:25 UTC
