### ISSUE TITLE
Memory Integrity

### ISSUE THREAD

**Issue by KeithQuestion** [MicrosoftDocs/windows-itpro-docs#6626] opened 2020-05-03 13:04 UTC
I keep getting a message "Memory integrity can't be started.  There may be an incompatibility on you device"

How do I correct this?

Regards
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f784502-84dc-1122-eab4-1eeeb08da046
* Version Independent ID: 21f210a7-4c38-8f62-0226-121562617fef
* Content: [Memory integrity - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/memory-integrity#feedback)
* Content Source: [windows/security/threat-protection/device-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/memory-integrity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by resistor420** [comment] 2020-05-03 19:26
what

**Comment by eshutah** [comment] 2020-05-03 22:13
Same problem for me.  Dell XPS 8700, Windows 10 Version 10.0.18363 Build 18363.  I only tried the setting for the first time today.

**Comment by RAJU2529** [comment] 2020-05-04 04:23
@eshutah . @KeithQuestion   There are two ways to set this. One is by group policy and another manually adding registry key.
 Processor must be supported with bios compatible firmware is needed.
I have intel i5 7200u . I enabled memory integrity.

**Comment by alfa-batsi** [comment] 2020-05-07 11:19
I have the same error on Microsoft Surface Laptop 3.

**Comment by RAJU2529** [comment] 2020-05-07 11:25
@alfa-batsi . Did you enabled VBS virtualization-based security before enabling  memory integrity

**Comment by alfa-batsi** [comment] 2020-05-07 11:30
I do not think so. Prior trying to enable memory integrity, I turned on core isolation first. Where do i turn the VBS virtualization from?

**Comment by RAJU2529** [comment] 2020-05-07 11:33
@alfa-batsi type the following in cmd with admin rights and press enetr 

**Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard" /v EnableVirtualizationBasedSecurity /t REG_DWORD /d 1 /f**

**Comment by alfa-batsi** [comment] 2020-05-07 11:40
I did as you suggested, restarted computer, but still get same error

**Comment by RAJU2529** [comment] 2020-05-07 11:42
@alfa-batsi. give me the screenshot , what's the hardware configurations are there in your laptop

**Comment by RAJU2529** [comment] 2020-05-07 11:45
@alfa-batsi 
here is my laptop configuartions 
![Capture1](https://user-images.githubusercontent.com/3296790/81290833-5d169580-9086-11ea-9da9-1bbdf9506d33.JPG)
![Capture2](https://user-images.githubusercontent.com/3296790/81290848-60aa1c80-9086-11ea-9a92-c8a508ccc0a7.JPG)
![Capture3](https://user-images.githubusercontent.com/3296790/81290851-6273e000-9086-11ea-862d-45cde65e5ebf.JPG)

**Comment by alfa-batsi** [comment] 2020-05-07 11:50
![image](https://user-images.githubusercontent.com/1078022/81291150-56822100-907a-11ea-9607-7d29373d4d52.png)

**Comment by alfa-batsi** [comment] 2020-05-07 11:52
![image](https://user-images.githubusercontent.com/1078022/81291401-bc6ea880-907a-11ea-9be0-2d5ad8600f5b.png)

**Comment by RAJU2529** [comment] 2020-05-07 11:53
@alfa-batsi .  memory integrity is already turned on

**Comment by alfa-batsi** [comment] 2020-05-07 11:56
The last screenshot is when i try to turn it on and the error pops up. Then it goes back to off

![image](https://user-images.githubusercontent.com/1078022/81291646-3a32b400-907b-11ea-9097-4779e09a093f.png)

**Comment by RAJU2529** [comment] 2020-05-07 12:00
@alfa-batsi . what about device security page

**Comment by alfa-batsi** [comment] 2020-05-07 12:08
I do not think there is anything usefull there, nut anyway:

![image](https://user-images.githubusercontent.com/1078022/81292620-f80a7200-907c-11ea-8892-5ead04f1d111.png)

**Comment by RAJU2529** [comment] 2020-05-07 12:12
@alfa-batsi , You using windows 10 home, not pro version,  so you cant  configured through group policy editor. 

did you enabled all advanced security features related to INTEL  processor

**Comment by alfa-batsi** [comment] 2020-05-07 12:19
I just looked through bios settings. There is everything enabled related to security

**Comment by alfa-batsi** [comment] 2020-05-07 12:20
may be this feature is not support for win 10 home. I will look through microsoft docs. Thanks for your time.

**Comment by RAJU2529** [comment] 2020-05-07 12:26
@alfa-batsi At last try, i give  device guard registry key, merge it 
[Deviceguard.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/4592891/Deviceguard.zip)

**Comment by alfa-batsi** [comment] 2020-05-07 12:36
I went with "Enable DeviceGuard.reg" file, restarted the computer, but still no luck.

**Comment by RAJU2529** [comment] 2020-05-07 12:39
@alfa-batsi , sorry then no more ideas

**Comment by alfa-batsi** [comment] 2020-05-07 12:40
Thanks a lot.

**Comment by eshutah** [comment] 2020-05-07 16:46
I'm going to file this setting under "Unfinished/Bug riddled" for now.  If you have to edit the registry and/or run the group policy editor in hopes of making it work, Microsoft has more work to do.

**Comment by RAJU2529** [comment] 2020-05-07 16:52
@eshutah . Is your issues is  solved  or not

**Comment by alfa-batsi** [comment] 2020-05-07 16:54
no, did not have time to dig deeper. maybe some time later. i will post update.

**Comment by eshutah** [comment] 2020-05-07 17:08
> @eshutah . Is your issues is solved or not

The issue is not resolved for me.  I'm going to consider the setting unusable for now.  Or, you could argue that it is resolved for me since I have chosen not to pursue the sorts of fixes you are suggesting.  I will probably try it again after the next update.

**Comment by Sadlic** [comment] 2020-05-07 18:39
Hi, I had the same issues with memory integrity and found this thread with same "no result". But I found the following and finally did it:

https://www.tenforums.com/tutorials/104025-turn-off-core-isolation-memory-integrity-windows-10-a.html

1. In my msinfo32 (System Information) the item  "Visualization-based security Services Running" had an empty value. The rest was like it is shown in the picture. => Something is wrong but I went forward

2. I followed top down and got the same result with the "Memory Integrity" switch as before. It turns gray and UAC dialog pops up (but sometimes it doesn't. But never mind). The expected message Restart dialog never came up. And so wasn't the red remark "This change requires you to restart your device."

3. Hoping for the second chance. And as I looked for the reg-value of HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity it was set to 0. After setting it to 1 and restarting ... voila ... Memory Integrity is working and the value of msinfo32 (System Information) item "Visualization-based security Services Running" is set to "Hypervisor enforced Code integrity".


Hope that will help you out of trouble.

Cheers 
Karsten

**Comment by Kaldek** [comment] 2020-05-10 04:43
Sadlic is correct - I had the same issue on a device that was running Memory integrity and I turned it off to check something, then it refused to re-activate.  Editing the registry key solved the issue and forced it back on.

**Comment by RAJU2529** [comment] 2020-05-10 12:00
@Kaldek . I don't have that registry key, but still memory integrity is ON.

**Comment by e0i** [comment] 2020-05-10 20:08
Closing the issue based on @Sadlic's response. Thank you all for the productive discussion.

**Closed by e0i** 2020-05-10 20:08 UTC
Labels: device guard
