### ISSUE TITLE
No hypervisor support for windows running on mac using bootcamp

### ISSUE THREAD

**Issue by arafubeatbox** [MicrosoftDocs/windows-itpro-docs#5312] opened 2019-10-30 05:51 UTC
I am running Windows 10 enterprise version on a mac that does not support safeboot.

When I run the command
"Get-CimInstance –ClassName Win32_DeviceGuard –Namespace root\Microsoft\Windows\DeviceGuard" it shows this:

AvailableSecurityProperties {1,3}
RequiredSecurityProperties 1
SecurityServicesConfigured 2
SecurityServicesRunning 0
VirtualizationBasedSecurityStatus 1

I want to enable hypervisor support, and run HVCI to enable VBS.
Is it possible to do this on a mac Boot Camp?

Eventually, I want to use Hyper-V, and the "systeminfo" command states that the hardware meets all the conditions for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4b8d75-5d09-e0d6-1a90-45175fd1043d
* Version Independent ID: dfb10d10-a514-6ea5-1307-df865db530db
* Content: [Enable virtualization-based protection of code integrity](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity#feedback)
* Content Source: [windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment] 2019-10-31 15:24
@arafubeatbox. Sir here are the requirements of Hyper V in windows 10 OS. See below official website for more information
**https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements**

**https://docs.paloaltonetworks.com/vm-series/9-0/vm-series-deployment/set-up-the-vm-series-firewall-on-hyper-v/system-requirements-on-hyper-v.html**

**Comment by e0i** [comment] 2020-05-08 15:54
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-05-08 15:54 UTC
Labels: device guard
