### ISSUE TITLE
Error Code 0x801C044D listed twice it Error Mitigation Sections

### ISSUE THREAD

**Issue by jrjenk** [MicrosoftDocs/windows-itpro-docs#5455] opened 2019-11-18 19:10 UTC
The Error Code 0x801C044D is listed twice in the mitigation section, not adjacent, and with different explanations.  while I get that there might be multiple causes I think you should group them together to make that more obvious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment] 2019-11-21 22:59
OK, I think there may be a chance that this has happened because the current source code format of that table is still simple HTML instead of MarkDown (MD).

I will make an effort to convert that HTML table to MD, but I might need to ask if the Cause + Mitigation for those 2 entries should be in the same cells, if there should be 1 row or 2 rows for error code 0x801C044D (first column) and if there should be a blank line between the 2 lines if the 2x cause + mitigation should share the same cells.

**Comment by mypil** [comment] 2019-11-22 02:59
@jrjenk - PR #5501 has been created by illfated to fix and close this issue once the PR is merged.

@illfated - Thanks for creating the PR for this issue. 

Thank you and we appreciate your contribution to make the docs better!

**Closed** 2019-12-03 15:03 UTC
