### ISSUE TITLE
Indicators

### ISSUE THREAD

**Issue by rushifaldu** [MicrosoftDocs/windows-itpro-docs#4215] opened 2019-06-22 22:46 UTC
Indicators link is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d6b543-3693-7771-9cd1-b8f57e304310
* Version Independent ID: 5ba25ca7-32ac-2d28-cc69-e6bf53dede66
* Content: [What's new in Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment] 2019-06-23 00:03
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-06-23 14:54
Hi @rushifaldu, thanks for informing us about the broken link. Much appreciated!

Hi @mjcaparas, can you please confirm if this is the new [Indicators](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/ti-indicator) link that falls under Microsoft Defender ATP? Let us know and we can assist in creating a *Pull Request* to correct the wrong link. Thank you so much.

**Comment by RAJU2529** [comment] 2019-06-24 14:01
@Jvsam. I saw new indicator link and i conformed that.New link belongs to windows defender.
 create a pull request and change the new link .
Thanks, sir for information

**Comment by illfated** [comment] 2019-06-24 17:43
Oh. I see. Is this because Windows Defender changed name to Microsoft Defender or ATP ?

**Comment by mjcaparas** [comment] 2019-06-24 18:01
Yes. Confirmed. Old link points to windows-defender-atp folder. Changing that to https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/ti-indicator should fix it.

**Comment by jvsam** [comment] 2019-06-29 08:13
@officedocsbot reopen

**Comment by jvsam** [comment] 2019-06-29 08:14
Hi @mjcaparas apologies but I am re-opening this issue since there is no PR yet to change the wrong link. Appreciate the confirmation, I'll coordinate with the Windows writing team to submit a PR. Thank you. 

FYI @rushifaldu

**Comment by jvsam** [comment] 2019-07-07 02:11
Hi again @rushifaldu, the suggested update to this documentation via this [Pull Request (PR)](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4334) has been approved and merged. It will be displayed at docs.microsoft.com in the next scheduled publishing run. You can verify the changes at this URL: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp. We will now close this issue but we'll provide an update here to inform you when the changes are live.

Thank you for your feedback to help improve the contents of this document and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-07-07 02:11
@officedocsbot close

**Closed by jvsam** 2019-07-07 02:11 UTC

**Comment by jvsam** [comment] 2019-07-24 23:41
Hi @rushifaldu a quick update. The changes are now displayed here at docs.microsoft.com and you can verify by visiting this URL: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp. Thank you again.
