### ISSUE TITLE
Chromium Edge

### ISSUE THREAD

**Issue by marcos-nuga** [MicrosoftDocs/windows-itpro-docs#6061] opened 2020-02-15 11:29 UTC
Hi all,

After updating to version 80, Chromium Edge, the Kiosk doesn't run.

What can I do?

Marc

**Comment by RAJU2529** [comment] 2020-02-17 17:11
try to uninstall previous version,  download and install version  80.0.361.54

**Comment by e0i** [comment] 2020-05-07 18:09
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-05-07 18:09 UTC
Labels: kiosk
