### ISSUE TITLE
Missing description of the Publisher level for german version of  the page (de-de)

### ISSUE THREAD

**Issue by Denis1983** [MicrosoftDocs/windows-itpro-docs#9668] opened 2021-06-09 14:25 UTC
Understand Windows Defender Application Control (WDAC) policy rules and file rules

Missing description of the Publisher level for german version of  the page (de-de)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 74ef7917-edec-5597-4689-1ffbf6735918
* Version Independent ID: 41f7ceb2-ad16-812c-3766-b9a9a72a42c1
* Content: [Verstehen Windows Defender (Application Control, WDAC)-Richtlinienregeln und Dateiregeln (Windows 10) - Windows security](https://docs.microsoft.com/de-de/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment] 2022-08-04 15:45
Since Tina handled this about a year ago, I trust the problem is resolved, so closing this issue.

**Closed by aczechowski** 2022-08-04 15:45 UTC
Labels: application control, localization, writer-input-required, doc-enhancement
