### ISSUE TITLE
Broken windows update script links

### ISSUE THREAD

**Issue by nickandre10x** [MicrosoftDocs/windows-itpro-docs#9281] opened 2021-03-09 22:05 UTC
Your two links to `Reset Windows Update Client settings` script and `Reset Windows Update Agent` script are both broken nor are the resources readily searchable. Would be nice to have those.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment] 2021-03-10 02:14
@nickandre10x . This issue is already esculated by other user and Microsoft team is working on new host location. so please close this issue.

**Comment by illfated** [comment] 2021-03-10 21:21
Duplicate of issues #4930, #9104, #9216, #9237, and #9287 .

**Closed** 2021-03-15 17:41 UTC
Labels: deployment

**Comment by ste7677** [comment] 2021-03-17 12:05
This is CRITICAL - Please provide the scripts SOMEWHERE!

All our Windows 2016 servers broken due to windows update errors. Active directory and exchange server down.

**Comment by jaimeo** [comment] 2021-03-17 16:35
@ste7677 the SMEs I've been working with will be contacting you to investigate your issue.

**Comment by ritz301** [comment] 2021-03-18 19:25
We would need WU logs to investigate the issues your machines are facing. I would recommend filing logs via feedback hub under _Install and Update > Downloading, installing, and configuring Windows Update_.
