### ISSUE TITLE
Step 7 contains a command line with items that are out of sequence

### ISSUE THREAD

**Issue by zszabo2000** [MicrosoftDocs/windows-itpro-docs#3193] opened 2019-04-07 18:24 UTC
"netsh reset winsock" returns an error, while "netsh winsock reset" works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources#feedback)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment] 2019-04-07 18:31
Duplicate of issue ticket #3157 (**[Step 7](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3157)**)

**Comment by mypil** [comment] 2019-04-10 17:07
@officedocsbot assign @mypil

**Closed** 2019-04-19 23:43 UTC

**Comment by illfated** [comment] 2019-04-20 00:24
@zszabo2000 : As you can see, the Pull Request #3194 has been merged and the Github page is updated. It may take a few days before the change migrates to the docs.microsoft.com page, but you can consider your feedback responded to and followed up by the Microsoft Docs team.
