### ISSUE TITLE
legacy Dictionary Attack Prevention Parameters setting for TPM 2.0?

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/windows-itpro-docs#5164] opened 2019-10-11 15:51 UTC
What are these legacy values? I see where the new default values are specified (and can be modified by GPO) but I don't see what the legacy values are. I started seeing issues with the new default values and want to compare to the legacy values (or use the legacy values). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d46fce78-6956-1b3a-124f-e8188d0412cd
* Version Independent ID: 5891df2d-6432-c5b4-0eff-49b520f59067
* Content: [TPM Group Policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings#configure-the-system-to-use-legacy-dictionary-attack-prevention-parameters-setting-for-tpm-20)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment] 2019-10-11 20:57
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-10-20 22:14
Hi @rasldasl, thank you for your question. To clarify, are you asking about the **legacy Dictionary Attack Prevention Parameters**—values that were used for Windows 10 Version 1607 and below⁠—that are configured when the GPO setting "*Configure the system to use legacy Dictionary Attack Prevention Parameters setting for TPM 2.0*" is enabled? If so, we believe it would be better if you contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance. There are also other support resources that are available for you like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community. **Kindly keep us informed if you find any relevant information** that can be incorporated into this documentation. This GitHub-based feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. We are always looking forward to suggestions and ideas to make the docs better for users.

Hi @DulceMontemayor do you have any insights regarding the *actual* legacy values used for Windows 10 Version 1607 and below? Is there any information available? Hoping you can help, thank you.

**Comment by jvsam** [comment] 2019-10-31 23:54
Hi again @rasldasl, how are you? Were you able to contact support or check with the community about this? It would be great if you can share the feedback. Thank you.

Hi @DulceMontemayor if time permits, can you please review this issue and provide some insights regarding the question? Looking forward to your feedback. Thank you.

**Comment by jvsam** [comment] 2019-10-31 23:54
@officedocsbot assign @DulceMontemayor

**Comment by rasldasl** [comment] 2019-11-01 00:44
I found I had a firmware issue with a specific model so it was not this change that was the problem. As a result I did not investigate the parameters any further.

Sent from my iPhone

On Oct 31, 2019, at 6:54 PM, Jo <notifications@github.com> wrote:

﻿

Hi again @rasldasl<https://github.com/rasldasl>, how are you? Were you able to contact support or check with the community about this? It would be great if you can share the feedback. Thank you.

Hi @DulceMontemayor<https://github.com/DulceMontemayor> if time permits, can you please review this issue and provide some insights regarding the question? Looking forward to your feedback. Thank you.

**Comment by jvsam** [comment] 2019-11-10 22:43
Thanks for the update @rasldasl, happy to know you've identified the cause of the problem. 

We will now close this issue, but please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation through the doc's *feedback feature*.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-11-10 22:43
@officedocsbot close

**Closed by jvsam** 2019-11-10 22:43 UTC
