### ISSUE TITLE
Isn't the guidance to enable complexity requirement as "Best Practice" contrary to current recommendations?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/windows-itpro-docs#6040] opened 2020-02-12 13:56 UTC
I am surprised to see that this article still recommends enabling the complexity requirement as a best practice.  I thought Microsoft's stance on that changed several years ago, as evidenced by the 2016 whitepaper on password guidance?  
https://www.microsoft.com/en-us/research/publication/password-guidance/

Is this article out of date?  If not, perhaps it could elaborate on why it is still recommended to enable complexity and how that fits in with the other guidance from MS? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment] 2020-02-13 15:56
@NeighborGeek 

The issue is being passed to an independent contributor for investigation.

Thank you for the question.

**Comment by VLG17** [comment] 2020-03-23 16:27
@NeighborGeek thank you for providing this feedback. Although the article tells us to "_Set Passwords must meet complexity requirements to Enabled_" it also warns us that this is not failproof "_This makes a brute force attack difficult, but still not impossible_."

Nevertheless i understand your point and think you are correct. Is it ok if i add a Note at the top of the "Best Practices" section pointing to the Microsoft Password Guidance for the latest Best Practices? I would like to keep what's already in the article, in order to be able to do a comparison between the two. Do you agree?

**Comment by NeighborGeek** [comment] 2020-03-23 16:43
That sounds reasonable to me.

**Comment by e0i** [comment] 2020-03-31 08:35
Closing via #6311. Thank you.

**Closed by e0i** 2020-03-31 08:35 UTC
Labels: policy settings, threat-protection
