### ISSUE TITLE
Documentation missing info for older environments that have been upgraded

### ISSUE THREAD

**Issue by bhstang65** [MicrosoftDocs/windows-itpro-docs#3084] opened 2019-03-28 13:35 UTC
I was enabling Hello for Business at my work and reached a point where I was stuck.  Every command in the guide worked without error, however I was unable to sign in using Hello.  Any error I received on the Client wasn't helpful to find a resolution.  After troubleshooting I realized I wasn't receiving the msDS-KeyCredentialLink on my user account.  I searched for this issue directly and found resolution by opening my AD Connect console and choosing to Refresh Schema.  I feel you should add this to your instructions to help others like myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02eda72c-ccd2-e8d8-4f7e-6edf95b79408
* Version Independent ID: be08aee5-2403-c131-0f39-005e1271d5f1
* Content: [Hybrid Windows Hello for Business Prerequistes (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment] 2019-03-29 12:22
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-03-29 12:23
@bhstang65 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment] 2019-04-02 10:50
Dear @bhstang65 , if I understand you correctly, you connected to Azure AD, then upgrade your environment then had this problem?
Or I missing something?
Thank you

**Comment by mypil** [comment] 2019-04-15 15:08
@bhstang65 - We would like to follow up on this issue. Can you please respond to the query of MaratMussabekov?

Thank you.

**Comment by bhstang65** [comment] 2019-04-15 18:35
I added a 2016 Domain Controller to my environment and then connected to Azure AD.  It appears you have to manually sync the Schema in AD Connect so it knows about the new features of a 2016 Domain Controller.  The Hello documentation didn't mention this that I was able to find.

**Comment by MaratMussabekov** [comment] 2019-04-16 11:09
Dear @bhstang65 ,
in scenario: 
1. connected to Azure AD
2. Windows Server 2016 domain controller added.
there is a need to manually sync Azure AD connect, for sure.

in scenario you described:
1. Windows Server 2016 domain controller added
2. connected to Azure AD
there is no need to re-sync Azure AD (usually). I think in this case the need to re-synchronize is caused by something else, not by adding of WS2016. Are you sure there wasn't any other schema change in on-premises deployment?

Thank you

**Comment by bhstang65** [comment] 2019-04-16 16:55
Maybe I'm not understanding what is meant by connected to Azure AD.  We have been running AD Connect for several years now.  If running AD Connect is connected to Azure AD, then scenario 1 firmly describes us.  I was thinking one of the powershell commands I ran during the integration might have been the connection to Azure AD.  I didn't see any mention of syncing the AD Connect schema in the Hello for Business instructions and that is why I opened the issue.  Syncing Azure AD connect schema resolved my problem, so all is well from that perspective.  I was just looking for a way to get that step added to the documentation for other people.

**Comment by MaratMussabekov** [comment] 2019-04-18 12:21
Dear @bhstang65 ,
that's a good point, I have created a PR to add this info to the article.
Thank you!

**Comment by bhstang65** [comment] 2019-04-18 14:27
Thank you for looking into it!

**Comment by bhstang65** [comment] 2019-04-18 14:32
Looks like the perfect place for it!  I have a question about the wording though.  It didn't appear to me that the schema was refreshed upon synchronization.  I think AD Connect synchronizes every 30 minutes, however I fought with my issue for days after the local schema change happened (adding server 2016 DC).  I had to manually sync the schema with AD Connect because it wasn't doing it on its own.  Should it be updating the schema when a synchronization occurs?

**Comment by illfated** [comment] 2019-04-18 20:57
When looking at the text added in the PR (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3294/files#diff-d435e15b9217a90c6387a8e03d98dd77R74), it looks like there could be a need for the word "manually" in the sentence, maybe just before the link. Then again, when I read the linked page [**Refresh directory schema**](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-installation-wizard#refresh-directory-schema)  , it seems to be a manual action per definition. Thoughts?

**Comment by MaratMussabekov** [comment] 2019-04-19 04:02
Dear @bhstang65 , 
**Should it be updating the schema when a synchronization occurs?** - I think it doesn't synchronize all the changes. That will explain why Microsoft added this feature to refresh the schema. Anyways, it is a good practice to run Azure AD Connect installation wizard again after any major change to the schema.

Dear @illfated ,
**it looks like there could be a need for the word "manually" in the sentence, maybe just before the link** - not sure about that. I never saw the term "Manually refresh directory schema", this action is usually called "refresh directory schema", so I think it could be confusing. What do you think?

Thank you

**Comment by illfated** [comment] 2019-04-19 06:19
I am completely OK with the current content. I guess I should have asked @bhstang65 directly if it needs any more clarification to be precise enough.

**Comment by bhstang65** [comment] 2019-04-19 13:28
From and endusers perspective, the current wording sounds like given time the Schema would have updated on its own.  I would change the last part to something like this  

"In case the schema of your local AD DS was changed since installing AD Connect or running the Azure AD Connect installation wizard, you may need to [refresh directory schema](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-installation-wizard#refresh-directory-schema)."

Or just say In case the schema of your local AD DS has changed, refresh directory schema.

Can I just say I love the new Microsoft!  That you are given end users a voice is rare and refreshing in the tech industry!  It feels like community!

**Comment by illfated** [comment] 2019-04-19 13:38
Very well, it looks like the PR  **update hello-hybrid-cert-trust-prereqs.md** #3294 has got your suggestion covered.

**Comment by mypil** [comment] 2019-04-23 12:26
@bhstang65 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-04-25 15:14
@officedocsbot close

**Closed by mypil** 2019-04-25 15:14 UTC
