### ISSUE TITLE
Local Webpage

### ISSUE THREAD

**Issue by markedtiger** [MicrosoftDocs/windows-itpro-docs#1763] opened 2018-10-05 14:34 UTC
I'm trying to use Kiosk Browser to view internally hosted webpage but only get the message that it can't be found; this is the same if I try to load a html file that's saved to the same machine. Do I need to change some settings to be able to view them or is this something Kiosk Browser doesn't support?

**Comment by jdeckerms** [comment] 2018-10-05 14:51
@markedtiger This issue has been reported to the engineering team.

When you receive the Windows 10, version 1809 update, you'll be able to use Edge in a kiosk configuration.

**Comment by ppejovic** [comment] 2018-12-19 00:13
@jdeckerms is it possible to get an overview of the root cause of this issue in Kiosk Browser please? We're seeing varying behavior for our intranet sites, some load successfully and others report "Hmm, we can't reach this page". If possible I'd like to determine why some sites work and others don't. Thanks.

**Comment by JasonSCarter** [comment] 2019-02-04 13:49
I also would like to report this issue.  Still not fixed in build of 1809.  17763.292

**Comment by jdeckerms** [comment] 2019-03-08 16:50
@JasonSCarter Are you using Edge for kiosk?

**Comment by JasonSCarter** [comment] 2019-03-08 16:51
@jdeckerms no.  Kiosk Browser from Windows Store.  (It's built on Edge I believe).  I have a Premier case open on the issue.

**Comment by jdeckerms** [comment] 2019-03-08 17:14
@ppejovic I don't have any new information for the documentation at this time, sorry. @JasonSCarter I'm sure Premier support will help you work out your issue.

**Comment by JasonSCarter** [comment] 2019-03-08 18:40
@jdeckerms been a few weeks, case is still open.  Last I heard it was a networking issue and case was routed to networking team.  Haven't gotten an update since then.

**Comment by illfated** [comment] 2019-03-09 15:14
@JasonSCarter / @ppejovic / @markedtiger : Have you found any of the documentation in https://docs.microsoft.com/ (https://github.com/MicrosoftDocs/windows-itpro-docs) directly related to this and if it needs to be updated or corrected as part of this issue you and the others have got with the Kiosk Browser problems? (Just asking because this site is primarily about improving the documentation pages.)

**Comment by jvsam** [comment] 2019-06-06 23:52
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-06-16 22:05
Hi @JasonSCarter did you get any update on the case you've opened? If it has been resolved and the resolution needs to reflect on any or specific docs available at https://docs.microsoft.com/, please let us know. This Github site is intended for product documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation.  Looking forward to hearing from you!

**Comment by JasonSCarter** [comment] 2019-06-17 12:27
@jvsam Eventually they came back with a "this is by design", which resulted in them updating the following page with a simple note that the Kiosk browser cannot access intranet websites:  https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app

They stated the app is missing the Network Isolation capability which would allow intranet websites, and upon me requesting, the developers refused to add this capability.

**Comment by illfated** [comment] 2019-06-17 20:11
Well, OK, I see. Thank you at least for getting back to us with the updated information.

I can only add that from an outsider's perspective, it appears logical that a kiosk browser might only be set up for internet use, not intranet access -- presuming that an intranet connected computer would be set up as a normal computer with a standard Windows interface and proper security software & user access control.

(This is only my opinion, possibly completely opposite of what others would expect in this scenario.)

**Comment by jvsam** [comment] 2019-06-23 03:03
Hi @JasonSCarter I know the escalation result may have been frustrating for you. The good thing is, you've raised it. May I suggest submitting this as well to the Product team? This is what [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) is all about. Other users may have similar concerns or "key ask* related to *Kiosk Browser's support for intranet websites*. It may not be supported for now due to valid technical reasons, but perhaps in the future it will.

Anyhow, since this documentation is still considered accurate and *up-to-date*, we will now close this issue. However, feel free to re-open if you have suggestions to improve the quality of this documentation and we will submit them for review. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-06-23 03:03
@officedocsbot close

**Closed by jvsam** 2019-06-23 03:03 UTC
Labels: assigned-to-author, configuration
