### ISSUE TITLE
Reset Windows Update Client settings script link broke

### ISSUE THREAD

**Issue by MooreSys** [MicrosoftDocs/windows-itpro-docs#9237] opened 2021-03-02 23:22 UTC
Reset Windows Update Client settings script link broke.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment] 2021-03-02 23:47
We are aware of the issue and are working on a replacement.

**Comment by illfated** [comment] 2021-03-10 21:22
Duplicate of issues #4930, #9104, #9216, #9281, and #9287 .

**Comment by e0i** [comment] 2021-03-23 15:56
Fixed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/15e9a411fce64546f8572b29691f782b3f4badb1#diff-fc5cd38a44f9cd55d877749fbddbe9dabdf373fbf2348b20aba9581b44062630

**Closed by e0i** 2021-03-23 15:56 UTC
Labels: deployment
