### ISSUE TITLE
FAQ - WDAG windows 10 - Registry keys

### ISSUE THREAD

**Issue by acepace** [MicrosoftDocs/windows-itpro-docs#2378] opened 2018-12-24 21:31 UTC
The registry keys should be properly labeled as REG_DWORD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8927df09-e9aa-8c40-290d-0ca7d86ec4e2
* Version Independent ID: ca67bcfc-6120-d6ca-290b-1a7822494c73
* Content: [Frequently asked questions - Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment] 2019-04-15 22:21
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-04-15 22:21
Hello, @acepace 

We are closing this issue as it seems like a duplicate of #2373, which has been resolved.

Feel free to re-open this issue if it is not the case.

Thank you for providing feedback.

**Comment by e0i** [comment] 2019-04-15 22:22
@officedocsbot close

**Closed by e0i** 2019-04-15 22:22 UTC
Labels: windows defender application guard
