### ISSUE TITLE
List of URL's to pass through the SSL Inspection

### ISSUE THREAD

**Issue by mmaraa** [MicrosoftDocs/windows-itpro-docs#5421] opened 2019-11-13 07:12 UTC
I noticed in our very restricted customer environment where all traffic is SSL Inspected that connection does not work with URL's in this network. The connection troubleshooter have endpoints.txt -file which includes several URL's where the troubleshooter tries to connect to. Our customer internet connection is routed out in the Northern Europe area, so connections should go towards https://winatp-gw-weu.microsoft.com/. 

While inspecting the firewall traffic, we can see that the connection is run towards SevilleCloudGateway-WEU-PRD.trafficmanager.net that isn't listed here in the documentation. However, both URL's are pointing to the same IP-address (currently 13.81.218.185) but the firewall is allowing URL's on its name what it was requested. If Defender client calls service to URL: sevilleclodugateway-weu-prd.trafficmanager.net it appears to the firewall with that URL (at least in Checkpoint firewall) and does the SSL Inspection to all other URL's even if the target is same in the network point of view. 

Can this document to be updated with all URL's that clients are requesting exactly to, to avoid this kind of scenarios. And yes. This is very challenging in highly restricted networks with L7 filters in firewalls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Configure machine proxy and Internet connection settings](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment] 2019-11-13 12:13
this question is complicated. Keep calm windows experts users will give answers

**Comment by e0i** [comment] 2020-07-07 16:01
@mmaraa

Can you confirm that the call does not originate from a third-party app, rather than Defender ATP? 

The list of URLs mentioned within the documentation all belong to `windows.net` domain, and it is counterintuitive that Defender would make calls to `.trafficmanager.net` domain.

**Comment by mmaraa** [comment] 2020-07-11 19:04
For 100% I **can not** confirm that the request was originated from Defender client. The customer has really strict firewall rules and disabling SSL Inspection for that particular URL solved issues in Defender ATP client registration and data flow towards the service. I cannot imagine that anything else could solve this thing except our change in SSL Inspection. There wasn't made other changes to the network configurations during the issue was open on customer site.

This was about 9 moths ago (when this issue #5421 was opened), so can't even confirm if it is still valid or not. Later on all other of my implementations have been SSL Inspection _free_ networks.

**Comment by e0i** [comment] 2020-07-13 14:34
Thank you for taking the time to follow-up with a detailed response. Since the case cannot be confirmed, it is to my understanding that the mentioned domain does not belong to the documentation and the issue is being marked as closed.

Please feel free to re-open the case if you think that there is a misunderstanding. Thanks again, and stay safe.

**Closed by e0i** 2020-07-13 14:34 UTC
Labels: in progress, microsoft defender atp
