### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1940] opened 2018-10-24 20:22 UTC
Hello, Unable to deploy these policies, as Data types, and examples are not provided. 

One CSP says Value type is chr. 

There is no Data value recognized by O.M.A., or Cloud Intune, or SCCM that is CHR. 

The reference CHR for either False, or True.. wouldn't that be Boolean?

Can someone please update this CSP with correct deployment settings PER CSP component policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0c33a6-9251-9737-3f75-04be41fe9716
* Version Independent ID: e9806355-0616-cff1-e527-95d7c13ae06e
* Content: [WiFi CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/wifi-csp)
* Content Source: [windows/client-management/mdm/wifi-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/wifi-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Tdiwestyguy** [comment] 2018-10-24 20:35
Comparing this CSP to others, it does not seem to follow the same "Template" of information being published externally by Microsoft. 

Example:  
All other CSP lists the supported Scopes at the top of the CSP sheet. (this does not)
This Scope is required to format the OMAURI path to CSP via MDM provider. 


Profile- This does not outline how to deploy, and what the syntax is. At one point it says "Get is supported operation, but then lists other supported operations? which is confusing. 

WiFiCost - shouldn't this say Integer Data Value along with references?

DisableInternetConnectivityChecks, WlanXML, ProxyPacUrl, 
When reviewing Data type CHR as listed in this WIFI CSP, comparing to OMA website, https://docs.microsoft.com/en-us/windows/client-management/mdm/oma-dm-protocol-support,  Data type CHR is not found, can someone please confirm use?

**Comment by illfated** [comment] 2018-10-24 20:46
BTW. the warning on top of that page has a typo, `express` instead of 'expressed'
(not sure if that pink paragraph element is specific to the page or not).
Maybe I do have an OCD for reading correct grammar, typos distract me a lot.

**Comment by Tdiwestyguy** [comment] 2019-01-17 21:21
Hi, I could use a hand with my request for clarification on this CSP.

**Comment by Heidilohr** [comment] 2019-01-18 00:35
@Tdiwestyguy I'm getting in touch with the dev team responsible for the policy right now.

**Comment by Tdiwestyguy** [comment] 2019-03-04 19:32
I still need help, have not received a response to my questions.  

@HeidiLohr can someone help me with this?

**Comment by jonmannn** [comment] 2019-03-27 20:28
According to my MDM provider, there is an open internal Microsoft ticket regarding this as this policy will continuously fail if the SSID of the network you are trying to scope contains spaces.

Ticket number: MSFT: 117011015155069

**Comment by jvsam** [comment] 2019-06-06 23:24
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-06-09 19:45
Hi @Tdiwestyguy, did you get it to work? If the internal Microsoft ticket mentioned by @jonmannn *(I am sorry but I can't confirm the status)* is what's causing the issue, then we may need to wait for the resolution. If it's not related and the issue is not about the content of this article, I recommend opening a service ticket in your tenant so you can get your issue resolved ASAP. Please follow this link to contact support for Windows 10: https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

Please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are accurate and up-to-date.

**Comment by illfated** [comment] 2019-06-09 20:22
@Tdiwestyguy (Alex) : I wonder if the page needs to be reviewed to see if some of the content needs to be updated.
I noticed some updates related to this type of information on one of the other pages earlier this year:
https://docs.microsoft.com/en-us/surface-hub/manage-settings-with-mdm-for-surface-hub#generate-oma-uris-for-settings

I noticed in particular this section:

> The data type is also stated in the CSP documentation. The most common data types are:
>
> - char (String)
> - int (Integer)
> - bool (Boolean)

I do not have access to a test scenario or a similar scenario to yours, so we need input from someone who can actually check and verify what is needed in the article to make it useful as proper documentation for this topic.

**Comment by jvsam** [comment] 2019-06-09 20:57
Thanks @illfated. I will get this issue over to the Windows writing team for review and further investigation. If the team finds discrepancies, we can request for the content to be updated. 

@Tdiwestyguy, additional information from you—especially if you were able to resolve your issue—will definitely help! We want to make sure the docs are always accurate and up-to-date.

**Comment by jvsam** [comment] 2019-07-01 08:03
Hi @ManikaDhiman, I hope all is well. Will you be able to confirm if this document is up-to-date already or update is still ongoing? Please see the issues raised by @Tdiwestyguy as well and if they can be addressed. Thank you very much.,

**Comment by ManikaDhiman** [comment] 2019-07-01 19:32
Hi @jvsam, for "DisableInternetConnectivityChecks" policy, a note has been added stating the policy is deprecated since Windows 10, version 1607.

For WiFiCost, the description states that the value type is integer and provides the supported values. Product team is tracking a bug to include WiFiCost policy in the DDF.

All the doc bugs related to WiFi CSP article have been fixed. Let me know if there is anything else that needs to be updated.

**Comment by jvsam** [comment] 2019-07-07 06:50
Hi @ManikaDhiman your help is appreciated. Thank you so much. 

@Tdiwestyguy I believe we can consider this issue *resolved*. The documentation has been updated as well—*at least based on the issues the Content team supports*. You can verify the changes at this URL: -https://docs.microsoft.com/windows/client-management/mdm/wifi-csp. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by jvsam** [comment] 2019-07-07 06:51
@officedocsbot close

**Closed by jvsam** 2019-07-07 06:51 UTC
Labels: assigned-to-author, client management, mdm, more info or example needed
