### ISSUE TITLE
whats the difference between "ProvisionedHomePages" and "ConfigureHomeButtonURL"

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1785] opened 2018-10-08 03:48 UTC
i have edited  new  url  https://www.google.co.in/?gws_rd=ssl/  
under the registry 
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\MicrosoftEdge\Internet Settings]
"ProvisionedHomePages"="https://www.google.co.in/?gws_rd=ssl/"
"ConfigureHomeButtonURL"="https://www.google.co.in/?gws_rd=ssl/"

did i configured correctly or not , if wrong means , please tell me the  correct line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aa5c0a6-acd2-4ec3-275d-3a684b3faaf4
* Version Independent ID: 6b475925-ca66-d47f-e180-92988683b37a
* Content: [Group Policy and Mobile Device Management settings for Microsoft Edge (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies)
* Content Source: [browsers/edge/available-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/available-policies.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment] 2018-10-08 13:57
Hi @RAJU2529, let me check with the engineering team to make sure this is correct and may provide more details in the content :)

**Comment by shortpatti** [comment] 2018-10-19 14:28
@RAJU2529, I will reach out to the engineering team.

**Comment by e0i** [comment] 2019-04-18 22:38
@shortpatti Any updates with this issue? We would like to follow-up. Thanks.

**Comment by RAJU2529** [comment] 2019-04-19 11:05
sir I just asked the difference between.

**Comment by illfated** [comment] 2019-04-20 02:35
The difference should be quite simple, at least judging by what I can read from the doc page:

***

[**Configure Start pages**](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies#configure-start-pages)

> By default, Microsoft Edge loads the pages specified in App settings as the default Start pages. With this policy, you can configure one or more Start pages when you enable this policy and enable the Configure Open Microsoft Edge With policy. Once you set the Start pages, either in this policy or Configure Open Microsoft Edge With policy, users cannot make changes.

Group Policy | MDM | Registry | Description
-- | -- | -- | --
Not configured | Blank | Blank | Load the pages specified in App settings as the default Start pages.
Enabled | String | String | Enter the URLs of the pages you want to load as the Start pages, separating each page using angle brackets:    <support.contoso.com><support.microsoft.com> **Version 1703 or later:** If you do not want to send traffic to Microsoft, use the <about:blank> value, which honors both domain and non-domain-joined devices when it's the only configured URL.  **Version 1809:** When you enable the Configure Open Microsoft Edge With policy with any option selected, and you enable the Configure Start Pages policy, the Configure Open Microsoft Edge With policy takes precedence, ignoring the Configure Start Pages policy.

> **Registry settings**
- Path: HKLM\SOFTWARE\Policies\Microsoft\MicrosoftEdge\Internet Settings
- Value name: ProvisionedHomePages
- Value type: REG_SZ

***

[**Set Home Button URL**](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies#set-home-button-url)

> By default, Microsoft Edge shows the home button and loads the Start page, and locks down the home button to prevent users from changing what page loads. Enabling this policy loads a custom URL for the home button. When you enable this policy, and enable the Configure Home Button policy with the Show home button & set a specific page option selected, a custom URL loads when the user clicks the home button.


Group Policy | MDM | Registry | Description
-- | -- | -- | --
Disabled or not configured(default) | Blank | Blank | Show the home button, load the Start pages, and lock down the home button to prevent users from changing what page loads.
Enabled - String | String | String | Enter a URL in string format, for example, https://www.msn.com.  For this policy to work, you must also enable the Configure Home Button policy and select the Show home button & set a specific page option.

> **Registry settings**
- Path: HKLM\Software\Policies\Microsoft\MicrosoftEdge\Internet Settings
- Value name: ConfigureHomeButtonURL
- Value type: REG_SZ

***
Based on the documentation above, I believe the following explanation to be what it means:
1. **ProvisionedHomePages** (Configure Start pages):
  This setting tells Microsoft Edge which page to load as the default startup page. If more than 1 page URL is specified, those pages should load together in the order they are listed in the registry key.
2. **ConfigureHomeButtonURL** (Set Home Button URL):
  This setting tells Microsoft Edge which page should load _when you press the **Home** button in the browser toolbar_.

**Caveat:** I don't have the required environment to verify the complete correctness of my assessment, but this explanation is based on what I can read from the documentation above, copied directly from the doc page [Group Policy and Mobile Device Management settings for Microsoft Edge (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies) (as linked above in your original comment post https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1785#issue-367630840).

**Comment by RAJU2529** [comment] 2019-04-20 12:18
Thanks a lot sir. after reading your explanation. I clearly understood the difference.

Now you can close this issue

**Comment by illfated** [comment] 2019-04-20 13:46
(@officedocsbot Close.)

**Comment by illfated** [comment] 2019-04-20 15:41
@RAJU2529 : Thank you for providing regular feedback to the Microsoft Docs. I can only express my regret that I was unaware of this issue at an earlier time, but I hope my feedback was useful enough, even if it took this much time before you got the answer you were looking for. Thank you also for your reply indicating that your question has been answered.

While I have been able to respond to your question, I rely upon the Microsoft Docs team members to handle the issue pages for closing or delegating the issue questions to the right person to solve the issue at hand. This issue ticket will probably be closed at a later date, when the Microsoft Docs team members are back from the Easter holidays.

(This issue ticket can now be resolved and closed with "@officedocsbot Close" from one of the team members.)

**Comment by e0i** [comment] 2019-04-20 23:12
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-04-20 23:13
Hello @RAJU2529

We are marking this issue as resolved since you have confirmed that your question has been answered.

Note that you can also close any issues that have been resolved yourself via clicking _"Close issue"_ button at the bottom of the comment textbox.


@illfated Sincerely thank you for helping resolve this issue, and your generous contributions to the community in general. Much appreciated.

**Comment by e0i** [comment] 2019-04-20 23:13
@officedocsbot close

**Closed by e0i** 2019-04-20 23:13 UTC
Labels: assigned-to-author, browser-edge, policy settings, question, to-triage
