### ISSUE TITLE
VPN stack no longer stores session credentials in Credential Manager.

### ISSUE THREAD

**Issue by sivan-koren** [MicrosoftDocs/windows-itpro-docs#10305] opened 2022-01-21 00:29 UTC
As of Windows 10 build 19044.1469 or a previous, recent update, the VPN stack does not appear to store a *Session credential in Credential Manager upon establishing a VPN connection.

This documentation should be updated to reflect the change, or if this change is not intentional, a link to any relevant patches/KB articles should be included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b4b43c7-e56a-f762-846f-51257983d3ab
* Version Independent ID: fa5d8ebb-02ea-cbc1-9b29-69bb710643e3
* Content: [How to use Single Sign-On (SSO) over VPN and Wi-Fi connections (Windows 10 and Windows 11) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/how-to-use-single-sign-on-sso-over-vpn-and-wi-fi-connections)
* Content Source: [windows/security/identity-protection/vpn/how-to-use-single-sign-on-sso-over-vpn-and-wi-fi-connections.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/how-to-use-single-sign-on-sso-over-vpn-and-wi-fi-connections.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment] 2022-03-16 12:10
Hello @sivan-koren ,
**the VPN stack does not appear to store a Session credential in Credential Manager upon establishing a VPN connection.** - could you please provide an information source?
I tried to find it, but didn't succeed.
Thank you

**Comment by sivan-koren** [comment] 2022-03-16 15:24
On any fresh Windows 10 Pro or Windows 11 Pro installation, create a new
VPN connection and connect. Then open the credential manager and look to
see that there is no "*Session" entry, contrary to the documentation. See
attached screenshot to observe that this entry does not exist when
connected to a VPN.

If the "*Session" entry is only created under certain conditions, these
conditions should be documented.

**Comment by sivan-koren** [comment] 2022-03-16 15:29
![nosession](https://user-images.githubusercontent.com/13458661/158626933-2564e3f2-0165-410f-af50-b2e78ddb0ade.png)

**Comment by MaratMussabekov** [comment] 2022-03-22 03:38
Hello, yes, confirmed.
On 21h1 and prior I see *session, on 21h2 - do not.
I will create a PR.
Thank you

**Comment by sivan-koren** [comment] 2022-03-23 16:56
I'm still confused here. The article now states that the credential is not visible in Credential Manager. Does that mean that there is in fact no credential or that it is simply not visible in the GUI? If the credential does exist, why does Windows prompt the user to enter individual credentials for each network resource? Doesn't that imply that the credential stored in the VPN stack is factually not passed for Windows to use against network resources contrary to the entirety of this article? Does this only work on domain attached versions of Windows (e.g. only Windows Pro/Enterprise and only when connected to a domain controller)? If so, the documentation should be revised to state so as this is a dramatically different behavior than previous versions of Windows.

**Comment by MaratMussabekov** [comment] 2022-03-25 10:20
Hello @sivan-koren 
yes, you are correct, it asks for credential, so my PR may be wrong.
**Does this only work on domain attached versions of Windows** - no, as far as I tested, behavior is the same.

Dear @denisebmsft , can it be addressed to the production team? It looks like SSO for VPN doesn't work in 21h2, and I believe that "applies to" section need to be added to the article to show that article is for 21h1 and earlier, however I have some concerns:
1. I only tested PPTP VPN, for other types behavior could vary
2. it is not shown in 21h2 change log that this feature was removed
3. may be some other features were introduced for VPN SSO (still nothing in change log)

Dear @e0i , could you please re-open this issue?

Thank you

**Comment by Thuyaaung939** [comment] 2022-10-11 06:58
***@***.***

**Comment by yogkumgit** [comment] 2022-12-23 13:37
@paolomatarazzo Please help us in resolving this issue. Thanks

**Closed** 2022-12-28 16:17 UTC
Labels: identity protection, writer-input-required, doc-bug

**Comment by sivan-koren** [comment] 2022-12-28 16:39
@v-stsavell, this is still incorrect. *Session isn't just "not visible in Credential Manager." Not visible, and doesn't exist are very different meanings. There is actually no credential based on mine and others' testing. If that's expected, then this entire portion of the article is factually false:

```
This article explains requirements to enable Single Sign-On (SSO) to on-premises domain resources over WiFi or VPN connections. The following scenarios are typically used:

Connecting to a network using Wi-Fi or VPN.
Use credentials for WiFi or VPN authentication to also authenticate requests to access a domain resource without being prompted for your domain credentials.
For example, you want to connect to a corporate network and access an internal website that requires Windows integrated authentication.

The credentials that are used for the connection authentication are placed in Credential Manager as the default credentials for the logon session. Credential Manager stores credentials that can be used for specific domain resources. These are based on the target name of the resource:

For VPN, the VPN stack saves its credential as the session default.
For WiFi, Extensible Authentication Protocol (EAP) provides support.

```

If no one can figure out how SSO works on these later versions, the least we should expect from Microsoft is to document that no documentation exists for SSO over VPN in 21H2 and later and that this entire article only applies to versions prior to that.

**Comment by paolomatarazzo** [comment] 2023-01-13 18:50
thank you for the feedback, @sivan-koren 
Which VPN protocol are you using? Have you reviewed the following article? https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-known-issues

**Comment by sivan-koren** [comment] 2023-01-13 20:25
Paolo,
Thank you for your response. It appears that in a recent Windows update, this issue may have been quitly fixed. As of today, the VPN stack suddenly behaves as it did prior to 21H2.
I did check the article, and tested disabling and re-enabling Credential Guard had no effect on the issue. The *Session credential is now present, functional and visible.
I suspect at this point that there was in fact a bug in the 21H2 update that caused the VPN stack to stop storing credentials in Credential Manager. This bug was confirmed by @MaratMussabekov at the time. However, it appears that it was quietly fixed in a very recent Windows update.
I suggest at this point that this documentation should be reverted to how it read on Jan 20, 2022 before this issue was logged, because the *Session credential is in fact now visible in Credential Manager.

Cheers!

**Comment by paolomatarazzo** [comment] 2023-01-13 21:49
That's interesting, thank you for letting me know, @sivan-koren. I will check with the feature PM and determine how to adjust the documentation.
