### ISSUE TITLE
safety scanner remove malware

### ISSUE THREAD

**Issue by dyd1947** [MicrosoftDocs/windows-itpro-docs#8378] opened 2020-09-29 01:32 UTC
[Enter feedback here]
Look at the scan result: unknown malware was detected but not deleted. I am a genuine Win10 home version computer, and the computer motherboard has a key, which is activated with the digital license associated with the account. I always feel that there is an invisible hand holding me, unable to work. You can detect malware. I want to delete the unknown malware detected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment] 2020-09-29 05:12
@dyd1947 .a after completion of scanning, find the path of the malware files.notedown on notepad.
now boot the windows into safe mode.
go the location of the malware file , delete it manually.

**Comment by e0i** [comment] 2020-10-19 13:38
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-10-19 13:38 UTC
Labels: intelligence

**Comment by d19470218** [comment] 2020-10-21 09:20
按你的办法，我想在记事本上找到恶意软件文件的路径，我不会找啊。请你把查找方法，说的详细些。
我点击病毒后，出现了新的页面，我无法操作。其网址：
https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=Unknown
我想[查找案例]，提示【该页面不存在】。

**Comment by illfated** [comment] 2020-10-21 17:21
Translated via web MT engine:

> According to your method, I want to find the path of the malware file in Notepad, I won't find it. Please explain the search method in more detail.
> After I clicked on the virus, a new page appeared and I could not operate it. Its URL:
> microsoft.com/en-us/wdsi/threats/threat-search?query=Unknown
> I want to [Find a case] and prompt [This page does not exist].

看起来您应该改为在Microsoft论坛页面中询问，以获得适合您要求的答案。

免责声明：我与GitHub上的Microsoft或Microsoft Docs团队无关。

该存储库的目的是通过为用户提供一种报告事实错误，改进建议并请求对新版本进行更新的方式来改进现有文档。 由于团队规模小且工作量大，MS Docs团队成员可能没有时间回答您的问题。

尝试使用以下资源与可能会为您提供帮助的用户取得联系：

- https://social.msdn.microsoft.com/Forums/zh-CN/home
- https://social.technet.microsoft.com/Forums/zh-CN/home
- https://social.msdn.microsoft.com/Forums/zh-TW/home
- https://social.technet.microsoft.com/Forums/zh-TW/home
- https://answers.microsoft.com/zh-hans


***

Looks like you should ask in the Microsoft Forum pages instead, to get an answer that fits your request.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions. The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
