### ISSUE TITLE
Error in spreadsheet

### ISSUE THREAD

**Issue by povlhp** [MicrosoftDocs/windows-itpro-docs#8728] opened 2020-12-01 09:00 UTC
Spreadsheet lists 
notify.windows.com

But there is no DNS entry for it.

;QUESTION
notify.windows.com. IN A
;ANSWER
;AUTHORITY
windows.com. 299 IN SOA ns1-205.azure-dns.com. azuredns-hostmaster.microsoft.com. 1 3600 300 2419200 300
;ADDITIONAL
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2748359b-273d-7faa-6a63-7a6ebea450d2
* Version Independent ID: f4885da5-9a83-13aa-789e-1751db586404
* Content: [Set up Microsoft Defender ATP deployment - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/production-deployment#tenant-configuration)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/production-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/production-deployment.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment] 2020-12-02 09:42
I don't think the address needs to be traceable via DNS. See this page explaining why that address needs to be part of the list:
- https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview#important-notes
- It is important that the cloud service always ensures that the channel URI uses the domain "notify.windows.com". The service should never push notifications to a channel on any other domain. If the callback for your app is ever compromised, a malicious attacker could submit a channel URI to spoof WNS. Without inspecting the domain, your cloud service could potentially disclose information to this attacker unknowingly.

**Comment by illfated** [comment] 2020-12-02 09:45
The addresses in the list are not required to be DNS compliant. They are used to create rules for how MSDATP / Microsoft Defender for Endpoint handles network communication.

**Comment by e0i** [comment] 2020-12-27 12:29
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-12-27 12:29 UTC
Labels: defender for endpoint
