### ISSUE TITLE
this

### ISSUE THREAD

**Issue by luciousnickel28** [MicrosoftDocs/windows-itpro-docs#6617] opened 2020-05-01 14:10 UTC
i cant do it for my school

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb904674-d586-0a38-0e7c-7ac3e06cbcd9
* Version Independent ID: 549fbb52-6234-2a79-8604-85498e622f98
* Content: [Enable hardware-based isolation for Microsoft Edge (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by mypil** [comment] 2020-05-02 16:35
@luciousnickel28 - Can you please share what specific issue you have with this doc? Or are you having some technical issues which requires technical support?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by illfated** [comment] 2020-05-02 21:03
To me, that looks more like an implementation issue than a suggestion for what should be done to improve the existing document.

But you are right, it would be useful to know more about the details, to be able to determine exactly what the issue is about.

**Comment by mypil** [comment] 2020-05-09 22:14
@luciousnickel28 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.

**Closed by mypil** 2020-05-09 22:14 UTC
