### ISSUE TITLE
Not Applicable

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#3399] opened 2019-04-29 18:19 UTC
I have been attempting to test Application Guard for Edge via InTune - on Win10 Pro devices this comes through as 'Not Applicable'. Is Ent required despite the OS requirements outlined here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43df7b-6ead-de5a-2e41-4d49978ab485
* Version Independent ID: 5497d300-cb21-55f3-7e80-98bc3592635c
* Content: [System requirements for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment] 2019-04-29 18:36
@Niglb I'll confirm. Can you confirm you are trying on 1803 or higher?

**Comment by Niglb** [comment] 2019-04-29 21:39
Confirmed - I am actually testing 1903 currently.

**Comment by Justinha** [comment] 2019-04-30 21:00
@Niglb Engineering confirmed Pro is supported since 1803. Do other system requirements seems set?

**Comment by Niglb** [comment] 2019-05-01 15:17
As far as I can tell yes - I am testing on Lenovo M920q hardware

**Comment by mypil** [comment] 2019-05-03 14:03
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-05-03 14:04
@Justinha - Do you have any updates on this?

Thank you,

**Comment by Justinha** [comment] 2019-05-03 14:16
@mypil No, we've confirmed the SKUs listed are right. I've asked engineering for other suggestions and I'll pass along what I learn. In the meantime @Niglb you might want to contact customer support to get the best help for this.

**Comment by mypil** [comment] 2019-05-03 14:35
@Niglb - Based on the information provided by Justinha, the best way forward is if you can open a service ticket so this can get resolved ASAP.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Justinha** [comment] 2019-05-03 19:27
@Niglb I'm told WDAG in the Pro SKU can't be managed with Intune; it's standalone only. @mypil could you assist with submitting a PR? We can add a line below the SKUs listed in the table to say Pro edition is only for for non-managed devices; Intune or 3rd party MDM cannot manage WDAG on Pro edition.

**Comment by Niglb** [comment] 2019-05-03 20:23
@Justinha Oh interesting which would explain the Not Applicable message via the InTune configuration reports. Maybe I can configure via a InTune deployed powershell script to Win10 Pro? :)

**Comment by mypil** [comment] 2019-05-06 12:24
@Justinha - I will be glad to help. Assigning @Malind19 for the PR creation.

@Malind19 - kindly create the requested PR for this issue. 

Thank you.

**Comment by Malind19** [comment] 2019-05-09 02:56
@mypil Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3592

**Comment by mypil** [comment] 2019-05-09 13:10
@Niglb - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-05-13 13:24
@officedocsbot close

**Closed by mypil** 2019-05-13 13:24 UTC
