### ISSUE TITLE
Deep dive references point to Microsoft Virtual Academy

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#3513] opened 2019-05-06 07:51 UTC
Hello, 

The Deep Dive References point to Microsoft Virtual Academy courses. Since MVA is being retired I suggest to update the links, assuming that these videos are being hosted elsewhere. 

Regards
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f8afd0-78e2-b866-196e-7068fd3743fe
* Version Independent ID: 94338ba3-90f0-eb4c-54e8-d3de22d8647b
* Content: [How Windows Defender Credential Guard works](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-how-it-works)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-how-it-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-how-it-works.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment] 2019-05-08 19:02
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-10 18:42
@DaniHalfin

Would you be able to advice how to approach this issue? We would like to follow-up with a PR. Thanks.

**Comment by e0i** [comment] 2019-05-27 21:24
@alexverboon The issue is under investigation. Thank you for providing this valuable feedback.

**Comment by illfated** [comment] 2019-05-27 21:36
Like I mentioned in my PR #3816 , there is a possibility that the missing content could be found on this page:
https://www.linkedin.com/learning/search?keywords=Deep+Dive+into+Windows+Defender+Credential+Guard

**Comment by e0i** [comment] 2019-05-31 13:21
@officedocsbot add label mva-links

**Comment by e0i** [comment] 2019-06-10 22:50
@alexverboon 

The documentation team has been informed regarding the situation and content changes are being made progressively.

The issue is thus being marked as resolved.

Thank you for bringing this up to attention. Much appreciated.

**Comment by e0i** [comment] 2019-06-10 22:50
@officedocsbot close

**Closed by e0i** 2019-06-10 22:50 UTC
Labels: mva-links
