### ISSUE TITLE
[LOC]"&lt;"needs to be replaced with"<", "&gt;"needs to be replaced with">"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3805] opened 2019-05-24 17:15 UTC
https://docs.microsoft.com/ja-jp/windows/application-management/manage-windows-mixed-reality
![manage-windows-mixed-reality](https://user-images.githubusercontent.com/40815708/58345284-ec856180-7e92-11e9-8f59-61c1f21cd538.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 98d4c6ca-ae3c-7750-f58b-0df996e41402
* Version Independent ID: 0d05fd22-b761-6fb4-8686-a2021573e542
* Content: [企業で Windows Mixed Reality アプリを有効化またはブロックする (Windows 10)](https://docs.microsoft.com/ja-jp/windows/application-management/manage-windows-mixed-reality)
* Content Source: [windows/application-management/manage-windows-mixed-reality.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/manage-windows-mixed-reality.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by illfated** [comment] 2019-05-24 18:31
Future solution: PR #3807 -- when merged into the `master` branch and migrated to the Docs page, subsequently migrated to the localized page, it should close this issue.

(Comments are welcome regarding estimated time of total time before arrival on the localized pages.)

**Comment by e0i** [comment] 2019-05-25 01:35
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-27 21:02
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by hyoshioka0128** [comment] 2019-06-10 03:49
@illfated : #3807 (ja-jp) was also fixed.

**Comment by illfated** [comment] 2019-06-10 06:36
Nice! The PR changes have migrated both to the docs.microsoft.com/en-us/ page and to the /ja-jp/ page. Very good indeed.

@e0i : This issue ticket is now resolved and can be closed. Ref. the XML content in

- https://docs.microsoft.com/ja-jp/windows/application-management/manage-windows-mixed-reality#mixed-reality-%E3%83%9D%E3%83%BC%E3%82%BF%E3%83%AB%E3%82%92%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%99%E3%82%8B
- https://docs.microsoft.com/en-us/windows/application-management/manage-windows-mixed-reality

**Somewhat unrelated, but on the same page:**
I just noticed that for some reason, 2 out of 3 section headings in the /en-us/ version don't work or have disappeared (behaving as if there is no spacing between the headings and the preceding text. Not sure what happened there, but it is at least somewhat broken for the en-us version, even if the section titles are intact on the /ja-jp/ and /fr-fr/ pages. I need to investigate if there are any unexpected characters in the /en-us/ page. (Not caused by anything related to this issue ticket.) I may just open a new PR for that page, as soon as I manage to figure out what went wrong.

**Comment by e0i** [comment] 2019-06-28 12:56
Thank you @hyoshioka0128 for the report, and @illfated for your generous contributions. Much appreciated.

**Comment by e0i** [comment] 2019-06-28 12:56
@officedocsbot close

**Closed by e0i** 2019-06-28 12:56 UTC
Labels: localization
