### ISSUE TITLE
Dynamic Provisioning and Windows 10 builds

### ISSUE THREAD

**Issue by quarkyuk** [MicrosoftDocs/windows-itpro-docs#1705] opened 2018-09-28 20:38 UTC
Are there any considerations around DP packages and builds? So if I build a DP package in WICD 10.0.17134.1, how do I know if it will work with Windows 1803, 1709, 1702, 1609, etc? 

Some guidance in the article around that would be great (as there are changes to OOBE, I guess there are DP changes to reflect that?) if applicable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda43942-cce6-c093-0637-21b5c6e00335
* Version Independent ID: 03a1e0bd-83ac-666d-da6b-c47259fe8b02
* Content: [Windows 10 deployment considerations (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deployment-considerations)
* Content Source: [windows/deployment/planning/windows-10-deployment-considerations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-deployment-considerations.md)
* Product: **w10**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by egallagh** [comment] 2019-02-09 18:00
Ultimately, there is no way to know if the specific settings in the DP package will work in past or future versions of Windows without doing appropriate regression testing.
Recommend closure.

**Comment by e0i** [comment] 2019-04-08 18:49
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-04-08 18:49
Hello @quarkyuk  ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment] 2019-04-08 18:49
@officedocsbot close

**Closed by e0i** 2019-04-08 18:49 UTC
Labels: assigned-to-author, deployment
