### ISSUE TITLE
Fehler in deutscher Übersetzung: mf * eine* statt mf *a*

### ISSUE THREAD

**Issue by wech71** [MicrosoftDocs/windows-itpro-docs#2968] opened 2019-03-19 10:00 UTC
Fehler in deutscher Übersetzung:

    der primäre MFA verwendet den Namen `mf * eine*` oder 

Im Original ist von 

    the primary MFA uses the name  `mf *a*` or 

die Rede, hier mit "a" also nicht "eine" sondern eine alphabetische Numerierung, nämlich **mfa** gemeint.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 08552f2d-5920-7a9b-a96b-6d3518b1a11a
* Version Independent ID: e6e8ac42-46ea-475c-016c-2b0931a72862
* Content: [Konfigurieren oder Bereitstellen von Multifactor Authentication (MFA)-Diensten (Windows Hello for Business)](https://docs.microsoft.com/de-de/windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by illfated** [comment] 2019-03-20 00:17
Funny translation bug. Original text in the `de-de` version of the page:
- https://docs.microsoft.com/de-de/windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa#voraussetzungen
> Dieser Dokumentation wird der primäre MFA verwendet den Namen mf * eine* oder mfa.corp.contoso.com. Alle sekundären Server verwenden Sie den Namen Mfa * n* oder Mfan. corp.contoso.com, wobei n die Anzahl der bereitgestellten MFA-Servers ist.

Recommended translation:
> Dieser Dokumentation wird der primäre MFA verwendet den Namen <b>mf* a</b>* oder **mfa.corp.contoso.com**. Alle sekundären Server verwenden Sie den Namen <b>mfa</b> <b>* n*</b>   oder <b>mfa*n*.corp.contoso.com</b>, wobei n die Anzahl der bereitgestellten MFA-Servers ist.

See also the US English page for reference:
- https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa#prerequisites
> For this documentation, the primary MFA uses the name <b>mf* a</b>* or **mfa.corp.contoso.com**. All secondary servers use the name <b>mfa* n</b>* or <b>mfa*n*.corp.contoso.com</b>, where _n_ is the number of the deployed MFA server.

Please also note my suggestion to use lowercase for the MFA-Server name instead of uppercase M. The naming schema formats should not change between the translations.
Notice also that HTML source handles the asterisks as text instead of formatting code, so they can be displayed without extra spaces. MarkDown uses asterisks as format tags, making Github pages a bit more complex to handle in these cases.

**Comment by mypil** [comment] 2019-03-20 17:47
@officedocsbot assign @OfficeGlobal

**Comment by mypil** [comment] 2019-04-04 11:35
@OfficeGlobal - Do you have any updates on this issue? Kindly assist with this Translation (Localization) issue. Thank you.

**Comment by mypil** [comment] 2019-04-05 17:40
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-04-08 11:13
@dongmicro - I would like to follow up on this. Do you have any updates? Thanks.

cc: @AndreaBarr

**Comment by mypil** [comment] 2019-04-09 18:36
@officedocsbot add label localization

**Comment by mypil** [comment] 2019-04-15 16:00
@dongmicro - Can you assist with this Translation (Localization) issue?

**Comment by mypil** [comment] 2019-04-22 12:02
@dongmicro - I would like to follow up on this. Can you please assist with this Translation (Localization) issue? Thanks.

**Comment by mypil** [comment] 2019-04-24 20:07
@dongmicro - Any updates on this?

**Comment by illfated** [comment] 2019-04-25 04:17
Maybe @dongmicro is unavailable for the time being?
(Looks like there is no activity for 2019 here on Github.)

**Comment by mypil** [comment] 2019-05-02 10:35
@officedocsbot unassign @OfficeGlobal

**Comment by mypil** [comment] 2019-05-02 10:36
@officedocsbot assign @dongmicro

**Comment by mypil** [comment] 2019-06-06 14:06
@officedocsbot unassign @mypil

**Comment by e0i** [comment] 2019-07-17 14:04
@officedocsbot assign @e0i
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by e0i** [comment] 2019-07-30 15:51
@officedocsbot assign @e0i @officedocsbot assign @MollyMalone @officedocsbot add label localization
--

**Comment by illfated** [comment] 2019-07-30 16:03
Looks like @officedocsbot did not assign @MollyMalone as expected. I can understand that "add label localization" was skipped, since it is already there, but not adding the assignment of @MollyMalone is something the admin responsible for @officedocsbot needs to check to find out if this was intentional or a bug.

**Comment by TinaMcN** [comment] 2019-07-30 16:44
Please assign to @TinaMcN instead (it's the replacement for my @MollyMalone account)

**Comment by TinaMcN** [comment] 2019-07-30 17:04
This topic is currently machine translated.  I set it to be human translated - this may take a few weeks to complete.

**Comment by e0i** [comment] 2019-08-01 20:13
@officedocsbot unassign @dongmicro 
 @officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment] 2019-09-04 18:20
This topic appears to have been removed for both English and German.

**Comment by illfated** [comment] 2019-09-04 18:36
Confirmed, the pages are indeed gone.
MultiFactor Authentication (MFA) is no longer offered to new customers.

**Comment by TinaMcN** [comment] 2019-09-04 18:38
@illfated, thanks for confirming.  Can you close the issue?  I don't have access to close issues.

**Comment by illfated** [comment] 2019-09-04 18:52
Try using the command
@officedocsbot Close

(and if that command does not work for you, @e0i (Onur) will help us out).

**Comment by TinaMcN** [comment] 2019-09-04 19:37
@officedocsbot Close

**Comment by TinaMcN** [comment] 2019-09-04 19:39
@illfated, where do I enter commands?  I don't see anywhere to enter them.

**Comment by illfated** [comment] 2019-09-04 19:47
👍 You already did. Thanks for checking. You were correct the first time.
You do not appear to be on the list of users who can ask @officedocsbot to perform tasks.

All we can do now, is to wait for @e0i to close this issue ticket.

**Comment by e0i** [comment] 2019-09-11 14:53
@TinaMcN @illfated Thanks. OfficeDocsBot has been deprecated.

**Closed by e0i** 2019-09-11 14:53 UTC
Labels: localization

**Comment by illfated** [comment] 2019-09-11 15:52
Thank you for the "heads up" information, it is news to me that the bot has been retired.
