### ISSUE TITLE
reset Windows update manually steps incorrect

### ISSUE THREAD

**Issue by ddecavele-atos** [MicrosoftDocs/windows-itpro-docs#8684] opened 2020-11-21 03:28 UTC
Step 3 of the manual resets points to:
`Del "%ALLUSERSPROFILE%\Application Data\Microsoft\Network\Downloader\qmgr*.dat"`

On Windows 10 Pro version 2004 this directory does not exist.

`%ALLUSERSPROFILE%\Microsoft\Network\Downloader` does exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment] 2020-11-21 06:03
@ddecavele-atos . Thanks for pointing out. I will check in Windows 10 20h2 and I will update the status.

**Comment by illfated** [comment] 2020-11-21 07:51
Not sure how relevant this is, but on my Windows 10 Home x64, Version 20H2 (OS Build 19042.630), this directory exists (hidden, owner: System) with the following files:

![image](https://user-images.githubusercontent.com/38162891/99870896-c4d19f80-2bd6-11eb-832a-2fa476adbef1.png)

**Comment by RAJU2529** [comment] 2020-11-21 08:44
on windows 10 Enterprise 20H2 build no 19042.360 , folder exists  in  below path
**C:\ProgramData\Microsoft\Network\Downloader**
![Capture](https://user-images.githubusercontent.com/3296790/99871881-cc5b6d80-2c03-11eb-8024-4015aa18f98d.JPG)

**Comment by illfated** [comment] 2020-11-21 10:07
OK, fair enough. Maybe there is something going on in the Windows 10 Home versions which doesn't happen in Windows 10 Enterprise.

**Comment by e0i** [comment] 2020-12-27 11:42
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Thank you.

**Closed by e0i** 2020-12-27 11:42 UTC
Labels: deployment
