### ISSUE TITLE
reboot-csp.md needs Time zone guidance

### ISSUE THREAD

**Issue by lanatmwan** [MicrosoftDocs/windows-itpro-docs#4811] opened 2019-08-28 21:26 UTC
The documentation needs more details on how time zones are handled. 

Specifically, I would like a real world scenario like how to setup midnight reboots across devices in multiple time zones. 

In experimenting with date formats, it looks like I need to specify the utc offset to get my devices on pacific time to reboot at midnight. '2019-08-02T07:00:00Z' 
However, that would seem to imply I need to be able to assign a group to each time zone and have one configuration policy per group. That seems rather inefficient so I'm hoping a better way can be documented.

**Comment by e0i** [comment] 2019-08-28 21:28
@officedocsbot assign @e0i

**Comment by illfated** [comment] 2019-08-28 22:38
Duplicate ticket to #4810 - should also have been reported from the related document page instead of being opened as a ticket with no reference.

**Comment by e0i** [comment] 2019-09-14 19:57
@lanatmwan 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by illfated** [comment] 2019-09-15 12:52
Intended references to the following document page(s):
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/reboot-csp.md
- https://docs.microsoft.com/en-us/windows/client-management/mdm/reboot-csp


|category|content|
|:---:|---|
|title:|Reboot CSP|
|description:|Reboot CSP|
|ms.assetid:|4E3F1225-BBAD-40F5-A1AB-FF221B6BAF48|
|ms.reviewer:|   |
|manager:|dansimp|
|ms.author:|dansimp|
|ms.topic:|w10|
|ms.prod:|article|
|ms.technology:|windows|
|author:|manikadhiman|
|ms.date:|06/26/2017|

**Comment by e0i** [comment] 2019-10-27 22:29
Duplicate of #4810

**Closed by e0i** 2019-10-27 22:29 UTC
