### ISSUE TITLE
Supported Windows version

### ISSUE THREAD

**Issue by SamiSavolainen** [MicrosoftDocs/windows-itpro-docs#5704] opened 2019-12-16 19:23 UTC
Hi, what is officially supported Windows version for Self-Deploying mode today ? I have active at Intune Support since our customer started experiencing TPM-related problems this with hardware that has worked last week and before with Windows 1903. Intune Support instructed us to use the most current (1909) version, but I do not believe this...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6867cc8c-868d-d472-8aa5-1ed5b94ced2c
* Version Independent ID: 6822e12d-7474-9e49-1e8b-88f7eec3b22c
* Content: [Windows Autopilot Self-Deploying mode - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/self-deploying#feedback)
* Content Source: [windows/deployment/windows-autopilot/self-deploying.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment] 2019-12-17 04:29
@SamiSavolainen . Why you don't believe any reasons.  your reasons might me helpfull to clarify your doubts from Windows expert users.
I don't have intune , so I can't comment

**Comment by joinimran** [comment] 2020-01-01 18:05
@SamiSavolainen Can you please share more details what users are experiencing before we can better make corrections in the document.

**Comment by illfated** [comment] 2020-01-01 21:12
@SamiSavolainen : You mention TPM related problems, do you know with which TPM version your customer experiences these issues?

**Comment by SamiSavolainen** [comment] 2020-01-03 07:30
It turned out later that the problems started after MS updated customer Intune tenant to version 1912, which was resolved by Microsoft. Problems were experienced both with Self-Deploying and White Glove deployments. Ticket was opened and MS customer adviced to use the most current version(1909) of Windows.

**Comment by illfated** [comment] 2020-01-03 09:19
OK, so the catalytic factor here is updating to MS Intune version 1912 while using Windows 10 1903. Have I understood you correctly, that updating to Windows 10 version 1909 did not solve the problem?

**Comment by joinimran** [comment] 2020-01-05 06:56
@SamiSavolainen To make it further clear, the documentation is correct but there was an issue with intune itself which lead to this scenario. And, it's working fine for both 1903 as well as 1909 versions?

**Comment by SamiSavolainen** [comment] 2020-01-08 06:16
Hi,

This is correct.

Problems started after Microsoft had committed the monthly update (1912) to
Intune tenants.
After that Self-Deploying and White Glove methods stopped working.
Common to these methods is requirement for TPM 2.0.

It turned out that there was a bug in the Intune update that was later
fixed.

Hopefully this clarifies the case!

Br,
Sami

Sami Savolainen
p. +358 50 578 1135 <#SignatureSanitizer_SafeHtmlFilter_>
<#SignatureSanitizer_SafeHtmlFilter_>

**Comment by SamiSavolainen** [comment] 2020-01-08 06:21
Yes, the issue was Intune itself that was later confirmed by Microsoft.
Client operating system version itself was not the issue.

**Comment by illfated** [comment] 2020-01-08 07:02
Thank you for confirming what caused the issue. I presume we can close this ticket now, since it does not affect Windows Autopilot.

**Comment by mypil** [comment] 2020-01-11 00:47
Closing issue as it has been confirmed that it does not affect Windows Autopilot.

**Closed by mypil** 2020-01-11 00:47 UTC
