### ISSUE TITLE
Managed Installers only works for Windows Enterprise and not Windows Business/Pro

### ISSUE THREAD

**Issue by stevenm57811** [MicrosoftDocs/windows-itpro-docs#10548] opened 2022-05-19 07:23 UTC
[[Please update the article to reflect that the managedinstaller feature is only available to Windows Enterprise SKUs. Tested two Windows 11 enterprise machines and managed installers worked. Tested two windows 10 business and pro machines and they have failed. Please update the article to save people time. 

This is most likely related to AppLocker only being supported for non enterprise SKU's if you use the AppLocker CSP. The AppLocker CSP does not actually support managed installers. I used powershell to deploy my applocker xml file, still no success unless it was on an windows enterprise machine.
 ]]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5881f449-2567-9d50-99be-0b6cdb1218d7
* Version Independent ID: e4d0109a-54dc-3bb9-d4c5-cad8fdf93179
* Content: [Managed installer and ISG technical reference and troubleshooting guide (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/configure-wdac-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/configure-wdac-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/configure-wdac-managed-installer.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment] 2022-05-20 02:03
@denisebmsft Please close issue #10548, because the author of this issue is already duplicate issue #10547.

**Comment by aczechowski** [comment] 2022-06-02 23:41
duplicate of #10547

**Closed by aczechowski** 2022-06-02 23:41 UTC
Labels: application control
