### ISSUE TITLE
Script links go nowhere

### ISSUE THREAD

**Issue by TrevorWesterdahl** [MicrosoftDocs/windows-itpro-docs#9315] opened 2021-03-16 21:03 UTC
The script links go nowhere. Please provide valid links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment] 2021-03-16 21:23
Duplicate of issue ticket #4930, #9104, #9216, #9237, #9287, and #9304.

The resolution of this issue is currently a work in progress, and has been so for a while.

Please visit the other linked tickets to look for the progress status.

#please-close

**Comment by jaimeo** [comment] 2021-03-16 21:59
I finally got some needed info from SMEs--hope to redo this article tomorrow.

**Comment by e0i** [comment] 2021-03-23 15:55
Fixed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/15e9a411fce64546f8572b29691f782b3f4badb1#diff-fc5cd38a44f9cd55d877749fbddbe9dabdf373fbf2348b20aba9581b44062630

**Closed by e0i** 2021-03-23 15:55 UTC
Labels: deployment
