### ISSUE TITLE
Doc does not make sense

### ISSUE THREAD

**Issue by termnews** [MicrosoftDocs/windows-itpro-docs#5832] opened 2020-01-11 11:33 UTC
These instructions don't make any sense, previous comments deliver the details on this statement, but no one assigned to this doc seems to be able to understand these comments. So I just post this to increase the counter -- perhaps Microsoft assigns someone who does more than copy-pasting friendly reply snippets to the issue when there are enough posts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Firmware Update - Surface](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update#feedback)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment] 2020-01-11 17:26
@e0i . Please assign the  author of this article, So that author can directly  submit  comments

**Comment by illfated** [comment] 2020-01-11 17:51
To quote jvsam: Or is there a way that we can engage the Product Engineering team to help clarify the feedback?

**Comment by e0i** [comment] 2020-01-13 22:56
Hello, @termnews Would you clarify the problematic part(s) about the document? Is it the snippets? We would like to follow up with clarifying updates. Thanks you for providing feedback.

**Comment by illfated** [comment] 2020-01-13 23:17
I had to re-read the issue post a couple of times to see the relation, but this is mostly a follow-up response to the content in issue ticket #5756 [**Some comments about this documentation page**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5756) and partially #5214 (Better describe the update status / better logging) , which might be closed soon.

Based on that, I presume this is about the uncertainties around the Microsoft Surface firmware update procedure, which may or may not work as intended & expected, depending on how you read the documentation.

**Comment by greg-lindsay** [comment] 2020-01-18 00:29
I should probably be the listed author of this article (although I didn't write it) because I've taken over managing these topics.  I will address the issue with the product team and try to rewrite the article, or get it rewritten and then edit and republish.

**Comment by e0i** [comment] 2020-02-01 16:32
Apologies to all for the delayed follow-up.

@greg-lindsay Please do let me know whether any independent contributions would be helpful to address this matter. Thank you.

**Comment by greg-lindsay** [comment] 2020-02-01 22:17
I did get a reply from the product team. It's long. I'll update the article next week.

**Comment by greg-lindsay** [comment] 2020-02-07 22:54
The reply I have still doesn't enable me to update this article. I have obtained a surface dock myself and I'm going to try and follow the docs myself. I've also pinged the product team for another reply in the meantime.

**Comment by greg-lindsay** [comment] 2020-02-08 01:22
See https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5756 for an update I'm going to use that issue as the main one and close this one.

**Closed by greg-lindsay** 2020-02-08 01:22 UTC
Labels: assigned-to-author
