### ISSUE TITLE
Win32 programs for Edge Kiosk Mode

### ISSUE THREAD

**Issue by Cirnohalo** [MicrosoftDocs/windows-itpro-docs#5144] opened 2019-10-10 01:33 UTC
How can I set up a Win32 program kiosk?
I have a Win32 application, which I have converted to a UWP application using the DesktopAppConverter for the purposes of running it in Assigned Access mode - the converted app works when running in non-assigned access mode - can be installed and functions properly.

However, when I set it up to be used as an assigned access application (by MDM) and log in with the account for assigned access, the screen keeps flashing (blue screen with loading dots, followed by a white screen, and repeat) for a period of time, resulting in the 0x80270254 error displayed.

**Comment by e0i** [comment] 2019-10-14 21:33
@Cirnohalo 

Your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Also note that the issues section of this repository is intended for documentation and content feedback.

For your  _support_ related questions or feedback, please visit, [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

Any documentation feedback is welcome.

Thanks.

**Comment by Cirnohalo** [comment] 2019-10-15 01:15
> @Cirnohalo
> 
> Your issue has been opened without being associated to a documentation topic.
> 
> Could you clarify which documentation you're referring to? A link would be helpful.
> 
> Also note that the issues section of this repository is intended for documentation and content feedback.
> 
> For your _support_ related questions or feedback, please visit, [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).
> 
> Any documentation feedback is welcome.
> 
> Thanks.

please refer to https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app   https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app

**Comment by VLG17** [comment] 2019-11-14 13:39
@Cirnohalo you can find your answer here:

https://stackoverflow.com/questions/41047093/how-to-launch-a-win32-application-to-run-like-a-windows-10-assigned-access-appx

https://stackoverflow.com/questions/40492539/windows-10-assigned-access-app-fails-to-start-due-to-not-registered-for-windows

"We got the confirmation that the Assigned Access mode doesn’t support Win32 apps yet, including Win32 apps converted with the Desktop Converter.

It is a known issue in RS1 which can pick Converted app in setting UI. We have a planned fix for this in RS2 but do not guarantee it will be delivered soon.

Please see this article for how to use Shell Launcher to config a kiosk device that runs a Classic Windows application as the user interface: https://technet.microsoft.com/en-us/itpro/windows/manage/set-up-a-kiosk-for-windows-10-for-desktop-editions"

**Comment by e0i** [comment] 2019-11-18 10:18
Hello @Cirnohalo,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Closed by e0i** 2019-11-18 10:18 UTC

**Comment by Cirnohalo** [comment] 2021-08-25 03:21
@VLG17  Hi, when will this problem be fixed?
