### ISSUE TITLE
How often do these policies refresh on the end-point?

### ISSUE THREAD

**Issue by clickbangdead** [MicrosoftDocs/windows-itpro-docs#6125] opened 2020-02-26 20:56 UTC
So, if something happens ot the registry entry that is created by an ADMX-backed policy, how often does it re-write hte entry? I created a policy, then after it deployed I went back and manually deleted the registry value it set in the HKCU\software\policies registry tree, and it never re-created them, even after several syncs. This means that these aren't really like Group Policy, they're more preferences, but that's not called out anywhere. I know there are separate policies that are considered "preferences" but the ones I'm setting are not, they are full blown policies written to the \software\policies key. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d3e3340-f744-af16-bfd2-3964d585e1e1
* Version Independent ID: dd074932-c941-ce52-29ce-1ec637fda651
* Content: [Understanding ADMX-backed policies - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/understanding-admx-backed-policies)
* Content Source: [windows/client-management/mdm/understanding-admx-backed-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/understanding-admx-backed-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment] 2020-03-02 02:45
@clickbangdead . If you manually entered gpupdate /force
In commnd prompt , it will recreate the policy registry keys. 

Also I seen the particular admx templates which concentrates only frequency of updating of group policy settings which will create or updates in registry

**Comment by e0i** [comment] 2020-03-10 00:31
@clickbangdead 

It seems that your question has been answered by the community and thus the issue is being marked as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Closed by e0i** 2020-03-10 00:31 UTC
Labels: client management
