### ISSUE TITLE
Hot to activate an Enterprise E3 N LTSC (installed from Enterprise ISO)

### ISSUE THREAD

**Issue by MrM40** [MicrosoftDocs/windows-itpro-docs#4890] opened 2019-09-07 07:18 UTC
I've not been able to find information about how to activate Enterprise E3, only how to upgrade and activate from Win Pro.
I don't have Volume License and no product key. I did try to use the KMS key but still not activate.
PC is joined AAD (just workgroup) and I login to windows with an ADD count

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses#feedback)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment] 2019-09-07 15:23
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-09-15 19:03
Hello @MrM40, I assumed you also checked the information available on the [Windows 10 Subscription Activation](https://docs.microsoft.com/windows/deployment/windows-10-subscription-activation) doc, right? How about checking the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or [Technet forums](https://social.technet.microsoft.com/Forums/home)? Here are interesting discussions that you can check (*where you can also participate*):

- [Activation via office 365 Windows 10 Enterprise E3 licence](https://social.technet.microsoft.com/Forums/en-US/7a61d5f6-24c0-49f4-b734-0b68de19216b/activation-via-office-365-windows-10-enterprise-e3-licence?forum=win10itprosetup)
- [KMS Activation Not working on Server 2019 or LTSC 2019](https://social.technet.microsoft.com/Forums/en-US/b5d4e330-41b6-48c9-a2ac-cf4813151234/kms-activation-not-working-on-server-2019-or-ltsc-2019?forum=ws2019) 
- [Windows 10 LTSC is getting error 0xc004F074 when trying to activate via KMS](https://social.technet.microsoft.com/Forums/en-US/7a84a919-967d-435c-babb-56d83a80ce4a/windows-10-ltsc-is-getting-error-0xc004f074-when-trying-to-activate-via-kms?forum=win10itprogeneral)

If you are still unsuccessful in finding the information or resolution, I suggest that you please open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. If your issue gets resolved, please share your solution here if it's something that can be incorporated into this documentation. 

Thanks for being part of the Microsoft Docs community!

**NOTE:** This site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review.

**Comment by MrM40** [comment] 2019-09-15 19:39
Yea I did read most of the linked documents.
It seems LTSC is not supported by the Office 365 Enterprise E3 subscription, although I haven't been able to get a final confirmation on this. Neither in any of the document I've read or from my my support ticket.

**Comment by jvsam** [comment] 2019-09-15 23:10
@MrM40 I've been looking at the forums as well and so far I haven't read anything definite. Did support confirm that it's not supported? Also, to clarify, is it [Office 365 E3](https://www.microsoft.com/en-us/microsoft-365/business/office-365-enterprise-e3-business-software?activetab=pivot%3aoverviewtab) or [Microsoft 365 E3](https://www.microsoft.com/en-us/licensing/product-licensing/microsoft-365-enterprise). The latter has the Windows Enterprise in the plan, not O365. Thanks for the clarification.

**Comment by MrM40** [comment] 2019-09-16 06:19
No, support didn’t confirm, but I might try again and push them a latter harder on the matter :-P
It sure is “Windows 10 Enterprise E3” you can get through the CSP program. I didn’t know there was two different cloud subscription programs, but I guess it has to be Microsoft 365 E3 then.

 

I’ll get back as soon as I get a final confirmation if LTSC is covered by the W10 Enterprise E3/E5 subscriptins.

**Comment by jvsam** [comment] 2019-09-21 18:42
Hello again @MrM40. I just want to ask if you've received any feedback from support? If so, did they confirm if LTSC is supported in the [Microsoft 365 E3](https://www.microsoft.com/en-us/licensing/product-licensing/microsoft-365-enterprise) plan? Please keep us posted here, thank you.

**Comment by MrM40** [comment] 2019-09-21 19:24
Unfortunately not and the case is now closed.
Even the MS support engineer doesn't seem to have access to someone at Microsoft who actually know sometime about this subject. They seem to use Google for must of their support work, and that will no give any answer. Been there already.
But my own conclusion is it is not covered by the MS 365 E3 subscription. 
In many way it makes sense, it's rather obvious that Microsoft want to limit the use of LTSC as much as possible, but on the other hand, MS also want to push as much products to O365 (MS 365) as possible to embellish their "cloud" turnover, so there are contradictory interesset (sorry, went a little off topic there).

**Comment by jvsam** [comment] 2019-09-22 15:20
Hello @MrM40, sorry to hear that, I wish I could help. Since there are no changes/updates to suggest to this documentation, I will now close this issue. However, you can reopen it at any time, e.g. if you have *confirmed* information that can be incorporated to this doc. Or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this or other documentation.

Also, I do encourage you to submit the LTSC suggestion on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). The Microsoft engineering team uses UserVoice feedback to learn what users are asking for or what they want to improve. 

Thank you again!

**Comment by jvsam** [comment] 2019-09-22 15:21
@officedocsbot close

**Closed by jvsam** 2019-09-22 15:21 UTC
