### ISSUE TITLE
Microsoft PIN Reset Service Integration website Throws error

### ISSUE THREAD

**Issue by amanjee** [MicrosoftDocs/windows-itpro-docs#2820] opened 2019-03-03 05:35 UTC
Microsoft PIN Reset Service Integration website throws the error "You do not have permission to view this directory or page." after providing AAD Authorization. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a146880-235b-a69c-3e9d-a3fa56a25389
* Version Independent ID: c2c226b4-17ef-8888-9e1b-e20cf3273c3a
* Content: [Windows Hello for Business Features](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-features#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-features.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by hashtag2949** [comment] 2019-03-04 17:28
API blocked by Panda security

**Comment by bally-singh** [comment] 2019-03-10 19:44
Same error for me - Global Admin. Sign-ins log:

Status: Interrupted
Sign-in error code:  65001
Failure reason: Application X doesn't have permission to access application Y or the permission has been revoked. Or The user or administrator has not consented to use the application with ID X. Send an interactive authorization request for this user and resource. Or The user or administrator has not consented to use the application with ID X. Send an authorization request to your tenant admin to act on behalf of the App : Y for Resource : Z.

**Comment by mapalko** [comment] 2019-03-14 02:57
@amanjee and @bally-singh we are currently investigating this issue. Can you confirm that you are still blocked from enabling the service?

**Comment by bally-singh** [comment] 2019-03-15 09:40
Hi mapalko,

Still an issue for me:

Once clicking on "Accept to give consent for the PIN reset service to access your account", I get the error message:
"You do not have permission to view this directory or page."

**Comment by mapalko** [comment] 2019-03-15 17:23
Can you confirm under the Azure Enterprise Applications dashboard that Microsoft PIN Reset Service Production does not show up under the status Enabled services. If they are not showing up can you attempt to add them through the portal instead of the link in the documentation. See: https://blogs.technet.microsoft.com/matt_hinsons_manageability_blog/2017/07/26/intune-passcode-reset-microsoft-pin-reset-service/

**Comment by mapalko** [comment] 2019-03-21 21:08
@bally-singh and @amanjee have you been able to test the steps in the documentation listed in my previous comment?

**Comment by bally-singh** [comment] 2019-03-22 13:52
Hi Mapalko.

Sorry in the delay! This is working for me. I am on a hybrid AAD/AD and users are able to reset the PIN on their Windows 10 device when connected to the corporate network. However, in my naivety I thought this would be something available to do via the cloud by an IT administrator.

Thanks for all your support - much appreciated 👍

**Comment by e0i** [comment] 2019-05-09 15:08
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-09 15:09
@amanjee 

The issue is being marked as resolved since it seems that your question has been answered by _mapalko_.

Note that the issues section of this repository is intended for documentation and content issues only.

Should you have any further issues similar to this one, please consider opening a product support ticket here: [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Any feedback directly regarding the documentation itself is welcome.

Thank you.

**Comment by e0i** [comment] 2019-05-09 15:09
@officedocsbot close

**Closed by e0i** 2019-05-09 15:09 UTC
Labels: windows hello for business
