### ISSUE TITLE
Event Type information would be great

### ISSUE THREAD

**Issue by Jonathan0Doe** [MicrosoftDocs/windows-itpro-docs#1727] opened 2018-10-02 10:47 UTC
This is a really nice overview of events associated with ipsec. It would be great, if the event type (like success or failure) information would be added to the event ids.

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50638434-1963-d8ea-5fad-0dcfbe67946d
* Version Independent ID: 8aefb55f-e95e-e80f-3a66-e3bd8dddbfc9
* Content: [Audit IPsec Main Mode (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-ipsec-main-mode)
* Content Source: [windows/security/threat-protection/auditing/audit-ipsec-main-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/audit-ipsec-main-mode.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by shortpatti** [comment] 2018-10-02 15:11
closing. duplicate of [1728](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1728)

**Closed by shortpatti** 2018-10-02 15:11 UTC
