### ISSUE TITLE
Advanced Hunting query incorrect.

### ISSUE THREAD

**Issue by akisctx** [MicrosoftDocs/windows-itpro-docs#7910] opened 2020-07-21 10:52 UTC
The Advanced Hunting query on this page does not work.

It should be fixed in the following places:

- Change MiscEvents to DeviceEvents
- Change EventTime to Timestamp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a868903-95b1-288c-72d2-be936171044a
* Version Independent ID: 1456cb15-b4ec-2c0d-958e-340766c27788
* Content: [Query Application Control events with Advanced Hunting (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/querying-application-control-events-centrally-using-advanced-hunting)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/querying-application-control-events-centrally-using-advanced-hunting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/querying-application-control-events-centrally-using-advanced-hunting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by erroltuparker** [comment] 2020-08-18 22:04
The new query should be as per below

DeviceEvents
| where Timestamp > ago(7d) and
ActionType startswith "AppControl"
| summarize Machines=dcount(DeviceName) by ActionType
| order by Machines desc

Please merge https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8095 into this

**Comment by e0i** [comment] 2020-08-26 10:09
Duplicate of #8095

**Closed by e0i** 2020-08-26 10:09 UTC
Labels: microsoft defender application control
