### ISSUE TITLE
Error Malformed line 1 in source list /etc/apt/sources.list.d/microsoft-prod.list (type)

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/windows-itpro-docs#9019] opened 2021-01-26 14:27 UTC
Same problem as 
https://github.com/MicrosoftDocs/azure-docs/issues/59910

Running Ubuntu 20.4 LTS and trying to follow the guide. It's not possible to follow along with the guide as one gets

:~$ sudo apt-get install gpg
E: Malformed line 1 in source list /etc/apt/sources.list.d/microsoft-prod.list (type)
E: The list of sources could not be read.
E: Malformed line 1 in source list /etc/apt/sources.list.d/microsoft-prod.list (type)
E: The list of sources could not be read.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2021-01-26 22:44
@konstruktoid : Maybe you would like to take a look at this issue?

**Comment by konstruktoid** [comment] 2021-01-27 00:12
Can't reproduce.
But that page is getting a rewrite: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8960?

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
~$ curl -o microsoft.list https://packages.microsoft.com/config/ubuntu/20.04/insiders-fast.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    97  100    97    0     0    167      0 --:--:-- --:--:-- --:--:--   167
~$ sudo mv ./microsoft.list /etc/apt/sources.list.d/microsoft-insider.list
~$ curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
vagrant@focal:~$ sudo apt-get -y update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease                           
Get:3 https://packages.microsoft.com/ubuntu/20.04/prod insiders-fast InRelease [7,416 B]
Get:4 https://packages.microsoft.com/ubuntu/20.04/prod insiders-fast/main amd64 Packages [3,946 B]
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 3,946 B in 1s (4,211 B/s)
Reading package lists... Done
~$ sudo apt-get install gpg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gpg is already the newest version (2.2.19-3ubuntu2).
gpg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
~$ sudo apt-get -y upgrade
[...]
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for systemd (245.4-4ubuntu3.4) ...
Processing triggers for man-db (2.9.1-1) ...
~$
```

**Comment by illfated** [comment] 2021-01-27 00:40
Very good. We can have more feedback or consider closing this ticket when the PR is merged and the page is updated.

**Closed** 2021-12-11 01:02 UTC
Labels: question, defender for endpoint

**Comment by Lovygoogle** [comment] 2021-12-11 01:31
cd ..
rm -rf <repo>
git clone <repo>
cd <repo>
gh pr checkout 19
 حذف مستودعك  ، واستنساخه جديدًا ، ثم سحب طلب السحب مرةاخره
