### ISSUE TITLE
Missing closing tag

### ISSUE THREAD

**Issue by MaasvandeHaar** [MicrosoftDocs/windows-itpro-docs#3846] opened 2019-05-29 13:36 UTC
For Windows 10.0.17763 it seems an extra line should be added with the closing tag:

&lt;/appv:AppConnectionGroup&gt;

Also all text of &lt;appv:AppConnectionGroup bla bla &gt; should be on one line.
I'm running in errors: is it possible to use Application Connection Groups with Window10 at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef2cfd2-e308-92b9-9ff6-af0c6afd82c2
* Version Independent ID: c48302dc-532d-b9da-3083-5ecc8cb93418
* Content: [About the connection group file (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-connection-group-file#feedback)
* Content Source: [windows/application-management/app-v/appv-connection-group-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-connection-group-file.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by martyav** [comment] 2019-05-29 15:53
While the file should include the closing tag, I think having the attributes broken up by newlines is fine, as the parser will normalize them into standard spaces.

**Comment by e0i** [comment] 2019-05-30 14:14
@officedocsbot assign @e0i

**Comment by illfated** [comment] 2019-05-30 23:42
This format seems to work well in Notepad++ when Language is set to XML:
```xml
<?xml version="1.0" encoding="UTF-16"?>
<appv:AppConnectionGroup
  xmlns="http://schemas.microsoft.com/appv/2014/virtualapplicationconnectiongroup"
  xmlns:appv="http://schemas.microsoft.com/appv/2014/virtualapplicationconnectiongroup"
    AppConnectionGroupId="61BE9B14-D2B4-41CE-A6E3-A1B658DE7000"
    VersionId="E6B6AA57-F2A7-49C9-ADF8-F2B5B3C8A42F"
    Priority="0"
    DisplayName="Sample Connection Group">
    <appv:Packages>
      <appv:Package
        PackageId="1DC709C8-309F-4AB4-BD47-F75926D04276"
        VersionId="*"
        IsOptional=”true”
      />
      <appv:Package
        PackageId="04220DCA-EE77-42BE-A9F5-96FD8E8593F2"
        VersionId="E15EFFE9-043D-4C01-BC52-AD2BD1E8BAFA"
        IsOptional=”false”
      />
    </appv:Packages>
</appv:AppConnectionGroup>
```

**Comment by e0i** [comment] 2019-06-27 13:18
@MaasvandeHaar It seems that moving further with content updates is not necessary as XML format is already valid. The issue is thus being closed.

Feel free to re-open this issue should there be anything else that we might have missed.

Thank you for providing feedback.

**Comment by e0i** [comment] 2019-06-27 13:18
@officedocsbot close

**Closed by e0i** 2019-06-27 13:18 UTC
