### ISSUE TITLE
Broken links to scripts

### ISSUE THREAD

**Issue by klishb** [MicrosoftDocs/windows-itpro-docs#9216] opened 2021-02-28 03:49 UTC
[Enter feedback here]
Both of the links to the reset scripts do not work any more:

https://gallery.technet.microsoft.com/scriptcenter/Reset-WindowsUpdateps1-e0c5eb78
and 
https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment] 2021-02-28 08:51
Thank you for reporting the issue, but it has already been reported several times and will be managed in the other ticket page (#9104).

Duplicate of the following issue tickets:
- #9104 ([**Windows Update - Dead links**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9104)) (open)
- #9129 ([**Script link not working**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9129)) (closed)
- #9153 ([**Two links to the automation scripts at the top of the document are broken**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9153)) (closed)
- #9195 ([**Broken link**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9195)) (closed)

**Comment by illfated** [comment] 2021-02-28 08:53
For your information (FYI): the MS Docs team will handle the issue by creating new pages for those retired TechNet Gallery pages.

**Comment by nam31** [comment] 2021-03-22 09:21
Hi @klishb as @illfated pointed out  

> Thank you for reporting the issue, but it has already been reported several times and will be managed in the open ticket page (#9104).
> 
> Duplicate of the following issue tickets:
> 
> * #9104 ([**Windows Update - Dead links**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9104)) (open)
> * #9129 ([**Script link not working**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9129)) (closed)
> * #9153 ([**Two links to the automation scripts at the top of the document are broken**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9153)) (closed)
> * #9195 ([**Broken link**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9195)) (closed)

Please refer to issue #9104 for a resolution to this problem.
Thank you

**Closed by nam31** 2021-03-22 09:21 UTC
Labels: deployment
