### ISSUE TITLE
Policy Settings are Being Ignored

### ISSUE THREAD

**Issue by FormulaAT** [MicrosoftDocs/windows-itpro-docs#1193] opened 2018-07-02 19:17 UTC
The "No auto-restart with logged on users for scheduled automatic updates installations" setting seems to be ignored. We have our Configure Automatic Updates set to option 4, as detailed above, but logged in users still experience sudden restarts with no notice at the scheduled time. Verified versions experiencing this issue are 1709 and 1803. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment] 2018-07-06 18:28
Hi @FormulaAT did you check that the policy actually applies on the device in question (for the user in question) ?

**Comment by FormulaAT** [comment] 2018-07-06 20:34
Yes, both by using GPResult and by viewing the Applied Policies within the Update Settings on the computers. The No Automatic Reboot with Logged on Users policy is applied, but we still experience sudden restarts with no notice.

**Comment by DaniHalfin** [comment] 2018-07-06 20:45
I will ask someone to look into this, but it might be better for you to reach out to support, as generally I wouldn't expect this behavior.

**Comment by DaniHalfin** [comment] 2018-09-26 22:47
@shortpatti - can this be reassigned to @jaimeo to confirm closure?
I believe this isn't expected behavior, and so should be looked at with the help of MS support.

**Comment by FormulaAT** [comment] 2018-10-11 15:59
Here's a [TechNet thread](https://social.technet.microsoft.com/Forums/en-US/31574929-70b8-4c08-a150-88a81a43ee99/windows-10-ignores-wsus-gpo-no-autorestart-with-logged-on-users-for-scheduled-automatic-updates
) with others reporting the issue. What's the correct way to engage support on this?

**Comment by jaimeo** [comment] 2018-10-11 16:59
I've brought this thread to the attention of relevant PMs, but the way to engage support is to visit support.microsoft.com.

**Comment by MCPWiz** [comment] 2019-05-22 12:35
As far as I can understand the text above, there are 3 times when a restart can still happen dispite No restart with logged on user:

1 No auto-restart with logged on users for scheduled automatic updates installations prevents automatic restart when a user is signed in. If a user schedules the restart in the update notification, the device will restart at the time the user specifies even if a user is signed in at the time. This policy only applies when Configure Automatic Updates is set to option 4-Auto download and schedule the install.

2 
Note

When using Remote Desktop Protocol connections, only active RDP sessions are considered as logged on users. Devices that do not have locally logged on users, or active RDP sessions, will be restarted.

3
You can also use Registry, to prevent automatic restarts when a user is signed in. Under HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate\AU, set AuOptions to 4 and enable NoAutoRebootWithLoggedOnUsers. As with Group Policy, if a user schedules the restart in the update notification, it will override this setting.

**Comment by jvsam** [comment] 2019-06-07 02:35
@officedocsbot assign @jvsam

**Comment by nam31** [comment] 2020-10-09 15:43
@FormulaAT Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.

**Closed** 2020-11-25 14:36 UTC
Labels: deployment, update
