### ISSUE TITLE
White Glove Hybrid Azure AD Join only when not on the Domain network?

### ISSUE THREAD

**Issue by JeroenDijkman** [MicrosoftDocs/windows-itpro-docs#5589] opened 2019-12-03 13:29 UTC
When we perform the White Glove connected to our Domain network with a Hybrid Azure AD join the process finishes the domain join during white glove. It does not install the other apps targeted and it does not end up with the "reseal" option.
Is it needed for White Glove (technician flow) with Hybrid Azure Ad join to NOT be connected to the Domain network?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#feedback)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by snok87** [comment] 2019-12-05 15:06
I got the same issue. It start provisioning, rename computer, join local domain, reboot and finish, without any Reseal option or red/green screen.
I got a user assigned to that computer, everything is working well when normal hybrid ad join enrollment.

**Comment by mypil** [comment] 2019-12-13 23:57
@JeroenDijkman @snok87 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Closed by mypil** 2019-12-13 23:57 UTC

**Comment by snok87** [comment] 2019-12-16 10:34
I have tried a NON-hybrid White globe enrollment and its working well. I already got a support ticket with Microsoft for the last 2 weeks. We havent found the issue yet. The issue is just with Hybrid enrollments.

**Comment by illfated** [comment] 2019-12-16 22:30
@snok87 : Thank you for reporting back and telling us about your progress. Looking forward to any solution you will get and if it would be useful in the documentation.

**Comment by MrPRSmith** [comment] 2020-01-09 19:40
@JeroenDijkman @snok87 I'm seeing the same behavior with the White Glove and Hybrid Azure AD join scenario using a fully patched 1909 system - I'm curious if would you be able to share the outcome of your support ticket?

**Comment by JeroenDijkman** [comment] 2020-01-10 10:06
> @JeroenDijkman @snok87 I'm seeing the same behavior with the White Glove and Hybrid Azure AD join scenario using a fully patched 1909 system - I'm curious if would you be able to share the outcome of your support ticket?

@MrPRSmith No resolution from Microsoft yet. They actually closed my ticket because I was away for one week! Currently I have re-opened the ticket but nothing new yet. The support takes forever to be honest.

**Comment by MrPRSmith** [comment] 2020-01-10 11:26
> > @JeroenDijkman @snok87 I'm seeing the same behavior with the White Glove and Hybrid Azure AD join scenario using a fully patched 1909 system - I'm curious if would you be able to share the outcome of your support ticket?
> 
> @MrPRSmith No resolution from Microsoft yet. They actually closed my ticket because I was away for one week! Currently I have re-opened the ticket but nothing new yet. The support takes forever to be honest.

@JeroenDijkman thanks for letting me know, guess I'll have to log a ticket myself when I get some time!

**Comment by illfated** [comment] 2020-01-10 13:29
Yes, definitely log a new ticket for your individual issue. Microsoft won't know how widespread that issue is until someone doing the statistics reports from all the support centres.

**Comment by snok87** [comment] 2020-02-19 08:11
Is still happening, the lass thing i'm working on is TPM attestation. It seems that is not working well in OOBE.
If i start a new (or restored) device and execute tpm.msc, it says that tpm is not ready yet and then i get "EK cert not found" log message.
I tried to upgrade TPM firmware to lastest, clear TPM, forced TPM scheduled tasks, but nothing is working.

If i execute TPM scheduled tasks after login with domain user, it works perfectly and download the cert and TPM is seen as Ready and attestation too, but this is not working before White Glove procedure.

**Comment by illfated** [comment] 2020-02-19 21:20
Wish I knew more about this to be able to give you any answers about what could be going on there. To me, it sounds like what you are trying to do is not a supported solution, but I am just guessing blindly in this case. Have you tried posting this issue in any of the other microsoft.com forums, like techcommunity / social / answers and so on?

**Comment by snok87** [comment] 2020-02-20 10:57
I have a case with Microsoft since December 2019 :)

**Comment by illfated** [comment] 2020-02-20 21:17
Very well, I sincerely hope you will get the answers you are looking for from them. Keeping my fingers crossed for you to be able to solve your issue.
