### ISSUE TITLE
Please correct the description of "AllowScanningNetworkFiles"

### ISSUE THREAD

**Issue by narkuroki** [MicrosoftDocs/windows-itpro-docs#11313] opened 2023-02-02 04:19 UTC
[Enter feedback here]
Please correct the following statements.
━━━━━━━━━━━━━━━━━━━━
This policy setting allows you to configure scanning for network files. It is recommended that you do not enable this setting.
・If you enable this setting, network files will be scanned.
・If you disable or do not configure this setting, network files will not be scanned.
━━━━━━━━━━━━━━━━━━━━

There are two parts that need to be fixed:

No1.
Current statement: It is recommended that you do not enable this setting.
Correct: It is recommended to enable this setting.
Why it needs to be fixed: We have checked internally and confirmed that enabling is now recommended.

No2.
Current description: If you disable or do not configure this setting, network files will not be scanned.
Correct:  If you do not configure this setting, network files will be scanned.
Why it needs to be fixed: I have checked internally and confirmed that it will take effect if not configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Defender Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#allowscanningnetworkfiles)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment] 2023-02-02 18:14
Thanks for submitting this issue @narkuroki. Another issue was filed for the same issue, so I'm closing this issue as a duplicate of https://github.com/MicrosoftDocs/windows-itpro-docs/issues/11315. These docs are generated automatically, and the policy description comes from the GPO, so I recommend submitting feedback via the Feedback Hub app to correct the strings in the ADMX template for the policy, which would in turn get the docs updated correctly as well.

**Closed by vinaypamnani-msft** 2023-02-02 18:14 UTC
Labels: mdm

**Comment by narkuroki** [comment] 2023-02-03 00:29
@vinaypamnani-msft 
thank you for your reply.
I interpreted that the document cannot be modified unless the string on the GPO side is modified.
I would like to request a GPO fix through the Feedback Hub app, can you tell me where I can access it?

**Comment by aczechowski** [comment] 2023-02-03 01:17
@narkuroki For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.
