### ISSUE TITLE
Hybrid Azure AD Join + MFA enabled user issue with W10 subscription activation

### ISSUE THREAD

**Issue by anarii** [MicrosoftDocs/windows-itpro-docs#4093] opened 2019-06-18 20:34 UTC
This is a huge issue currently with MFA usage growing all the time and when trying to activate W10 Enterprise subscription licenses.

"An issue has been identified with Hybrid Azure AD joined devices that have enabled multi-factor authentication (MFA). If a user signs into a device using their Active Directory account and MFA is enabled, the device will not successfully upgrade to their Windows Enterprise subscription. To resolve this issue, the user must either sign in with an Azure Active Directory account, or you must disable MFA for this user during the 30-day polling period and renewal."

Please clarify in the documentation:

1. Is there an ETA for this to issue to be fixed?
2. The suggested solutions:

If the device is domain joined (and Hybrid Azure AD Joined) and the user is using AD (AAD synced) credentials to logon, how is it possible that the only workaround seems to be to logon with cloud only Azure AD account? This isn't feasible in a lot of environments.

Disabling MFA for a lot of users is obviously also not feasible for security reasons only to get the user's Windows 10 subscription activated.

Is there other ways to workaround the issue until it gets fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44969189-979f-f80a-3f6c-24826e496c78
* Version Independent ID: b3cda3a2-e399-e652-918c-c3d9582acaf4
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment] 2019-06-18 20:39
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-06-19 06:18
Hi @anarii we apologize for the inconvenience. We would love to help you with this issue, however, this Github site is intended for product documentation so I would recommend that you contact support and open a [service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant instead to get an update on the ETA and inquire if there are other workarounds. For sure, once the issue is resolved or if there is already a final resolution, it would reflect on this documentation. 

You can definitely help us with this as well. If you decide to contact Windows 10 support, please keep us posted here on the resolution or information that can be called out in the docs. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Looking forward to hearing from you!

**Comment by jvsam** [comment] 2019-06-21 10:43
Hi @anarii just following up if you were you able to contact Windows 10 support for assistance? If so, we're very interested to know if you were able to resolve your issues. Again, if the resolution or information is something that can be incorporated to the existing documentation, please keep us informed and we will be happy to assist you in updating the contents of this document. Thank you.

**Comment by jvsam** [comment] 2019-06-23 03:45
Hi @anarii, hope all is well. We haven't received any response from you, so for now, we will close this issue. However, feel free to re-open if you have suggestions to improve the quality of this documentation and we will submit them for review. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-06-23 03:45
@officedocsbot close

**Closed by jvsam** 2019-06-23 03:45 UTC
