### ISSUE TITLE
Install Apps on the HoloLens documentation contains multiple dead links

### ISSUE THREAD

**Issue by adrianimajion** [MicrosoftDocs/windows-itpro-docs#3608] opened 2019-05-09 19:28 UTC
This page: https://docs.microsoft.com/en-us/hololens/hololens-install-apps

As well as presumably a number of other docs pages include a lot of hyperlinks to pages like developer.microsoft.com/en-us/mixed-reality#setting_up_hololens_to_use_windows_device_portal 

All of those pages now just redirect to https://developer.microsoft.com/en-us/mixed-reality, which is just a landing page. This really reduces the value of the documentation since a *lot* of important context was hosted outside of docs.microsoft - like the link above that previously explained the steps to conduct within Settings in the HoloLens to enable device portal access and developer mode. Every link under the "Use the Windows Device Portal to install apps on HoloLens" header is broken currently.

**Comment by e0i** [comment] 2019-05-10 21:50
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-27 20:49
@adrianimajion Thank you for providing feedback. The issue is under investigation.

**Comment by scooley** [comment] 2020-05-11 17:11
+ @evmill 

Thanks for pointing this out, @adrianimajion, we have some work planned to revamp the device portal docs in the near(ish) future.  Your feedback helps us prioritize the work.

Stay tuned!

**Comment by evmill** [comment] 2020-05-11 17:21
@scooley While this issue is over a year old now it's still relevant in a way. These links now exist in the "Manage custom apps for HoloLens" page. Those links DO work correctly on that page. However that page is a little stale. It's on our radar for updating. 
https://docs.microsoft.com/hololens/holographic-custom-apps

**Comment by e0i** [comment] 2020-07-09 12:46
The pages seem to have been fixed. Closing.

**Closed by e0i** 2020-07-09 12:46 UTC
Labels: assigned-to-author, devices
