### ISSUE TITLE
What does this statement means - "The designed Windows for Business configuration has you give the Key Admins "

### ISSUE THREAD

**Issue by rishtech** [MicrosoftDocs/windows-itpro-docs#8071] opened 2020-08-15 08:52 UTC
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Passwordless Strategy - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment] 2020-08-15 12:03
@rishtech . From my knowledge based,  passwordless configuration will be configured by the 
organization systm admin. if device is joined in azure.
 
For standard device, that is not joined to azure, hence the users will configure as their their needs, hence there is no interaction between users and system administrator

**Comment by e0i** [comment] 2020-08-25 23:25
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Thank you.

**Comment by MaratMussabekov** [comment] 2020-08-28 11:11
Dear @e0i , @raju2529.
I believe that @rishtech is telling about article https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment as the mentioned wording is not presented in the Password Strategy article.

"The designed Windows for Business configuration has you give the Key Admins (or KeyCredential Admins when using domain controllers prior to Windows Server 2016) group read and write permissions to the msDS-KeyCredentialsLink attribute." means that Key Admins group got the permission to change msDS-KeyCredentialsLink attribute in the AD during the configuration of Windows Hello for Business. I think that the wording should be changed as the correct one incorrect and confusing.
I will create a PR.

Thank you

**Comment by RAJU2529** [comment] 2020-08-28 11:53
Its beyond my knowledge

**Comment by learnconceptswork** [comment] 2020-08-29 08:48
@MaratMussabekov , Thanks for understand the exact issue. 
@e0i , First of all I would like to understand, what do you mean by it seems, is there any review process for feedback closure, or it is an autonomous function. 
FYI, the question and answer is nowhere related.

**Comment by rishtech** [comment] 2020-08-29 09:24
@MaratMussabekov , Thanks for understand the exact issue.
@e0i , please read @MaratMussabekov response.

**Comment by illfated** [comment] 2020-08-29 12:53
I would also like to note that the phrasing in the first sentence
> The designed Windows for Business configuration has you give the Key Admins

uses poorly phrased English grammar (I am pretty certain that @JohanFreelancer9 will agree), as if the phrasing has been translated word-for-word from a different language.

I would have suggested a better syntax right now, but I need to consider the implications for a while.

**Closed** 2020-09-11 16:58 UTC
Labels: hello-for-business, in progress
