### ISSUE TITLE
Mistranslation

### ISSUE THREAD

**Issue by ykore52** [MicrosoftDocs/windows-itpro-docs#8257] opened 2020-09-10 00:26 UTC
I found following mistranslation in Japanese.

* AD ( Active Directory )  -> 広告 ( advertisement )

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [グループ ポリシーを使用した Windows 10 デバイスの自動登録 - Windows Client Management](https://docs.microsoft.com/ja-jp/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#feedback)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2020-09-10 01:28
@ykore52 : Thank you for reporting that mistranslation. I notice that the kanji combination 広告 appears 8 times on the referenced page. Is the mistranslation present in all 8 places, or only in some of them?

@TinaMcN : This looks like a free-text translation issue not related to code or command-line examples, so it will not be practical to enclose the phrase "Active Directory" in MarkDown backticks on the English page.

**Comment by ykore52** [comment] 2020-09-10 02:27
@illfated Yes. "広告" appears in all 8 places.

**Comment by illfated** [comment] 2020-09-11 03:41
The machine translation has likely had an issue with uppercase/lowercase indifference, reading "AD" as "ad" instead of initials. Hoping it can be solved.

**Comment by TinaMcN** [comment] 2021-06-15 23:38
@ykore52 this article is now translated by a human. Can you please verify if the issue is fixed and close this issue if it looks ok to you? Thanks again for reporting it.

**Closed** 2021-09-24 15:35 UTC
Labels: mdm, localization, loc-bug
