### ISSUE TITLE
Table 4. Surface Book 3 with Quadro RTX 3000 SKUs

### ISSUE THREAD

**Issue by aarondmarr** [MicrosoftDocs/windows-itpro-docs#6666] opened 2020-05-07 18:55 UTC
Will there be a SKU with 2 TB of storage? I have a ThinkPad P71 w/ P5000 I'd like to replace with a Quadro Surface Book, but I need 2 TB of storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d978d59-5616-b09e-103a-711379a814c2
* Version Independent ID: c4685ca4-2eda-3834-3ddf-a613c4b2d789
* Content: [Surface Book 3 GPU technical overview - Surface](https://docs.microsoft.com/en-us/surface/surface-book-quadro#feedback)
* Content Source: [devices/surface/surface-book-quadro.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-book-quadro.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **v-jokai**

**Comment by RAJU2529** [comment] 2020-05-12 14:22
@aarondmarr .  yes you can get,  but you must configure hardware items before purchasing . 2TB storage is available only 15inch only in USA.
for more information visit below site
**https://www.microsoft.com/en-us/store/configure/Surface-Book-3/8XBW9G3Z71F1?crosssellid=fbt-p2c&selectedColor=&preview=&previewModes=**

**Comment by aarondmarr** [comment] 2020-05-12 18:09
Hello!
        Thank you, but I don't see where I can configure a Surface Book 3
with the Quadro RTX 3000 graphics card with 2TB of storage. Could you
point me in the right direction?

Best regards -
Aaron Marr

**Comment by RAJU2529** [comment] 2020-05-12 18:25
@aarondmarr  go to below site 
**https://www.microsoft.com/en-us/p/surface-book-3/8xbw9g3z71f1?activetab=pivot:techspecstab**

with Nvidia 1660Ti, not  RTX 3000  series, so before purchasing verify all technical specifications

**Comment by e0i** [comment] 2020-07-06 17:04
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-07-06 17:04 UTC
Labels: devices
