### ISSUE TITLE
Are the block rules implemeted for Azure PaaS?

### ISSUE THREAD

**Issue by dave-au** [MicrosoftDocs/windows-itpro-docs#5719] opened 2019-12-19 02:03 UTC
Are these recommended implemented by Microsoft within the Azure PaaS environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d71055e-2b14-227b-0107-c8f150194d5b
* Version Independent ID: 0eab18a0-7e8f-05eb-b47f-e6913682d8e8
* Content: [Microsoft recommended block rules (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment] 2020-01-28 15:07
I think these rules for standardalone computer

**Comment by RAJU2529** [comment] 2020-01-28 15:08
I think these rules for standardalone computer

**Comment by e0i** [comment] 2020-05-09 20:18
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-05-09 20:18 UTC
Labels: windows defender application control
