### ISSUE TITLE
4688 Audit Failed

### ISSUE THREAD

**Issue by ThouSandThorChang** [MicrosoftDocs/windows-itpro-docs#10954] opened 2022-10-23 06:56 UTC
[在此处输入反馈]
Last update to Windows 11，only set Audit Process Creation success，couldn‘t get 4688 log

---
#### 文档详细信息

⚠ *请勿编辑此部分。 learn.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5eca37ef-510b-52ec-ed07-2fb4a2d307dc
* Version Independent ID: c4977b85-a93a-119d-3010-b6148c3421f0
* Content: [4688(S) 已新建进程。 (Windows 10) - Windows security](https://learn.microsoft.com/zh-cn/windows/security/threat-protection/auditing/event-4688)
* Content Source: [windows/security/threat-protection/auditing/event-4688.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/threat-protection/auditing/event-4688.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by ErrorRaffyline0** [comment] 2022-10-23 10:10
I back this up, I couldn't get this to work. 
"Include command line in process creation events" is missing under Administrative templates - System - Audit Process Creation in the group policy editor.
Even when migrating Win10 to Win11 (which allows the group policy to remain (albeit in a reset state)), enabling this policy will not enable the auditing of process creation events.

**Comment by RobMulder** [comment] 2022-10-23 10:54
Same here!
https://learn.microsoft.com/en-us/answers/questions/1046836/no-more-events-4688-in-eventlog-anymore.html

**Comment by ThouSandThorChang** [comment] 2022-10-24 06:18
> I back this up, I couldn't get this to work. "Include command line in process creation events" is missing under Administrative templates - System - Audit Process Creation in the group policy editor. Even when migrating Win10 to Win11 (which allows the group policy to remain (albeit in a reset state)), enabling this policy will not enable the auditing of process creation events.

Without the newest Win11 version，you could set the reg value to get the cmdline in 4688 log。

RegOpenKeyEx(HKEY_LOCAL_MACHINE, GPO_INCLUDE_CMDLINE_KEY, NULL, KEY_ALL_ACCESS, &hKey);
key：Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit
value：ProcessCreationIncludeCmdLine_Enabled   （DWORD）1

**Comment by ThouSandThorChang** [comment] 2022-10-24 06:22
> 我支持这个，我无法让它工作。 在组策略编辑器中的管理模板 - 系统 - 审核进程创建下缺少“在进程创建事件中包含命令行”。 即使将 Win10 迁移到 Win11（允许组策略保留（尽管处于重置状态）），启用此策略也不会启用进程创建事件的审核。

sometimes，only set gpedit in win11，could not success，you should set the reg value directly

**Comment by ThouSandThorChang** [comment] 2022-10-24 06:23
> I back this up, I couldn't get this to work. "Include command line in process creation events" is missing under Administrative templates - System - Audit Process Creation in the group policy editor. Even when migrating Win10 to Win11 (which allows the group policy to remain (albeit in a reset state)), enabling this policy will not enable the auditing of process creation events.

sometimes，only set gpedit in win11，could not success，you should set the reg value directly

**Comment by ThouSandThorChang** [comment] 2022-10-24 06:24
> Same here! https://learn.microsoft.com/en-us/answers/questions/1046836/no-more-events-4688-in-eventlog-anymore.html

Thank U very much！Hope resolve as soon.

**Comment by msconfig87** [comment] 2022-10-24 09:21
this is urgent. Our devs in the company complain oh high CPU use about 10% because event 1108 now appears instead of 4688 in some loop 4 times a second. We have auditing turned on as a company policy.
Event 1108 is: "The event logging service encountered an error while processing an incoming event published from Microsoft-Windows-Security-Auditing."
Google tells me event 1108 indicates a defective or incorrect event before 1108.

xml view:
`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Microsoft-Windows-Eventlog" Guid="{fc65ddd8-d6ef-4962-83d5-6e5cfe9ce148}"/>
		<EventID>1108</EventID>
		<Version>0</Version>
		<Level>2</Level>
		<Task>101</Task>
		<Opcode>0</Opcode>
		<Keywords>0x4020000000000000</Keywords>
		<TimeCreated SystemTime="2022-10-24T09:19:01.5396312Z"/>
		<EventRecordID>827115</EventRecordID>
		<Correlation/>
		<Execution ProcessID="3320" ThreadID="4780"/>
		<Channel>Security</Channel>
		<Computer>ZUEN62324</Computer>
		<Security/>
	</System>
	<UserData>
		<EventProcessingFailure xmlns="http://manifests.microsoft.com/win/2004/08/windows/eventlog">
			<ErrorCode>15003</ErrorCode>
			<EventID>4688</EventID>
			<PublisherID>Microsoft-Windows-Security-Auditing</PublisherID>
		</EventProcessingFailure>
	</UserData>
</Event>`

**Comment by ErrorRaffyline0** [comment] 2022-10-25 18:38
> this is urgent. Our devs in the company complain oh high CPU use about 10% because event 1108 now appears instead of 4688 in some loop 4 times a second. We have auditing turned on as a company policy.
> Event 1108 is: "The event logging service encountered an error while processing an incoming event published from Microsoft-Windows-Security-Auditing."
> Google tells me event 1108 indicates a defective or incorrect event before 1108.

Interesting, Microsoft support told me my event 1108 errors were due to an incorrect configuration of Windows Hello (which I had never set up). Then again that's probably because event 1108 is logged in many different scenarios, and the support agent probably just found that one case.

It also lines up because I only started getting  1108 event errors after event 4688 stopped being logged.

**Comment by ErrorRaffyline0** [comment] 2022-11-07 18:55
For clarity, this issue is caused by #10956. #10955 discusses the omission of documentation about this problem.

**Comment by ErrorRaffyline0** [comment] 2022-11-22 23:22
Addressed in [Windows 11 Build 22621.898 (KB5020044)](https://blogs.windows.com/windows-insider/2022/11/17/releasing-windows-11-build-22621-898-to-the-release-preview-channel/).
Weird that the writers and support people said that the feature is no longer supported if they're actively fixing it...

**Comment by winhelponline** [comment] 2022-12-04 06:22
[KB5020044 Fixes Process Creation Audit Logging (Event ID 4688/1108 Issue](https://www.winhelponline.com/blog/kb5020044-process-creation-audit-event-4688-1108/)

The 1108 events should stop after updating to 22621.900. The [4688](https://learn.microsoft.com/en-us/answers/questions/1046836/no-more-events-4688-in-eventlog-anymore.html) (Process creation event) entries appear correctly now.

From [November 29, 2022—KB5020044 (OS Build 22621.900) Preview](https://support.microsoft.com/en-us/topic/november-29-2022-kb5020044-os-build-22621-900-preview-43f0bdf9-0b75-4110-bab3-3bd2433d84b3):

**Improvements**

> "It addresses an issue that affects process creation. It fails to create security audits for it and other related audit events."

**Comment by ErrorRaffyline0** [comment] 2022-12-05 13:10
> [KB5020044 Fixes Process Creation Audit Logging (Event ID 4688/1108 Issue](https://www.winhelponline.com/blog/kb5020044-process-creation-audit-event-4688-1108/)

I have also tested this, and it indeed seems to have been resolved. Now I'm just wondering why MS still claims it's not supported on Win11

**Comment by vinaypamnani-msft** [comment] 2023-01-13 18:26
Closing this issue, as the problem has been addressed.

**Closed by vinaypamnani-msft** 2023-01-13 18:26 UTC
Labels: threat-protection
