### ISSUE TITLE
View Windows 10 Devices Associated with Windows 10 Subscription License

### ISSUE THREAD

**Issue by eddypuck** [MicrosoftDocs/windows-itpro-docs#6576] opened 2020-04-25 23:32 UTC
Is there a Powershell command or other way to see the Windows 10 devices that are associated with a user?  I know they can have 5 devices licensed to unlock Enterprise features, so I would like to see the devices associated with the user.

**Comment by denisebmsft** [comment] 2020-04-28 16:25
Hello @eddypuck. Can you tell us to which article(s) your question pertains, so that we can route it to the correct writer/team? Thanks!

**Comment by e0i** [comment] 2020-05-16 18:05
Your issue has been opened without being associated to a documentation topic.

The issue is being closed as there hasn't been a response from your side regarding the specific article where the issue stems from.

Note that the issues section of this repository is intended for documentation and content feedback. For any similar questions, please visit, [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

If you feel that the related article also needs to be updated, feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates. Any documentation feedback is welcome.

Thank you, and stay healthy.

**Closed by e0i** 2020-05-16 18:05 UTC
Labels: question
