### ISSUE TITLE
Add information about Delivery Optiomization "scope" beyon Windows 10 updates

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/windows-itpro-docs#2913] opened 2019-03-13 11:43 UTC
It would be good if that article mentioned that Delivery Optimization works not only with Windows 10 updates, but also with Office 365 ProPlus updates, Microsoft Store apps, etc. etc.  The perception from this article could be that it works only for Windows 10 updates, while that is not true.
It's kind of hard to find that information anywhere, except on some scattered blogs as well as here:
https://myignite.techcommunity.microsoft.com/sessions/64510#ignite-html-anchor 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Configure Delivery Optimization for Windows 10 updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment] 2019-03-13 16:01
Good point! I have an overhaul of these topics in the pipeline right now (hopefully live later today in fact), including a table of all types of downloads that DO can manage. However, O365 ProPlus isn't currently in that table, so I'll double-check with the PM on that.

**Comment by e0i** [comment] 2019-05-09 14:44
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-09 14:50
@mariuszo-at-microsoft-com 

The issue is being marked as resolved since this issue has had been addressed with the following commit and content has been updated according to your input.

https://github.com/MicrosoftDocs/windows-itpro-docs/commit/076f1af663f191a2c8e45f2778f3770e21d4883c#diff-913948eb72d430873f66b6dd8ebed31b

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment] 2019-05-09 14:50
@officedocsbot close

**Closed by e0i** 2019-05-09 14:50 UTC
