### ISSUE TITLE
error 0x800705b4

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#5540] opened 2019-11-27 09:37 UTC
It works with User Driven Mode, but with white gloves, the first phase of protection hardware will fail 0x800705b4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#feedback)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [comment] 2020-02-11 22:35
There could be a lot of things going wrong there. You could be missing patches in your image. It could be the time of your BIOS is set off by 5 minutes. See https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/known-issues for known issues. 

If you want to know more about TPM attestation, you may visit https://oofhours.com/2019/07/09/tpm-attestation-what-can-possibly-go-wrong/

**Comment by JacquesRodrigues** [comment] 2020-03-02 15:46
Hi all, 

I have the same issue as "mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh".
We are using Windows 10 version 1909. When using the white glove approach we are presented with the same error message: 0x800705b4. After a simple restart en retry it simply works. this behavior seems inconsistent, sometimes it just works correctly from the first try. We would be really happy to get this resolved. Is anyone else experiencing this issue at the moment? 

Or maybe you've experienced it in the past and you could let us know how this got resolved? 

I've been scrolling through the Internet for a while now... :) 

Regards,

**Comment by goxia** [comment] 2020-03-03 01:45
Devices in some areas may have problems with TPM chips, But it'll be resolved later.

**Comment by ZsoltPfeiffer** [comment] 2020-03-20 10:44
Hi all,
I get this error with a compatible laptop, proper TPM and correct time sync settings.
Solution for me was: the TPM Certification checker sites MUST be reachable from the laptop on the network.
Intel- https://ekop.intel.com/ekcertservice
Qualcomm- https://ekcert.spserv.microsoft.com/EKCertificate/GetEKCertificate/v1
AMD- https://ftpm.amd.com/pki/aia
Infineon- https://pki.infineon.com
Check this.
Zsolt

**Comment by e0i** [comment] 2020-09-23 19:48
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Closed by e0i** 2020-09-23 19:48 UTC
Labels: deployment

**Comment by greg-lindsay** [comment] 2020-09-24 18:22
I've added a link to the networking requirements section pertinent to white glove and self-deploying mode into the articles for these scenarios. Hopefully this will help.
