### ISSUE TITLE
Office 365 ProPlus apps is missing Teams

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/windows-itpro-docs#5478] opened 2019-11-20 10:53 UTC
Since recent change that Micorosft Teams application is part of Office 365 ProPlus installation, please update this document that Teams is NOT supported as enlighted app!
Please check with product group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2019-11-21 21:46
I am guessing that Microsoft Teams (when confirmed) can be added either to the Note bubble 
or to the [**List of WIP-work only apps from Microsoft**](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip#list-of-wip-work-only-apps-from-microsoft) :

![image](https://user-images.githubusercontent.com/38162891/69379369-a6c61c00-0cb0-11ea-96b5-f8c58c44e2d2.png)

**Comment by e0i** [comment] 2019-11-29 18:09
Hello @hkusulja,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by hkusulja** [comment] 2019-11-29 18:15
@e0i you should close this, once this is resolved / means documentation is updated with correct current information, which is still not the case.

**Comment by e0i** [comment] 2019-11-29 18:23
@hkusulja Noted, Thank you for following up.

**Comment by artekartian** [comment] 2020-02-25 20:32
Could you make a comment on the new Edge (Chromium)? The app shows as "Enlightened" in Task Manager, the app locker file exists in the WIP Policy settings BUT is doesn't block the copy/paste to not-enterprise apps. Could someone confirm it should be working as the rest of WIP-aware apps?

**Comment by JoeMullarkey** [comment] 2020-04-20 01:59
@e0i, it does appear that Teams is reporting as not enlightened and the documentation does not reflect that. Are you having a bad day?

**Comment by illfated** [comment] 2020-04-20 08:28
Would be nice to hear either from the author or project manager what we can add or modify on the page, to get it updated and factually correct.

**Comment by e0i** [comment] 2020-04-20 16:54
Apologies, The issue has been buried in my notes because it has been re-opened. Passing it over to an independent contributor for investigation. Thank you for following up.

**Comment by VLG17** [comment] 2020-05-19 09:50
@hkusulja This has been addressed starting with **Teams build 1.3.00.12058** and is also reflected in the [article](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip#list-of-wip-work-only-apps-from-microsoft).

**Comment by e0i** [comment] 2020-05-21 18:56
Fixed via commit [[61554ae ] Corrected Teams &#39;WIP enlightened&#39; to &#39;WIP work only&#39; ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/61554aeb8a2c3e23236552bfb2cef1e1fef0de23)

**Closed by e0i** 2020-05-21 18:56 UTC
Labels: in progress, information protection
