### ISSUE TITLE
More information regarding ASR rules

### ISSUE THREAD

**Issue by jaegerschnitzel** [MicrosoftDocs/windows-itpro-docs#9334] opened 2021-03-19 11:13 UTC
It would be very nice if you could provide more information regarding specific ASR rules.

For example "Block executable files from running unless they meet a prevalence, age, or trusted list criterion".
-What does prevalance refer to?
-What does age refer to? As far as I could find out this means 24 hours
"or they're in a trusted list or an exclusion list" what is the difference between trusted list or exclusion list? As far as I know there is only the exclusion list available.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Verwenden von Regeln zur Reduzierung der Angriffsfläche, um Schadsoftwareinfektionen zu verhindern - Windows security](https://docs.microsoft.com/de-de/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-executable-files-from-running-unless-they-meet-a-prevalence-age-or-trusted-list-criterion)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment] 2021-03-22 14:36
Hello @jaegerschnitzel ,
This rule is not controlled by administrator, it is controlled by Microsoft cloud protection.
**What does prevalance refer to?** - prevalence of the application is assessed by Microsoft cloud protection
**What does age refer to?** - it refers to application release date
**"or they're in a trusted list or an exclusion list" what is the difference between trusted list or exclusion list?** - exclusion list is set by administrator, trusted list is internal list of applications trusted by Microsoft cloud protection.

Thank you

**Comment by nam31** [comment] 2021-04-07 17:18
@jaegerschnitzel Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by jaegerschnitzel** [comment] 2021-04-07 18:53
@nam31 Thanks for asking. The third part was of my question was answered to my full satisfaction.

The first two not really. I searched myself and found a Microsoft presentation with a few explanations.
**What does prevalance refer to?** - all unknown files which occur less than 1000 times Microsoft wide are blocked
**What does age refer to?** - unknown files newer than 24 hours are blocked

Perhaps you could add these two useful information in the official documentation?

**Comment by MaratMussabekov** [comment] 2021-04-12 17:25
Hello @jaegerschnitzel ,
that's a really useful information, can you please share the source?
Thank you

**Comment by nam31** [comment] 2021-05-04 18:39
@jaegerschnitzel We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by jaegerschnitzel** [comment] 2021-06-21 21:00
@nam31 
sorry for my late reply. This is the source: https://www.microsoftpartnercommunity.com/atvwr79957/attachments/atvwr79957/UK_Area_db/396/4/Microsoft%20Defender%20for%20Endpoint%20Overview.pdf

**Comment by MaratMussabekov** [comment] 2021-06-22 14:11
Hello, got it, I will create a PR.
Thank you

**Comment by nam31** [comment] 2021-06-23 06:56
Closing via https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5390
Thank you

**Closed by nam31** 2021-06-23 06:56 UTC
Labels: defender for endpoint
