### ISSUE TITLE
Bad translation

### ISSUE THREAD

**Issue by joergkarl** [MicrosoftDocs/windows-itpro-docs#6588] opened 2020-04-28 14:58 UTC
Some words are still in Englisch (1) or very bad translated into German (2). Example: usingmedical (1), visor (1), wischen (2)...
And why do you advise to use a antibiotic soap?
And what is SRG?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c9b9efc6-78cd-1f1e-bcd5-3e02130b7bd9
* Version Independent ID: 9ce2e642-96f3-ec9c-e8bd-1e5c8846d1e1
* Content: [HoloLens 2 – häufig gestellte Fragen zur Geräte Pflege und-Reinigung](https://docs.microsoft.com/de-de/hololens/hololens2-maintenance#feedback)
* Content Source: [devices/hololens/hololens2-maintenance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens2-maintenance.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by mypil** [comment] 2020-04-29 00:04
@joergkarl - Thank you for pointing this out.

I will get this issue over to the Win10 ITPro translation/localization writing team for investigation.


Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment] 2020-04-29 00:05
@tinamcN @officeglobal - Can you please assist with this Translation/Localization issue?

Thank you.

**Comment by TinaMcN** [comment] 2020-04-29 02:52
@joergkarl thank you for reporting this and the examples are very helpful.   I sent the article to be human translated which will take a few days..   The issue with "usingmedical" is caused by the machine translation tool which seems to have joined 2 English words which it could then obviously not translate to German.   I think the German word for "visor" is "Visier" but somehow the MT tool did not recognise that word.  I reported these to the MT tool owners for further investigation.  
@mypil regarding the issues about recommending antibiotic soap and SRG can you ask the writing team to comment as they are from the English article, it would be good to spell out what SRG means.

**Comment by TinaMcN** [comment] 2020-04-30 23:25
@joergkarl the article is now human translated and the translation issues should be fixed.  @Teresa-Motiv can you review the issues regarding antibiotic soap and SRG?

**Comment by Teresa-Motiv** [comment] 2020-05-01 00:33
I've forwarded the questions to the original doc author Saira.

**Comment by mypil** [comment] 2020-05-18 23:45
@Teresa-Motiv - Do you have any updates on this issue? Is this already fixed?

Thank you.

**Comment by illfated** [comment] 2020-05-19 00:30
Just to answer the question "And what is SRG?" : Surface Relief Grating (**Oberflächenreliefgitter**)

From https://www.imaginativeuniversal.com/blog/2015/10/18/how-hololens-displays-work/ :
> Nanometer wide structures or gratings are placed on the surface of the waveguide at the location where we want to extract an image. The grating effectively creates an interference pattern that diffracts the light out and even enlarges the image. This is known as **SRG or surface relief grating** as shown in the above image from holographix.com.

**Comment by illfated** [comment] 2020-05-19 00:41
@joergkarl : To answer your question "And why do you advise to use a antibiotic soap?", I would like to point out the possibility of bacterial growth or virus transfers in general. Because some of the Hololens parts are soft, some with a microporous surface, it is important to make sure you reduce the amount of bacteria left behind after each use, due to skin particles left behind, making the soft materials an easy target for bacterial growth. This can be mitigated by using antibacterial soap or detergents, diluted in water, according to the manufacturer's description and recommendation.

**Comment by illfated** [comment] 2020-05-19 00:47
Looking back at what I just wrote, I think it should be noted that using initials for technical terms, even if they are in common use when discussing the technical aspects of the device, it should be avoided in less technical articles like this page. The initials "SRG" should be replaced by its full description, Surface Relief Grating (or lowercase "surface relief grating").

**Comment by mypil** [comment] 2020-06-21 01:38
@joergkarl - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @TinaMcN and @illfated  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-06-21 01:38 UTC
Labels: devices, localization
