### ISSUE TITLE
注册表路径有误

### ISSUE THREAD

**Issue by KutouAkira** [MicrosoftDocs/windows-itpro-docs#6409] opened 2020-04-03 00:30 UTC
删除以下注册表设置：
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\LSA\LsaCfgFlags
HKEY \ _LOCAL \ _MACHINE \Software\Policies\Microsoft\Windows\DeviceGuard\LsaCfgFlags

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [管理 Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/zh-cn/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2020-04-03 01:43
From web translator, translating the Chinese (Hanzi) above:
### Registry path is wrong #6409

Delete the following registry settings:
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\LSA\LsaCfgFlags
HKEY \ _LOCAL \ _MACHINE \Software\Policies\Microsoft\Windows\DeviceGuard\LsaCfgFlags

***
From the English (/en-us/) page:

2. Delete the following registry settings:

    - HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\LSA\LsaCfgFlags
    - HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DeviceGuard\LsaCfgFlags

***
Unfortunately, I can not verify this information, because I am not using Windows Defender Credential Guard at home (on Windows 10 Home) or at work, using Windows 10 Professional, so registry does not show any of those registry path ends. I am only seeing (in both cases) the following parts of the paths:
- Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\
***
Can someone who has got access to a Windows 10 Pro or Enterprise computer with Windows Defender Credential Guard (and maybe also Device Guard) enabled, please verify & confirm if these Registry paths exist or not (depending on whether GPO is required in this case)?

**Comment by RAJU2529** [comment] 2020-04-03 05:53
@illfated . From my research on window 10 , the Group policy editor can be enabled  using  some commands in home edition too.
I have already GPO in windows 10 home edition, applied policies.

At present,, i am using enterprise, enabled all protections and also  i conformed that some registry keys misspelled in Chinese article.

**Comment by RAJU2529** [comment] 2020-04-03 05:54
@illfated . Will you create new PR, deleting and adding with correctly spelled registry keys.

**Comment by illfated** [comment] 2020-04-03 06:02
First of all, thank you for the feedback. I presume you confirmed that the Registry paths in this article are incorrect.

Secondly, do you have the correct Registry paths that we should insert there instead?

**Comment by RAJU2529** [comment] 2020-04-03 06:09
@illfated . four registry paths are miss spelled
**HKEY_LOCAL_MACHINE.S.-System-CurrentControlSet-LSA-LsaCfgFlags
HKEY \ _LOCAL \ _MACHINE \Software\Policies\Microsoft\Windows\DeviceGuard\LsaCfgFlags**

in first line you can  see  **hypen** is inserted  instead of   **\**
in second line ,  you can see **\** is inserted

**Comment by illfated** [comment] 2020-04-03 07:51
> @illfated . four registry paths are miss spelled
> **HKEY_LOCAL_MACHINE.S.-System-CurrentControlSet-LSA-LsaCfgFlags HKEY \ _LOCAL \ _MACHINE \Software\Policies\Microsoft\Windows\DeviceGuard\LsaCfgFlags**
> 
> in first line you can see **hypen** is inserted instead of \ symbol
> in second line , you can see \ is inserted

Ahaa... Thank you for pointing out the detail. See the following image from the page, where the search (Ctrl-F) highlights the correct format:

***

![image](https://user-images.githubusercontent.com/38162891/78337010-9132fe00-7590-11ea-96c4-ffe4bbcd7f1e.png)

***

**Comment by illfated** [comment] 2020-04-03 07:59
@TinaMcN : There seems to be a machine translation issue for one or more of the Registry paths in the /zh-cn/ page, so I presume this needs to be forwarded to the translation team.

**Comment by TinaMcN** [comment] 2020-04-03 17:47
@OfficeGlobal please human translate the article.

**Comment by illfated** [comment] 2020-04-06 07:37
@KutouAkira : 請重新打開此票證，直到問題解決。
(Please reopen this ticket until the issue is resolved.)

**Comment by OfficeGlobal** [comment] 2020-04-06 12:06
Working on a fix

**Comment by mypil** [comment] 2020-05-31 02:36
@OfficeGlobal - Do you have any updates on this? Is this issue already fixed?

Thank you.

**Comment by illfated** [comment] 2020-05-31 09:46
Looks like the non-standard pathing (extra spaces and underscores) is corrected from being translated in the /zh-cn/ page. As a comparison to the image I pasted above, in comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6409#issuecomment-608285930 from April 3, this is what it looks like now:

***

![image](https://user-images.githubusercontent.com/38162891/83349208-5270b880-a333-11ea-8ddf-84146eaffcf4.png)

***

So far, it looks like the most visible problem has been corrected. @KutouAkira : Would you like to confirm whether the issue is resolved?

Please note that if you find some of the information to be incorrect, like for example the path contents, it would need to be corrected in the /en-us/ pages for the corrections to be available in every translated page (given that the information is still factually incorrect in the /en-us/ page also).

**Comment by mypil** [comment] 2020-06-07 21:50
@KutouAkira - Thank you for submitting feedback.

From our understanding, this has been resolved so we will close this issue now.

Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-06-07 21:50 UTC
Labels: identity protection, localization
