### ISSUE TITLE
page not updated

### ISSUE THREAD

**Issue by dustinhess** [MicrosoftDocs/windows-itpro-docs#8630] opened 2020-11-13 13:12 UTC
The controls on this page haven't been updated to reflect new information as of 11-13-2020

20H2 update included additional controls:
https://docs.microsoft.com/en-us/hololens/hololens-release-notes

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659d0469-51e7-bf41-6913-c249d05548b6
* Version Independent ID: 7732d212-5328-9c03-7270-572146c074e8
* Content: [Policies in Policy CSP supported by HoloLens 2 - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2)
* Content Source: [windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2020-11-13 21:25
I would love to help out with updates, but unfortunately I don't have enough personal experience with this topic to know exactly what the changes should look like.

**Comment by MaratMussabekov** [comment] 2020-11-21 11:03
Hello, resolved by  https://github.com/MicrosoftDocs/windows-itpro-docs/commit/b83eb4e191a0564d1c70991c25d80728ef11ec6b, https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a9a7b85b6836362b122250851eab8319c16d1baf and https://github.com/MicrosoftDocs/windows-itpro-docs/commit/991070cce473892719b8a7ef3755a2fce5523ac8
Thank you

**Comment by nam31** [comment] 2020-12-02 13:54
@dustinhess Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2020-12-02 13:54 UTC
Labels: mdm
