### ISSUE TITLE
Hybrid Azure AD Join VPN functionality

### ISSUE THREAD

**Issue by ITCTarunchhabra** [MicrosoftDocs/windows-itpro-docs#6458] opened 2020-04-10 05:53 UTC
Hi Team, we have all our users in remote location and we have configured AutoPilot for the machines to join to Azure AD. Hybrid Azure AD Join with AutoPilot was not supported with VPN and it needs direct connectivity to on-premise network. Is that still the case or I can connect to AutoPilot-Hybrid Azure AD using VPN ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2434dfb6-ac9a-4ba1-a681-88786c87010a
* Version Independent ID: 47e7470e-ab97-9917-04aa-4ec08a178af5
* Content: [Windows Autopilot User-Driven Mode - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven#feedback)
* Content Source: [windows/deployment/windows-autopilot/user-driven.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/user-driven.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by markdepalma** [comment] 2020-04-18 23:24
This functionality should be in preview in the coming months (per Microsoft), but unfortunately is not out yet. I am working on a method to make this work at the moment. I have it working, but haven't locked it down to be 100% consistent. I will reply here once I have something to report.

**Comment by ITCTarunchhabra** [comment] 2020-04-19 10:50
Thank you Mark. I will look forward to your feedback.

Best Regards,
Tarun

**Comment by markdepalma** [comment] 2020-04-19 13:32
I nailed down the experience and configuration last night. I was able to reproduce consistently with new autopilot enrollments I am writing a blog article in the next day or two and will post it here when it is finished.

**Comment by tieronebanter** [comment] 2020-04-21 05:03
Can't wait!

**Comment by Sculpin90** [comment] 2020-04-21 11:27
What kind of VPN markdepalma? Always On VPN? Split-tunnel or Device-Tunnel? Or a third party?
If this functionality still only is in preview, what kind of VPNs are supported?

**Comment by VLG17** [comment] 2020-05-04 20:16
@ITCTarunchhabra This functionality is in private preview, with public preview expected this month - https://oofhours.com/2020/03/18/podcast-episode-1-windows-autopilot-hybrid-azure-ad-join/

according to Michael Niehaus, Program Manager:

> This capability is presently in private preview, with public preview expected in May.

**Comment by markdepalma** [comment] 2020-05-05 19:14
> What kind of VPN markdepalma? Always On VPN? Split-tunnel or Device-Tunnel? Or a third party?
> If this functionality still only is in preview, what kind of VPNs are supported?

I am using device tunnel and user tunnel (MS Always On) to make it all work. I had to write my own script (injected via Intune) to manage the EKU filter on the device tunnel and also had to let device tunnel use the Intune MDM device cert to authenticate to RRAS because it takes a little bit for the device certificate Intune profile to come down. I've been testing on multiple devices and just been trying to make it all consistent (also been busy with other things).

**Comment by markdepalma** [comment] 2020-05-05 19:16
> @ITCTarunchhabra This functionality is in private preview, with public preview expected this month - https://oofhours.com/2020/03/18/podcast-episode-1-windows-autopilot-hybrid-azure-ad-join/
> 
> according to Michael Niehaus, Program Manager:
> 
> > This capability is presently in private preview, with public preview expected in May.

Even if you use the network skip option (which I see references too in the autopilot logs) you'd still need certs to come down to authenticate to VPN. I'm wondering how they are making that all work immediately. I see significant delays in my cert and PowerShell profile delivery times compared to when I finish enrollment.

**Comment by mypil** [comment] 2020-05-16 15:58
@ITCTarunchhabra - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @markdepalma & @VLG17 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-05-16 15:58 UTC
Labels: deployment
