### ISSUE TITLE
Ошибка в машинном переводе

### ISSUE THREAD

**Issue by emil-ufa** [MicrosoftDocs/windows-itpro-docs#5842] opened 2020-01-14 16:22 UTC
Машинный перевод на русский язык калькой прописал путь к настройке политики безопасности:
Конфигуратион\виндовс компьютеров Сеттингс\секурити Сеттингс\локал ПолиЦиес\усер

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a8d839f2-c46b-657a-f19b-b3b20e383dfd
* Version Independent ID: 69a66a2f-b607-cd53-b5cd-0f5854639dbc
* Content: [Вход в качестве пакетного задания (Windows 10)](https://docs.microsoft.com/ru-ru/windows/security/threat-protection/security-policy-settings/log-on-as-a-batch-job#%D0%BD%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5)
* Content Source: [windows/security/threat-protection/security-policy-settings/log-on-as-a-batch-job.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/log-on-as-a-batch-job.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2020-01-15 01:53
Oh. I see. There are several lines of verbatim Operating System text or object names translated by Machine Translation.

@TinaMcN : Even though I could have suggested a change to the original en-us page using MarkDown backticks to `encapsulate` the OS keywords to prevent them from being translated, I believe that would only be practical for the table in the article. Not quite as acceptable or practical for the regular free text.

I also find it challenging to verify how much of the article text appears in English in a Russian Windows 10 OS.

**Comment by shivtorov** [comment] 2020-01-15 13:08
just looked at all these machine "translated" ru-ru pages - they are hilarious.
for many object names the machine just replaced characters from "en" alphabet with "ru" alphabet.
e.g. "SeTrustedCredManAccessPrivilege" becomes "Сетрустедкредманакцесспривилеже"
obviously, this symbol-by-symbol "translation" does not make any sense.

**Comment by mypil** [comment] 2020-01-15 22:53
@emil-ufa - Спасибо за отправку отзыва.
Я передам этот вопрос команде Win10 ITPro для расследования.

Спасибо, что сообщили и сделали документы лучше. Очень ценится.

Я принял к сведению, чтобы попросить команду обновить это, когда работа будет завершена.

**Comment by mypil** [comment] 2020-01-15 22:56
@tinamcN - Can you please assist with this translation/localization issue?

Thank you.

cc: @kenwith

**Comment by TinaMcN** [comment] 2020-01-15 22:59
I can't see the example "Сетрустедкредманакцесспривилеже" in the [Russian article](https://docs.microsoft.com/ru-ru/windows/security/threat-protection/security-policy-settings/log-on-as-a-batch-job) nor "SeTrustedCredManAccessPrivilege" in the [English article](https://docs.microsoft.com/fr-fr/windows/security/threat-protection/security-policy-settings/log-on-as-a-batch-job).  Am I looking in the wrong place?  @shivtorov can you please attach a screenshot?

**Comment by shivtorov** [comment] 2020-01-16 10:51
@TinaMcN , you right, this particular example "SeTrustedCredManAccessPrivilege" was from a different article in this repository - lots of these Russian pages essentially unreadable.

please find below a list of examples of symbol-by-symbol "translations" on this page.
```
EN:	SeBatchLogonRight
RU:	Себатчлогонригхт

EN:	Computer Configuration\Windows Settings\Security Settings\Local Policies\User Rights Assignment
RU:	Конфигуратион\виндовс компьютеров Сеттингс\секурити Сеттингс\локал ПолиЦиес\усер

EN:	IUSR_<ComputerName> and IWAM_<ComputerName>
RU:	<иуср_> ComputerName и<ивам_> ComputerName

EN:	IIS_WPG
RU:	иис_впг	

EN:	IUSR_<ComputerName>
RU:	иуср_<имя_компьютера>

EN:	IWAM_<ComputerName>
RU:	ивам_*<ComputerName> *
```

**Comment by mypil** [comment] 2020-02-22 12:23
@TinaMcN - Do you have any updates on this?

Thanks.

**Comment by illfated** [comment] 2020-02-22 18:53
@shivtorov : May I ask you to list some of the pages where this issue is particularly bad, so we could start looking into the possibility of making constructive changes to the originating `/en-us/` pages? I am thinking that I would like to suggest adding MarkDown code markers around code which is specific references to either Policy CSPs, registry entries and file paths.

**Comment by TinaMcN** [comment] 2020-02-28 01:08
I have escalated this issue to the team that owns the machine translation tool.  (Я обострил этот вопрос для команды, которая владеет инструментом машинного перевода. )

**Comment by TinaMcN** [comment] 2020-04-21 23:16
Quick update on this issue: after much investigation the root cause has been found a fix is ready.  We are starting to machine translate all of the Russian content again to correct the issue.  @emil-ufa @shivtorov thank you very much for highlighting it!

**Comment by mypil** [comment] 2020-05-18 23:14
@TinaMcN - Do you have any updates on this? Is this issue already resolved?

Thank you!

**Comment by TinaMcN** [comment] 2020-05-18 23:29
Yes, this should be fixed now.  I believe the machine translation tool has been re-run on all the content.   Please let me know if you notice this issue again or any other issues.

**Comment by illfated** [comment] 2020-05-18 23:31
Confirmed, all the words listed in the comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5842#issuecomment-575095713 by @shivtorov is now correctly displayed in English as they should be, due to the technical application of those terms.

**Comment by mypil** [comment] 2020-05-18 23:34
@emil-ufa @shivtorov - From our understanding, the issue you raised has been resolved so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-05-18 23:34 UTC
Labels: localization
