### ISSUE TITLE
Escape chars still needed?

### ISSUE THREAD

**Issue by phreeze83** [MicrosoftDocs/windows-itpro-docs#4659] opened 2019-08-09 08:59 UTC
as of version 1809 and later, are the escapechar modifications still needed?
Also the other steps seem to need some updating

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a4bce60-7c25-0acc-119d-a6b6b64aabd1
* Version Independent ID: 948c471f-2660-d0e5-d157-a5091444d5be
* Content: [Customize Windows 10 Start and tasbkar with provisioning packages (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-provisioning-packages-and-icd#feedback)
* Content Source: [windows/configuration/customize-windows-10-start-screens-by-using-provisioning-packages-and-icd.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-windows-10-start-screens-by-using-provisioning-packages-and-icd.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment] 2019-08-10 15:30
Hello @phreeze83  thank you for your question. Replacing the markup characters in the layout.xml with escape characters is one of the crucial steps on this doc. Have you tried bypassing it and did it work for you? What I would recommend to get immediate feedback is to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). And if the information from the support team needs to be called out on this documentation, e.g. *they confirmed that on X version there is no need to replace the markup with escape characters*, please let us know immediately so we can submit content amendments for review. If I have misunderstood your question, kindly clarify and provide more information. 

> Also the other steps seem to need some updating

As regards to the steps, where exactly is the inaccuracy? Is this related to the escape characters step as well? 

Thank you again for taking the time to share your feedback. Looking forward to your updates.

**TIP**: If you have Microsoft products or features questions, please check the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities), and interact with other community users, experts and also Microsoft engineers!

**Comment by phreeze83** [comment] 2019-08-12 10:16
it would be simpler if you just try it out yourself ;) 
without replaying markups, with an icd version 10.0.18362.1 it is possible to create the provisioning package just by giving it the XML file exported by windows. The package is able to be installed uninstalled, but my startmenu is not changing, probably because i'm using "Desktopapplicationlinkpath", don't know yet. Using the replaced markups, the package installs too, but still no change in the way it looks...weird

**Comment by phreeze83** [comment] 2019-08-13 12:39
addendum: the ICD version from the 1809 ADK does not even accept jut putting layout.xml in the startmenu variable. Plus it does not accept escaped code into the customization.xml etc. I don't know at what point something got broken there. Perhaps i need to downgrade the ADK (i needed the new one for the WinPE). To be able to create startlayouts again

**Comment by jvsam** [comment] 2019-08-18 00:36
I would love to assist you with your concern @phreeze83, however, this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. For technical issues that require testing or troubleshooting, then support or the forums will be your best option. But if you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will request assistance from the content writing team. I hope you'll be able to resolve your issues soon!. Thank you.

**Comment by jvsam** [comment] 2019-08-31 07:22
Hello @phreeze83, we hope you were able to contact support or reach out to the Tech community to resolve your concern. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. Thank you.

**Comment by jvsam** [comment] 2019-08-31 07:22
@officedocsbot close

**Closed by jvsam** 2019-08-31 07:22 UTC
