### ISSUE TITLE
Dates these release

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/windows-itpro-docs#8957] opened 2021-01-12 21:40 UTC
Can we please add the dates for when each of these versions release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ca25ead-3b5d-4434-1865-0d4fef57ebdf
* Version Independent ID: 8d146609-15b5-b8a0-62bf-108f29248991
* Content: [What's new in Microsoft Defender Advanced Threat Protection for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2021-01-12 23:07
There sort of is some form of history, as mentioned 8 months ago in issue ticket #6640 (**Please add version history**), which is this page:
- https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public/windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew.md

But then again, I don't know if the Defender for Endpoint updates truly and factually coincide with the page updates.

Waiting for feedback from one of the MS Docs team members.

**Comment by e0i** [comment] 2021-01-19 14:35
Duplicate of #6640. See comment, https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6640#issuecomment-624175839

**Closed by e0i** 2021-01-19 14:35 UTC
Labels: Microsoft submitter
