### ISSUE TITLE
Miss translation for Japanese

### ISSUE THREAD

**Issue by rioriost** [MicrosoftDocs/windows-itpro-docs#5942] opened 2020-01-28 07:10 UTC
In the section, 'System Requirements',
10.15 (Catalina)、10.14 (Mojave)、10.13 (高校)
should be
10.15 (Catalina)、10.14 (Mojave)、10.13 (High Sierra)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2020-01-29 23:30
True, the third name is translated when it should not be:
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac#システム要件
***
[**システム要件**](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac#システム要件)
MacOS の最新の3つのメジャーリリースがサポートされています。

10.15 (Catalina)、10.14 (Mojave)、10.13 (高校)
ディスク容量: 650 MB
***
According to online translator tools, " 高校 " translates to something like "College" or "University".
***
CC: @TinaMcN

**Comment by TinaMcN** [comment] 2020-01-29 23:41
@rioriost thank you for reporting it.  The article is machine translated.  I will send it to a translator to get it fixed, it may take 2-4 weeks as we are in the process of switching localization vendor.

**Comment by TinaMcN** [comment] 2020-01-29 23:41
@illfated please assign this to me.

**Comment by illfated** [comment] 2020-01-29 23:49
@TinaMcN : Thank you for assuming that I would be a MS Docs team member, but I am merely a lowly user & external contributor. 😅

@mypil : Please assist regarding the assignment. Thank you.

**Comment by TinaMcN** [comment] 2020-01-29 23:54
@illfated I assumed you were part of the MS Docs team because you are so active and have so many great suggestions for fixing issues..  Thank you for all the fantastic assistance in improving our documentation!

**Comment by illfated** [comment] 2020-01-30 00:00
Thank you for your nice words. It is true that I spend a lot of my spare time contributing, but it has also been a way for me to find practical use for my slight autism (highly functional type) sprinkled with a touch of OCD.

**Comment by TinaMcN** [comment] 2020-01-30 00:06
@illfated I'm very grateful that you choose to spend your spare time improving our documentation.  Thank you!!!

**Comment by mypil** [comment] 2020-01-30 02:45
@TinaMcN - I just assigned this issue to you. Thank you.

@illfated - As always, thank you for your proactive assistance. We greatly appreciate it!

**Comment by TinaMcN** [comment] 2020-02-27 00:10
@rioriost this issue has now been fixed.  Thanks again for reporting it!

**Comment by illfated** [comment] 2020-02-27 06:29
Confirmed, the mistranslation of (High Sierra) has now been resolved.

**Comment by mypil** [comment] 2020-02-28 00:42
@rioriost - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by TinaMcN so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-02-28 00:42 UTC
Labels: in progress, localization, microsoft defender atp
