### ISSUE TITLE
Error code 0x80070422

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-itpro-docs#9190] opened 2021-02-22 19:54 UTC
Missing error code 0x80070422 and related description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
* Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
* Content: [Windows Update error code list by component - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference)
* Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-error-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment] 2021-02-22 20:19
Document links:
- https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-error-reference.md

Different page from issue ticket #9189 (**Error code 0x80070422**), but the content issue is the same.

**Comment by RAJU2529** [comment] 2021-02-23 01:38
@e0i , please close this issue , because  same  issue has been reported  in #9189

**Comment by nam31** [comment] 2021-02-23 16:48
Closing this as it's a duplicate of [9189](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9189)

**Comment by illfated** [comment] 2021-02-24 13:09
@LuigiBruno : I apologize on behalf of  @RAJU2529 and @nam31 , they usually don't have time to go into details.

Maybe we should just move the content from this ticket into the other ticket, to make sure that the other ticket deals with multiple pages.

**Comment by nam31** [comment] 2021-04-16 13:33
Closing via #9412 
Thank you

**Closed by nam31** 2021-04-16 13:33 UTC
