### ISSUE TITLE
Revert change to license requirements made recently.

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/windows-itpro-docs#5454] opened 2019-11-18 18:30 UTC
The License Requirements section was updated to include a licensing change that happened earlier this year. I see that the change was committed several months ago and reverted recently.

https://github.com/MicrosoftDocs/windows-itpro-docs/commit/2b66253419958a0ce03431b885290a05f1faa43e#diff-6701b7a2e1253d31a8b2d4eae1e26628

Please re-add the M365 E3 with Security Addon licensing option to this page. I added additional comments to issue #3718.

The official announcement calls it the "Identity & Threat Protection" add-on available for M365 E3. The product catalog has it listed as "Microsoft 365 E5 Security" and it is an add-on to the M365 E3 product.

This page really should include the most recently introduced method for licensing Microsoft Defender ATP.

**Comment by e0i** [comment] 2019-11-26 16:25
Closing as a follow-up duplicate of #3718

**Closed by e0i** 2019-11-26 16:25 UTC
