### ISSUE TITLE
Article states "Microsoft Defender ATP currently does not support Windows Virtual Desktop multi-user session.", while MDATP support for WVD was announced

### ISSUE THREAD

**Issue by dvandoorn76** [MicrosoftDocs/windows-itpro-docs#6824] opened 2020-05-27 09:26 UTC
In this article there is still a warning (including typo) that WVD multi-user session is NOT supported, while it is currently in preview:
"Micrsosoft Defender ATP currently does not support Windows Virtual Desktop multi-user session."

However in the Microsoft Techcommunity article from May 7, 2020 https://techcommunity.microsoft.com/t5/windows-virtual-desktop/microsoft-defender-atp-now-in-preview-on-windows-10-enterprise/m-p/1372007 support for Microsoft Defender Advanced Threat Protection (MDATP) on Windows Virtual Desktop was announced enabling both single and multi-session scenarios. For WVD multisession scenario there is a note in that article stating multi-user is still in preview while single session is fully supported:
"Multi-user session scenarios is currently in Preview and limited up to 25 concurrent sessions per host/VM while the single session scenarios are fully supported."

Can the article be updated according to the announcement. 

Also for WVW for onboarding the current instructions for Windows 10 and server OS are mentioned, however it is not clear to me what this means for licensing. MUST we use licensing on a per user basis, or will on a per device/host basis also be available for W10 multi session hosts? There might be Windows 10 multisession WVD scenario's for certain customers where licensing on a per device/WVD VM basis is more interesting compared to licensing per user.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804f2883-5de4-9d54-d0b4-e64b04984aa8
* Version Independent ID: 0ab9ee92-c5e1-0455-92ba-ed07ed7bd140
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) machines - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment] 2020-07-05 04:24
Hello @dvandoorn76,
the issue is already fixed in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c0e41df2f57f888d13c1ed9b80dcd92f0711c59c#diff-3684d7e81c25a8f6d2e8d45baca8d406
**MUST we use licensing on a per user basis, or will on a per device/host basis also be available for W10 multi session hosts?** - for W10, only per user licenses are available (each could be used for up to 5 devices), and for servers - standalone server licenses must be used (per device). Note, to be able to buy server license, you must have at least 50 user licenses (source: [Licensing requirements](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#licensing-requirements))
Thank you

**Comment by illfated** [comment] 2020-07-05 14:08
( commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c0e41df2f57f888d13c1ed9b80dcd92f0711c59c )

**Closed** 2020-07-05 19:52 UTC
Labels: in progress, microsoft defender atp
