### ISSUE TITLE
Enable Prevent installation of devices that match these device setup classes.

### ISSUE THREAD

**Issue by Pickell** [MicrosoftDocs/windows-itpro-docs#6658] opened 2020-05-06 17:49 UTC
The example of the proper usage of "Enable Prevent installation of devices that match these device setup classes" is missing from the subsection "Prevent installation and usage of USB drives and other peripherals".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f395d314-f7cd-6d89-b392-b0af0e527d36
* Version Independent ID: dffc4bff-3403-9b7a-3ccb-69f92ece2672
* Content: [How to control USB devices and other removable media using Intune (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-control/control-usb-devices-using-intune#feedback)
* Content Source: [windows/security/threat-protection/device-control/control-usb-devices-using-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-control/control-usb-devices-using-intune.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment] 2020-05-12 14:48
@Pickell. The issue is conformed, I can edit the article, but I don't know how to add screenshots. So i  stopped.

**Comment by mypil** [comment] 2020-06-02 22:18
@Pickell @RAJU2529 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c7487990ba3b4e3d9e2374dec0027896b96cb222. 


Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-06-02 22:18 UTC
Labels: devices, threat-protection
