### ISSUE TITLE
Redirection error

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/windows-itpro-docs#4709] opened 2019-08-16 13:59 UTC
Again the link for Purchase MDOP is sending us to a non existing page (i end up there -&gt; https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=VG+zGKAdU0GQxv80.0.3.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8efb31f6-d09e-1db4-9e1b-baed18254b65
* Version Independent ID: b45f19dd-510d-1cd5-5e05-ce85690aab51
* Content: [MDOP Information Experience](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/)
* Content Source: [mdop/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment] 2019-08-16 14:14
@officedocsbot assign @jvsam

**Comment by illfated** [comment] 2019-08-16 15:30
Weird, the `correlationId` seems to be either randomized or a variable depending on the state of the page (& operating system?) you start off from.
I managed to get 2 separate different ones:
- https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=fudBxgZQYUuuQonh.0.3.0
- https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=V8JGFYM8/EaKRPJm.0.3.0

The only unchanged part is `.0.3.0` at the end of the link / end of `correlationId` .

**Comment by jvsam** [comment] 2019-08-18 22:56
Thank you for bringing this to our attention @baardhermansen, however, I can't see where the issue is. Can you please clarify which link is redirecting to a non-existent page? Are you pertaining to the *Purchase Windows Enterprise Licensing* link?

![image](https://user-images.githubusercontent.com/18371314/63231240-6a1afc80-c24b-11e9-8949-c564cb9cd7c3.png)

When clicked, it redirects user to the Volume Licensing page based on the user's country/region. Here's the worldwide page - https://www.microsoft.com/en-us/Licensing/worldwide.  

Let me know if that is not the link, although I've checked all the links on this [doc](https://docs.microsoft.com/microsoft-desktop-optimization-pack/) and they're all fine. Thank you for the clarification.

**Comment by baardhermansen** [comment] 2019-08-19 10:36
@jvsam Sorry, i wasn't too specific: Yes, i was referring to the Purchase Windows Enterprise Licensing link. As @illfated says, the correlationId is different each time apart from the ".0.3.0" at the end of the link.
I also tried the licensing worldwide link you referred to above, but same situation there; i'm redirected to the same errorpages link, again with a new correlationId.

**Comment by baardhermansen** [comment] 2019-08-19 10:41
@jvsam I'll be darned: Been using Edge version 78.x on the previous tries. Switched to Opera and now i'm redirected to the correct site, both with the Purchase Windows Enterprise Licensing and the /Licensing/worldwide links. 
Guess the issue can be closed then as the error lies in the browser, not the links.

**Comment by illfated** [comment] 2019-08-19 17:24
Thank you for keeping us updated on your attempts to get connected to the online service. I don't know what is going on there, but I would have thought that the page would favor Microsoft browsers (unless outdated, of course). Sorry for not knowing that service page any better, but I am not in a position to test the ATP service by trying to buy a license for it. I can only hope this situation may be forwarded to someone who knows the ATP license service page well enough to comment on it, in case there is something worth looking closer into there.

**Comment by jvsam** [comment] 2019-08-21 23:45
Glad to hear that it's working for you now @baardhermansen. I am not sure what's the issue with your Edge browser (*it does work for me*), but the first thing that comes to mind is perhaps some security settings or configuration somewhere (AV, firewall, etc.?). Or try to open it via in-private session to determine that it's not a locale issue. Hopefully, it's just a temporary problem.

We can now consider this issue resolved so I will close it. Feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you again for your feedback!

**Comment by jvsam** [comment] 2019-08-21 23:46
@officedocsbot close

**Closed by jvsam** 2019-08-21 23:46 UTC
