### ISSUE TITLE
Bulk enrollment device limit

### ISSUE THREAD

**Issue by MSLuke** [MicrosoftDocs/windows-itpro-docs#5262] opened 2019-10-24 09:11 UTC
I’m looking for information on how to change the 20 devices limit that the Windows Configuration Designer advises of. I can’t find anything in the MSDocs articles for bulk enrollment or provisoning packages that advises on how to actually change this limit. I am not sure if it is related to the token itself or the account used to generate the token.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d1da33-932c-e5cf-7a3c-8523d48a3a68
* Version Independent ID: bd16dcec-e38f-501d-22f4-735e50e93fa6
* Content: [Provisioning packages (Windows 10)](https://docs.microsoft.com/en-gb/windows/configuration/provisioning-packages/provisioning-packages)
* Content Source: [windows/configuration/provisioning-packages/provisioning-packages.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/provisioning-packages/provisioning-packages.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment] 2019-10-27 18:45
Duplicate of #5261

**Closed by e0i** 2019-10-27 18:45 UTC
