### ISSUE TITLE
Edge Tile Variables

### ISSUE THREAD

**Issue by danieldhudson** [MicrosoftDocs/windows-itpro-docs#1839] opened 2018-10-11 08:41 UTC
The variables for the Edge tile are incomplete/incorrect. When extracting the XML from the start menu (as per Yoav's guide) I get the following:

Square150x150LogoUri="ms-appx:///Assets/MicrosoftEdgeSquare150x150.png" Wide310x150LogoUri="ms-appx:///" ShowNameOnSquare150x150Logo="true" ShowNameOnWide310x150Logo="false"

Note that the Edge tile asset is different, and the ShowNameOnWide variable is missing from the example XML.

It should also be noted that, if using a 4x2 tile, you will need to change the variables around to the following:

Square150x150LogoUri="ms-appx:///" Wide310x150LogoUri="ms-appx:///Assets/MicrosoftEdgeWide310x150.png" ShowNameOnSquare150x150Logo="false" ShowNameOnWide310x150Logo="true"

Finally, the foreground text variable is missing:

ForegroundText="light"

Value can be light or dark, depending on what you change the BackgroundColor variable to and which text colour you'd like to match (light text on white tile isn't a good choice after all!). 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69882e91-6bef-d524-7059-20ba67129f4e
* Version Independent ID: ee0f2eb3-97da-4306-5cd1-2b6ae1858ed9
* Content: [Configure Surface Hub Start menu](https://docs.microsoft.com/en-gb/surface-hub/surface-hub-start-menu)
* Content Source: [devices/surface-hub/surface-hub-start-menu.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-start-menu.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment] 2018-10-11 16:58
@danieldhudson Thanks for the feedback. I'm checking with the product team on whether the image export results might have changed since the topic was written.

**Comment by jdeckerms** [comment] 2018-10-12 13:39
@danieldhudson Per the product team, Microsoft Edge tile logos won't appear on secondary tiles because they aren't stored in Surface Hub, so the path doesn't matter. However, I'm changing the example to avoid confusion. I'm also adding a note to explain that the default value of ForegroundText is light, so you don't need to include it in the XML unless you're changing the value.

**Comment by danieldhudson** [comment] 2018-10-16 08:08
Hi @jdeckerms. Ran some testing on this and the product team have this wrong; the Edge tile logos are stored on Surface Hub and will show when using the correct variable.

If you leave the Square and Wide variables as "ms-appx:///" then they will appear blank. Completing them as per my example does show the Edge logo.

See here for proof: https://imgur.com/a/vzQeARC (Please excuse the potato quality... capture card is at home!).

**Comment by jvsam** [comment] 2019-06-06 23:38
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-06-15 23:08
Hi @danieldhudson we appreciate your feedback. This note has been added to the documentation.

> *Microsoft Edge tile logos won't appear on secondary tiles **because they aren't stored in Surface Hub**. The default value for ForegroundText is light; you don't need to include ForegroundText in your XML unless you're changing the value to dark.*

As per the testing you've done, is it inaccurate? Or is it related to your [last comment](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1839#issuecomment-430142141)? We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are accurate and up-to-date so your feedback will definitely help. Also, if you have feedback or suggestions related to Windows 10 features or products, please submit it to [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Your feedback goes directly to the engineering team and they would love to hear what you think.

**Comment by danieldhudson** [comment] 2019-06-17 15:11
Hi @jvsam. I would say that, as per my testing, the note on the documentation is wrong. Completing the variable for Edge tile logos works fine on Surface Hub, suggesting that the logos are indeed stored in Surface Hub.

**Comment by jvsam** [comment] 2019-06-21 08:51
Thank you for the update @danieldhudson .

Hello @levinec I hope all is well. Can you help us with this please? As per @danieldhudson's testing, the *Note* is no longer accurate. Kindly advise. Thank you.

**Comment by jvsam** [comment] 2019-06-30 14:52
Hi @levinec if time permits, can you please look into this issue and confirm if the behavior is accurate or not? Let us also know if you need more information. Thank you.

**Comment by jvsam** [comment] 2019-07-07 07:25
> I would say that, as per my testing, the note on the documentation is wrong. Completing the variable for Edge tile logos works fine on Surface Hub, suggesting that the logos are indeed stored in Surface Hub.

Hello @levinec and @Dansimp do you have any answer for us regarding the issue raised here? Whether it's the expected behavior or is this just a glitch or an isolated system problem? Thank you.

**Comment by jvsam** [comment] 2019-07-14 12:55
Hi @danieldhudson it's been a while. I've looked into the contents again and Yoav's blog post is no longer available, even on the Techcommunity site. There are areas for improvement on this doc as well, not just the broken link but some md syntax are not working. I will request someone from the Windows content writing team to fix the cosmetic issues.

As regards to the accuracy of the documentation, I've seen you've been updating the Techcommunity about the issues with the Start Menu. Did you get an update from Support recently on customized Start menus? 

> Microsoft Edge tile logos won't appear on secondary tiles because they aren't stored in Surface Hub.

As per *Jeanie* and the feedback from the product team, the above is still considered *true* and the behavior you've experienced may be a *bug* unless you have confirmed recently that it is *working as designed*? Please keep us posted here. I also think your experience and expertise with regard to Surface Hub can help us improve this documentation. If you have a working XML file, how about opening a pull request here to include that? Thanks and looking forward to hearing from you.

**Comment by danieldhudson** [comment] 2019-07-18 03:45
Hi @jvsam. You'll have to forgive me for not opening a pull request, I've never used github before!

Here's a copy of my XML for our custom start menu (excluding the URL which I've changed to a placeholder):

<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
  <LayoutOptions StartTileGroupCellWidth="8" />
  <DefaultLayoutOverride>
    <StartLayoutCollection>
      <defaultlayout:StartLayout GroupCellWidth="8">
        <start:Group Name="">
          <start:SecondaryTile AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" TileID="34841030920" DisplayName="User Guide" Size="2x2" Column="2" Row="0" Arguments="-contentTile -formatVersion 0x00000003 -pinnedTimeLow 0xb733a3b6 -pinnedTimeHigh 0x01d3911b -securityFlags 0x00000000 -tileType 0x00000000 -url 0x0000006d https://www.contoso.com" Square150x150LogoUri="ms-appx:///Assets/MicrosoftEdgeSquare150x150.png" Wide310x150LogoUri="ms-appx:///" ShowNameOnSquare150x150Logo="true" ShowNameOnWide310x150Logo="false" BackgroundColor="#34414D" ForegroundText="light" />
          <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
		  <start:Tile Size="2x2" Column="4" Row="0" AppUserModelID="microsoft.microsoftskydrive_8wekyb3d8bbwe!App" />
          <start:Tile Size="2x2" Column="0" Row="2" AppUserModelID="Microsoft.Office.PowerPoint_8wekyb3d8bbwe!Microsoft.pptim" />
		  <start:Tile Size="2x2" Column="2" Row="2" AppUserModelID="Microsoft.Office.Word_8wekyb3d8bbwe!Microsoft.Word" />
		  <start:Tile Size="2x2" Column="4" Row="2" AppUserModelID="Microsoft.Office.Excel_8wekyb3d8bbwe!Microsoft.Excel" />
		  <start:Tile Size="2x2" Column="0" Row="4" AppUserModelID="Microsoft.MSPaint_8wekyb3d8bbwe!Microsoft.MSPaint" />
		  <start:Tile Size="2x2" Column="2" Row="4" AppUserModelID="VideoLAN.VLC_paz6r1rewnh0a!App" />
		  <start:Tile Size="2x2" Column="4" Row="4" AppUserModelID="Microsoft.WindowsMaps_8wekyb3d8bbwe!App" />
		</start:Group>
      </defaultlayout:StartLayout>
    </StartLayoutCollection>
  </DefaultLayoutOverride>
</LayoutModificationTemplate>

The key variable is this one: Square150x150LogoUri="ms-appx:///Assets/MicrosoftEdgeSquare150x150.png"

Even in the latest cumulative update for Windows 10 Team, completing this variable with the PNG location will show the Edge tile logo, as per my original images.

**Comment by jvsam** [comment] 2019-07-28 05:35
That's okay @danieldhudson, have you managed to try it though? Here's a good resource if you are interested in [contributing](https://docs.microsoft.com/en-us/contribute/git-github-fundamentals) in the future. 

Hi again @levinec just following up. You've mentioned on another issue that the Surface docs were assigned to you, but will you be able to assist and confirm if this note on the doc is still accurate?

> Microsoft Edge tile logos won't appear on secondary tiles because they aren't stored in Surface Hub. The default value for ForegroundText is light; you don't need to include ForegroundText in your XML unless you're changing the value to dark.

It was confirmed last year by @jdeckerms (thank you Jeanie!) but as per the testing done by Daniel, it's not the case anymore.  Hoping you can help us and clarify so we will now how to move forward with this issue. Thanks again.

**Comment by jvsam** [comment] 2019-08-04 05:34
> I would say that, as per my testing, the note on the documentation is wrong. Completing the variable for Edge tile logos works fine on Surface Hub, suggesting that the logos are indeed stored in Surface Hub.

Hi again @levinec just following up if you have any feedback on this. If the Product team can confirm if the below information is still accurate, then can we consider this as a bug? Thank you and hoping to hear from you.

> Microsoft Edge tile logos won't appear on secondary tiles because they aren't stored in Surface Hub. The default value for ForegroundText is light; you don't need to include ForegroundText in your XML unless you're changing the value to dark.

**Comment by levinec** [comment] 2019-08-05 23:02
Hi Jo,

I’ve reached out to the product team but haven’t heard back. Will ping them again!

Best,
Beth

**Comment by jvsam** [comment] 2019-08-07 13:16
Thanks for staying on top of this @levinec, we appreciate it. Kindly let us know when you hear back from the product team. Regards!

**Comment by levinec** [comment] 2019-08-16 17:29
fixed and verified by @robmazz

**Closed by levinec** 2019-08-16 17:29 UTC
Labels: assigned-to-author, devices

**Comment by jvsam** [comment] 2019-08-17 11:57
> Microsoft Edge tile logos won't appear on secondary tiles because they aren't stored in Surface Hub. The default value for ForegroundText is light; you don't need to include ForegroundText in your XML unless you're changing the value to dark.

Hi again @danieldhudson we really appreciate your patience on this matter. I just want to inform you that the issue that you've reported has been fixed, as confirmed by @levinec. Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by illfated** [comment] 2019-08-17 13:12
I presume https://github.com/MicrosoftDocs/windows-itpro-docs/commit/dd94dfbf00f8b54a731abd4c37c2315d78e9480a is the relevant commit to this issue.
