### ISSUE TITLE
Need rights required by users of the Windows Analytics

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/windows-itpro-docs#1435] opened 2018-08-07 16:11 UTC
Documentation mentions user needs administrator rights to create the workspace, but doesn't include what rights the users need after the administrator rights are removed.  Would also like to see link/documentation of adding additional users to the workspace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7ce50b9-cb28-a5ba-58f9-010e69f4fde5
* Version Independent ID: a161fed8-151a-1eca-8663-93e9365877d2
* Content: [Upgrade Readiness requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-requirements)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-requirements.md)
* Product: **w10**
* GitHub Login: @jaimeo

**Comment by andreabichsel** [comment] 2018-08-09 16:39
@jaimeo, can you look into this?

**Comment by jaimeo** [comment] 2018-08-09 17:12
I can't quite tell what role exactly you mean by "user" here, but to look at it from the perspective of tasks:

- viewing Log Search data requires Log Analytics Reader permissions
- to edit the data (includes viewing it, of course) requires Log Analytics Contributor permissions
- Log Analytics Owners can do everything, of course

OMS documentation about user management is at https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-manage-access#manage-accounts-and-users

Also, OMS is moving to the Azure portal (see https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-oms-portal-transition)--once that transition is complete, we'll be updating the docs to hopefully clarify things further.

**Comment by e0i** [comment] 2019-04-08 14:07
@officedocsbot assign @e0i

**Comment by VLG17** [comment] 2019-08-20 13:41
@jandreacola After the administrator rights are removed, the rights that need to be assigned to the user account depend on what that user shoud do or not. It's not a general rule and will be different based on the scenario you are in. There will be users who don't need access to the workspace, users with read only access, users with contributor access (can do modifications) and so on.

Editing the permission level and adding new users to the Workspace, as with the majority of Azure resources will be done through the Access Control (IAM) blade. More details [here](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-azure-portal)

**Comment by e0i** [comment] 2019-09-09 19:21
Hello @jandreacola,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Closed by e0i** 2019-09-09 19:21 UTC
Labels: assigned-to-author, deployment, more info or example needed, upgrade
