### ISSUE TITLE
Edições suportadas

### ISSUE THREAD

**Issue by ThiagoSalatiel** [MicrosoftDocs/windows-itpro-docs#3825] opened 2019-05-27 20:51 UTC
Galera, existe um erro de tradução grave no texto. Aonde é mencionado as versões suportadas, no texto está escrito "Não há suporte para estas edições:". Favor corrigir, pois pode causar uma bela confusão em pessoas leigas no produto.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: bc999894-2a0a-bc87-7fd7-97df5f1fd04e
* Version Independent ID: ad68f62a-6bf0-5f5f-bb07-f64afe68fd10
* Content: [Requisitos do Windows Autopilot](https://docs.microsoft.com/pt-br/windows/deployment/windows-autopilot/windows-autopilot-requirements#feedback)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by illfated** [comment] 2019-05-27 20:59
Na sua opinião, seria melhor usar "versões"?

**Comment by ThiagoSalatiel** [comment] 2019-05-27 21:05
Hello Trond, how are you?

                In my opinion, is better that u use “Versões suportadas”. Who translate that to Portuguese – Brazil, wrote wrong. They wrote like “Don’t has support to these versions”. So, the correct in pt-BR should be: “Há suporte para estas versões” that’s the same of “Has support to these versions”.

Reggard,

De: Trond B. Krokli <notifications@github.com>
Enviada em: Monday, May 27, 2019 5:59 PM
Para: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Thiago Salatiel <thiagosalatiel@msn.com>; Author <author@noreply.github.com>
Assunto: Re: [MicrosoftDocs/windows-itpro-docs] Edições suportadas (#3825)


Na sua opinião, seria melhor usar "versões"?

**Comment by illfated** [comment] 2019-05-27 21:17
Hello, Thiago, I am fine, thank you. I hope you are well too. 😃

Because this is a Localisation issue, we ordinary users do not have access to offer Pull Requests to correct or improve the translations, because those pages are not (yet) available here on Github (although it is under consideration, if I understood it correctly, in one of the Japanese issue pages). I do not know who among the Microsoft Docs team manages the translation issues when it comes to Portuguese, but maybe @dongmicro might know who would be available for this.

For now, we just have to wait for one of the Microsoft Docs team issue moderators to start following up on your report. 👍

**Comment by e0i** [comment] 2019-05-30 14:45
@dongmicro Please advise regarding this specific Portuguese translation issue. Thanks.

**Comment by e0i** [comment] 2019-07-17 13:56
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment] 2019-07-31 12:14
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment] 2019-08-01 20:24
@officedocsbot unassign @dongmicro

**Comment by e0i** [comment] 2019-08-12 19:09
@TinaMcN Would you be able to help with this Portuguese translation issue? Thanks.

**Comment by TinaMcN** [comment] 2019-08-12 23:14
@ThiagoSalatiel Obrigado pelo feedback.  O artigo foi traduzido por máquina.  Enviei para tradução humana.  Isso pode levar algumas semanas para ser concluído.  (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  This may take a few weeks to complete.)

**Comment by ThiagoSalatiel** [comment] 2019-08-21 15:37
@TinaMcN Thank you for your time and concern. Just a suggestion about this issue, Microsoft should have a better and easy way to receive this kind of suggestions and appointments about the translations. If you can suggest that form them, it will be great!

Thank you and regards.

**Comment by ThiagoSalatiel** [comment] 2019-08-21 15:38
@TinaMcN Thank you for your time and concern. Just a suggestion about this issue, Microsoft should have a better and easy way to receive this kind of suggestions and appointments about the translations. If you can suggest that form them, it will be great!

Thank you and regards.

**Comment by ThiagoSalatiel** [comment] 2019-08-21 15:40
Sorry, I closed this case accidentally.

**Comment by TinaMcN** [comment] 2019-08-21 19:54
@ThiagoSalatiel Thank you for your suggestion.  I totally agree that we need a better way to gather translation feedback on the Docs content.   I do hope to implement the Feedback control on the localized Windows content (like the one on the Azure content e.g. https://docs.microsoft.com/pt-br/azure/backup/quick-backup-vm-portal).  I just took over managing the localized Windows content recently, it will take some time to get such a process set up to manage the flow of that feedback in multiple languages.   In the meantime feel free to reach out to me if you have any other feedback.  Regards,
Tina

**Comment by TinaMcN** [comment] 2019-10-18 23:31
@ThiagoSalatiel O artigo é agora humano traduzido e o problema parece ser corrigido.  Por favor, verifique se ele está corrigido.  Obrigado novamente para o feedback.
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by ThiagoSalatiel** [comment] 2019-10-21 14:09
Hello Tina, how are you doing?

                Actually, it wasn’t fixed yet. As we can see in this pictures, we have this mention in English “The Following editions are supported”. So, we can understand that those version is ok for this feature.


English version:

[cid:image007.png@01D587FF.F882CE70][cid:image001.png@01D587FF.60757BA0]
Link: https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements

                In Portuguese (Brazil) version, still the same translation yet. So, we have this mention “Não há suporte para estas edições”. If we translate this to english, we’ll have “These editions are not supported”


[Wrong][cid:image010.png@01D587FF.F882CE70][cid:image011.png@01D587FF.F882CE70][cid:image002.png@01D587FF.60757BA0]
Link: https://docs.microsoft.com/pt-br/windows/deployment/windows-autopilot/windows-autopilot-requirements


Thank you for your reply and support.

Regards.

Thiago Salatiel
Cel.: +55 11 94055-4847 [Nextel]


De: Tina McNaboe <notifications@github.com>
Enviada em: Friday, October 18, 2019 8:32 PM
Para: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Thiago Salatiel <thiagosalatiel@msn.com>; Mention <mention@noreply.github.com>
Assunto: Re: [MicrosoftDocs/windows-itpro-docs] Edições suportadas (#3825)


@ThiagoSalatiel<https://github.com/ThiagoSalatiel> O artigo é agora humano traduzido e o problema parece ser corrigido. Por favor, verifique se ele está corrigido. Obrigado novamente para o feedback.
(The article is now human translated and the issue appears to be fixed. Please verify that it is fixed. Thanks again for the feedback.)

**Comment by TinaMcN** [comment] 2019-10-21 19:33
Hi Thiago, oh dear, the translators must have overlooked that, it's a really bad mistranslation!   I created a bug for them to fix it.  Thanks for checking it again.  Hopefully it will be fixed very soon.  Regards, Tina

**Comment by TinaMcN** [comment] 2019-11-07 23:40
Hi @ThiagoSalatiel the issue is now fixed.  Thanks again for reporting it, it was a great catch!   Let us know if you notice any other translation issues.
![image](https://user-images.githubusercontent.com/53281468/68437137-ebac6780-0174-11ea-8aab-d99da8a93540.png)

**Comment by ThiagoSalatiel** [comment] 2019-11-08 02:24
Hello Tina!

Thank you for your support on this issue!!!! Now, the document is ok!

Regards.

Thiago Salatiel
Cel.: +55 11 94055-4847 [Nextel]


De: Tina McNaboe <notifications@github.com>
Enviada em: Thursday, November 7, 2019 8:41 PM
Para: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Thiago Salatiel <thiagosalatiel@msn.com>; Mention <mention@noreply.github.com>
Assunto: Re: [MicrosoftDocs/windows-itpro-docs] Edições suportadas (#3825)


Hi @ThiagoSalatiel<https://github.com/ThiagoSalatiel> the issue is now fixed. Thanks again for reporting it, it was a great catch! Let us know if you notice any other translation issues.
[image]<https://user-images.githubusercontent.com/53281468/68437137-ebac6780-0174-11ea-8aab-d99da8a93540.png>

**Comment by TinaMcN** [comment] 2019-11-08 04:59
@officedocsbot please close

**Comment by illfated** [comment] 2019-11-08 14:15
@e0i : This issue ticket is ready to be closed (see above).

**Closed** 2019-11-08 14:22 UTC
Labels: localization
