### ISSUE TITLE
As of May 2018, this info is almost two years out of date

### ISSUE THREAD

**Issue by mcbsys** [MicrosoftDocs/windows-itpro-docs#926] opened 2018-05-17 16:04 UTC
The latest version of Windows 10 referenced in this article is 1607. We have since had 1709 and 1803. The Group Policy "Computer Configuration > Policies > Administrative Templates > Windows Components > Windows Update > Defer Windows Updates" no longer exists. The terms "Current Branch" and "Current Branch for Business" is no longer used. The maximum deferral has changed.

The little box at the top of the article mentions naming changes but does not address all the other inaccuracies. Please re-write the documentation to match the current product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e692b1-8354-6b09-dfd7-252585320aac
* Version Independent ID: d1c99e74-66df-760a-39e9-23e5ed2bcfec
* Content: [Walkthrough use Group Policy to configure Windows Update for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wufb-group-policy)
* Content Source: [windows/deployment/update/waas-wufb-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-wufb-group-policy.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment] 2018-08-21 23:32
@jaimeo - can you please take a look ?

**Comment by jaimeo** [comment] 2018-08-29 17:47
We are working on updates to this content right now.

**Comment by DaniHalfin** [comment] 2018-09-26 22:44
@shortpatti could you please reassign to @jaimeo ? Thanks.

**Comment by seamonkey420** [comment] 2018-12-05 21:00
and now been 3 months since someone confirmed this was being updated... so... bueller.. bueller?

**Comment by jaimeo** [comment] 2018-12-05 21:03
Thanks for the reminder; I'll ping our PMs again.

**Comment by seamonkey420** [comment] 2018-12-05 22:03
Also, there should be an added note about the Telemetry settings for those of us w/business versions of Windows 10 and Windows Updates; that setting it to 0 nullifies all GPO settings and lets the clients use the internet to check for updates vs specifically using ONLY WSUS servers.

**Comment by jaimeo** [comment] 2018-12-05 22:06
Thanks. We just published updates to the other WUfB topics; this one is next on the list, so I'll add this to our update details to include.

**Comment by seamonkey420** [comment] 2019-01-02 18:31
And its been another month since promising updates to this one page.  perhaps microsoft needs to slow its feature releases so it can keep its own documentation up to date? I'm trying to get 1809 to only get updates from WSUS but still allow users to use the microsoft store; i was able to do this without any issues on 1607 to 1803 but now on 1809, i notice my test 1809 machine is getting updates from microsoft even with policies set per recommendation..   Also premier support just sucks these days.. literally have no historical knowledge of Windows and just doesn't care.

**Comment by R2D2components** [comment] 2019-02-20 14:52
Stop stop please stop . What ever changes that were made have severely compromised the security parameters of the computer and devices please revert the activity to it nor
Al state this device has been compromised and I need any and all information that is possible to pursue this indivisible. Please contact me
As soon as possible

Jason Robertson

**Comment by mypil** [comment] 2019-03-20 18:41
@jaimeo - Do you have any updates on the progress of this?

**Comment by jaimeo** [comment] 2019-03-20 18:55
Look for further updates soon in conjunction with the next release of Windows 10.

**Comment by mypil** [comment] 2019-03-25 07:53
@mcbsys - Thank you for engaging with the community here for the docs.

From our understanding, the issue you raised has been answered by jaimeo. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-03-25 07:53
@officedocsbot close

**Closed by mypil** 2019-03-25 07:53 UTC
Labels: deployment, update
