### ISSUE TITLE
More details regarding TPM device attestation issue

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/windows-itpro-docs#4310] opened 2019-07-01 16:51 UTC
Regarding "issues with TPM device attestation in Windows 10, version 1809." please provide references for the issue and/or more description of the problem. Customers have been impacted by this and are asking for more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6867cc8c-868d-d472-8aa5-1ed5b94ced2c
* Version Independent ID: 6822e12d-7474-9e49-1e8b-88f7eec3b22c
* Content: [Windows Autopilot Self-Deploying mode](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/self-deploying)
* Content Source: [windows/deployment/windows-autopilot/self-deploying.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment] 2019-07-02 09:28
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-07-02 12:53
@aaronstackpole - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment] 2019-07-08 05:45
@aaronstackpole . More information about TPM  key device attestation .
**https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/tpm-key-attestation**

**Comment by aaronstackpole** [comment] 2019-07-08 05:48
I appreciate the link which describes what TPM Device Attestation is, note that this article does not explain why Windows 10 LTSC is no longer supported due to an issue with TPM Device Attestation. Please provide a link that describes the issue which makes this feature only work with the latest version of Windows 10 (1903) and will TPM Device Attestation work with this edition in six months?

**Comment by RAJU2529** [comment] 2019-07-08 05:58
@aaronstackpole . Reason is simple, win 10 LTSC might does not have the TPM device attestation policy. 
Moreover device must be joined with intune or azure subscription.
I seen same policy in v1809 and 1903.

**Comment by aaronstackpole** [comment] 2019-07-08 10:56
Correct, however that was changed about three weeks ago and it threw a three month process out a week before deployment and we want to know what changed because now we have to pay an extra $25,000 a year to use an edition of Windows 10 that supports this feature. Additionally we want to know if we select this edition will it still work in three months?

Sent from mobile
________________________________

**Comment by RAJU2529** [comment] 2019-07-08 11:04
@aaronstackpole . For your current question, only article author and practical experienced users can give answer . Let wait for few days.

**Comment by joinimran** [comment] 2019-07-09 18:44
Hello @greg-lindsay , Can you please share your insight on the query by @aaronstackpole .

@aaronstackpole Can you please share what issues you are facing?

**Comment by greg-lindsay** [comment] 2019-07-12 19:20
We have no link or other description available.  The problem is exactly as stated. There are issues. In other words, it doesn't work some of the time. It's a bug in how device attestation works in 1809, and it's fixed in 1903.

**Closed by greg-lindsay** 2019-07-12 19:20 UTC
