### ISSUE TITLE
Use CSP page conventions on the BitLocker CSP page

### ISSUE THREAD

**Issue by tr5tn** [MicrosoftDocs/windows-itpro-docs#4918] opened 2019-09-11 14:32 UTC
A number of other CSP pages have improved structure for the HTML content relative to this page. For instance, the [SmartScreen CSP page](https://docs.microsoft.com/en-gb/windows/client-management/mdm/policy-csp-smartscreen) uses comments really effectively to partition the content within each section such as these elements: 

```
<!--Policies-->
<!--Policy-->
<!--SupportedSKUs-->
<!--Scope-->
<!--Description-->
<!--ADMXMapped-->
<!--SupportedValues-->
```

All of this seems to vaguely match up with the DDF files. 

Although there are many inconsistencies across the CSP pages, this specific page stands out for its differences.

**Comment by illfated** [comment] 2019-10-05 16:48
Which one of the docs.microsoft.com pages is this about? It does not appear to be about the SmartScreen CSP page you have mentioned as an example.

**Comment by illfated** [comment] 2019-10-05 17:07
I am not sure if I can contribute with anything for this page yet, so it would be really helpful with a comment from the document author or one of the MS Docs team members experienced in this.

**Comment by tr5tn** [comment] 2019-10-07 14:23
> Which one of the docs.microsoft.com pages is this about? It does not appear to be about the SmartScreen CSP page you have mentioned as an example.
> 
> edit: Sorry, it took me a while to visit your other issue ticket page and notice that we have talked about this same issue, but concerning AppLocker instead of BitLocker.
> I presume we are talking about the following pages:
> 
> https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp
> https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bitlocker-csp.md
> 
> 
> Ref. issue ticket #4919 (The AppLocker CSP page is really unconventional)

Yeah, the SmartScreen CSP was an example of the desirable usage of the tags. Most CSP pages that I'm looking at seem to follow that pattern, which more or less aligns to the DDF file structures. The BitLocker CSP page that you link to above is miles off that though. Adopting these conventions on this reasonably complex page would be extremely helpful for parsing.

**Comment by tr5tn** [comment] 2019-10-16 14:06
Any updates on this please? The relatively trivial addition of comments to the BitLocker page would be extremely helpful. Examples in the post at the top.

**Comment by illfated** [comment] 2019-10-16 14:31
@e0i : Please assign a suitable team member (or yourself) to follow up on this ticket. 👍 🙈 🙉 🙊

**Comment by e0i** [comment] 2019-10-17 00:03
@tr5tn @illfated 

The issue is under investigation. Thank you.

**Comment by joinimran** [comment] 2020-01-18 16:26
@tr5tn , Looks like the BitLocker CSP page is setup as desired and as per CSP pages conventions. https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp 

Thanks
Imran

**Comment by tr5tn** [comment] 2020-01-27 15:53
> @tr5tn , Looks like the BitLocker CSP page is setup as desired and as per CSP pages conventions. https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp
> Thanks
> Imran

Hi Imran, 

I don't see any of those comments? 

Cheers, 

Tristan

**Comment by joinimran** [comment] 2020-01-29 10:51
@tr5tn , Can you please point out the stuff that is missing to give me more understanding regarding this document.

**Comment by tr5tn** [comment] 2020-01-31 17:04
@joinimran if you refer to the SmartScreen CSP page that I link in my original post and view the Source you will see that the content is partitioned using comments that basically align to the structure of the DDF files. If you search for comments such as these you will see what I mean: 









These tags comments very useful for parsing the content and are used widely, but these tags are not used on the BitLocker CSP page. Given the complexity of the BitLocker page this is one of the pages that would benefit most from these comments.

**Comment by denisebmsft** [comment] 2020-02-25 21:28
Greetings! Thank you @tr5tn for raising this question. And thank you, @illfated and @joinimran for your help with this. The comments noted as desirable that are in the SmartScreen CSP article (https://docs.microsoft.com/windows/client-management/mdm/policy-csp-smartscreen) are not actually standard conventions in our workgroup. This is why you are seeing those comments in some articles but not all (the BitLocker article, for example, https://docs.microsoft.com/windows/client-management/mdm/bitlocker-csp). I know this issue has been open for more than a couple of weeks, but please give us a few more days to circle back on this. We're discussing as a team and will follow up soon.

**Comment by e0i** [comment] 2020-03-13 13:32
@denisebmsft Please let us know of any developments regarding this issue. Thank you.

**Comment by denisebmsft** [comment] 2020-07-09 02:02
Hi all, I am going to close this as "won't fix" for now.

**Closed by denisebmsft** 2020-07-09 02:02 UTC
Labels: client management, to-triage

**Comment by tr5tn** [comment] 2020-07-10 13:11
I just checked the page and it appears that it appears to align with the request now!?!?

**Comment by illfated** [comment] 2020-07-10 13:40
Maybe this was fixed by the pull request #6013 in February, although I am not 100% sure what you mean when you say "align with the request".

**Comment by tr5tn** [comment] 2020-07-10 15:19
I mean that the content was changed to introduce the markings I requested, and chose not to use the word "fixed" because it wasn't broken per se. It wasn't "fixed" initially in February when I checked it then, but maybe that hadn't been published yet.

**Comment by joinimran** [comment] 2020-07-10 17:14
@tr5tn - I have created the Pull Request and mentioned all of the required markdowns.

Thanks.
