### ISSUE TITLE
Is Reboot needed

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/windows-itpro-docs#8575] opened 2020-11-03 14:36 UTC
It is not clear from the doc if a reboot is required when using the Intune policy rather than the custom CSP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b64219-4814-f414-e5fb-4bfa9be9a55f
* Version Independent ID: b1b2f9e2-912b-80e0-bee7-be41eaf9690f
* Content: [Deploy Windows Defender Application Control (WDAC) policies by using Microsoft Intune (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune.md)
* Product: **w10**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment] 2020-11-03 16:38
@thommck . I think its recommend to reboot is necessary.

**Comment by illfated** [comment] 2020-11-05 18:31
Based on the existing documentation, my impression is that the intention is to not require a reboot, unless the CSP is applied during OOBE.

You may want to safeguard the CSPs taking effect by planning a reboot when adding multiple CSPs.

**Comment by e0i** [comment] 2020-12-24 15:41
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Thank you.

**Closed by e0i** 2020-12-24 15:41 UTC
Labels: application control
