### ISSUE TITLE
Windows Hello, SCRIL and Pin Reset

### ISSUE THREAD

**Issue by iffarrukh** [MicrosoftDocs/windows-itpro-docs#5211] opened 2019-10-18 01:15 UTC
Hi
We are trialing Windows Hello for Business with goal to disable password completely with users restricting to login via Windows Hellow(by enabling   Smart card is required for interactive login) and remove password credential provider.

One thing we are struggling with is, how admins can reset the PIN if users forget their PIN. Right now if we enable PIN reset option for users and user try to reset the PIN, the reset screen asks for user password to verify the identity, but we have disabled the password credentials and by enabling the smart card is required options in user profiles, , Active Directory changes the affected user's password to a random 128 bits of data.. so there is no password anymore.

In short by enabling SCRIL and enforcing user to login via smart card/Windows Hello only, how admin/users can reset their PIN if forgotten.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment] 2019-10-18 19:44
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-11-03 05:31
Hello @iffarrukh, have you tried the recommendation on the doc to generate a new random 128 bit password?

> Although a SCRIL user's password never expires in early domains, you can toggle the SCRIL configuration on a user account **(clear the check box, save the settings, select the check box and save the settings) to generate a new random 128 bit password.**...

As for the Pin Reset Service, there are some requirements that you need to meet for it to work correctly. Have you looked at the [Windows Hello for Business deployment guide](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide) to re-check your implementation? If you are using Azure AD, please look at the Passwordless scenarios [here](https://docs.microsoft.com/azure/security/fundamentals/ad-passwordless) specifically the one where "[User manages their Windows Hello for Business credentials](https://docs.microsoft.com/azure/security/fundamentals/ad-passwordless#user-manages-their-windows-hello-for-business-credentials)."

For further troubleshooting, it will be best to open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community.

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation and we will submit it for review. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. 

Thank you.

**Comment by jvsam** [comment] 2019-11-03 05:52
Duplicate of #5213. Closing this issue. 

@officedocsbot close

**Closed by jvsam** 2019-11-03 05:52 UTC
