### ISSUE TITLE
PXE boot

### ISSUE THREAD

**Issue by Jeff-Jerousek** [MicrosoftDocs/windows-itpro-docs#5856] opened 2020-01-16 22:28 UTC
"PXE boot is not supported on Surface Pro X. For more information, refer to Deploying, managing, and servicing Surface Pro X."

The linked page says that PXE boot is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd6c1f5-529c-4b6a-6d70-6a091df10f3e
* Version Independent ID: df97fced-4167-f5d8-8643-50cbb1ba69e4
* Content: [Ethernet adapters and Surface deployment (Surface) - Surface](https://docs.microsoft.com/en-us/surface/ethernet-adapters-and-surface-device-deployment#feedback)
* Content Source: [devices/surface/ethernet-adapters-and-surface-device-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/ethernet-adapters-and-surface-device-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment] 2020-01-28 16:33
@Jeff-Jerousek The PR that addresses this issue has been merged and thus the issue is being closed. Thank you for your feedback.

**Closed by e0i** 2020-01-28 16:33 UTC
