### ISSUE TITLE
Office update with WUfB unclear

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#10921] opened 2022-10-06 10:41 UTC
In the **Quality updates** section you declare:
_Windows Update for Business also treats non-Windows updates (such as updates for **Microsoft Office** or Visual Studio) **as quality updates.**_

But in the **Microsoft product updates** section you declare:
_Updates for other Microsoft products, such as versions of **Office** that are installed by using Windows Installer (MSI). **Versions of Office that are installed by using Click-to-Run can't be updated by using Windows Update for Business**_

If MSI Office installation are considered as Microsoft products updates, and Office Click-to-Run installations can't be updated by using WUfB, what Office updates are included in Quality Updates?

Do Microsoft 365 Apps updates included in WUfB or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2056993d-a700-fba6-8982-e645b182eeea
* Version Independent ID: fb38a86a-cdf6-6fc2-8eb6-fd54f1599f55
* Content: [Windows Update for Business - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb)
* Content Source: [windows/deployment/update/waas-manage-updates-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-manage-updates-wufb.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by DoubNAT** [comment] 2022-11-07 23:26
I also would like clarity on this. And if Click-to-Run isn't included via WUfB, will there be plans to implement this in the future?

**Comment by dariomws** [comment] 2022-11-08 07:48
Hi @Martony78 and @DoubNAT, thank you for your feedback.

@aczechowski, I need your help/input here. I think we should remove this sentence from Quality updates. Could you confirm?

@DoubNAT, I don't think that C2R updates will be included in WUfB.

**Comment by aczechowski** [comment] 2022-11-11 00:21
I'm checking with the PM to confirm.

Regarding question from @DoubNAT I'll set expectations that we won't make any statements regarding potential future functionality. 😁

**Comment by aczechowski** [comment] 2022-11-15 22:53
@dariomws I confirmed with PM that Office 2016 updates in this way, but all later versions with C2R don't currently update with WUfB. Thanks for asking

**Comment by dariomws** [comment] 2022-11-16 07:46
@aczechowski, thanks!

Should we remove the mention to Office from Quality updates section?
"Windows Update for Business also treats non-Windows updates (such as updates for **Microsoft Office** or Visual Studio) as quality updates."

**Comment by aczechowski** [comment] 2022-11-16 17:46
At a minimum, yes. I'm not sure about Visual Studio, though. It's possible it's in the same situation as Office - it was at one time but no longer. It's been a while since I've used full VS, but I think it has its own update mechanism. So maybe let's just remove the entire example inside of the parentheses. 
thanks!

**Closed** 2022-11-17 18:15 UTC
Labels: deployment, writer-input-required
