### ISSUE TITLE
Registry details for exemptions seem incomplete

### ISSUE THREAD

**Issue by DFLiddle** [MicrosoftDocs/windows-itpro-docs#1733] opened 2018-10-02 15:55 UTC
The section "Guidance for accounts on shared PCs" indicates that accounts may be exempted from deletion if their SID is added to the registry, either manually or through a PowerShell command. The manual method does not specify the format for the entry in the registry key. How should it be entered? (I have been unsuccessful with my attempts to use the PowerShell command.) Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b376e2-39bd-faca-a76c-dd21bad8d8fd
* Version Independent ID: a76cabb0-59b9-7e97-6603-eec7d37f1fd4
* Content: [Set up a shared or guest PC with Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc#configuring-shared-pc-mode-on-windows)
* Content Source: [windows/configuration/set-up-shared-or-guest-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/set-up-shared-or-guest-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment] 2018-10-02 16:09
@DFLiddle Good question! I'll find the answer, reply to you here, and then update the topic.

**Comment by jdeckerms** [comment] 2018-10-03 13:28
@DFLiddle The engineering team would like to know what results you get when you use the PowerShell command. Does the PowerShell script itself throw an exception or present some similar type of overt failure? Or does the script succeed but then the expected behavior fails to arise?

**Comment by DFLiddle** [comment] 2018-10-03 14:06
I’m not a regular user of PowerShell, nor a very informed one, so please take everything I report with a grain of salt. That’s my first caveat.

My second caveat is that I don’t know what assumptions about accounts apply to this statement in the instructions: “The account management service supports accounts that are exempt from deletion."

When I apply the script, with my limited knowledge, I receive two errors:

`Unexpected token '$adminPass' in expression or statement.`
and
`Unexpected token 'iex' in expression or statement.`

This happens when I log in as a local administrator, open PowerShell, and type the command as written. The reported result occurs whether I enter the user name and password of an existing account or one that is to be created by the 'net user /add' command within the script.

Now, having written that, I am pleased to report that I seem to have figured out how the SID is to be entered in the registry—based on my reading of the script. It appears that the SID is to be entered simply as the name of a sub-key to 'Exemptions' and not as a value within it. Using this method produces the desired result, but I would appreciate it if someone in the know would confirm that it is correct.

Thank you all very much for your quick replies and attentiveness!

**Comment by jdeckerms** [comment] 2018-10-04 12:56
@DFLiddle Thanks for the details! I'm waiting for validation from the engineering team on your registry key solution and will let you know as soon as I get an answer.

**Comment by arpan3t** [comment] 2018-10-12 20:51
In case anyone is reading this thread having the above issue, here is the manual solution.  First note that I am running the latest version of Windows 10 Pro 17134, and I didn't have the exemptions key in my registry to begin with.  I used the ICD and created the provisioning package to deploy, so I am not sure why that key wasn't there.

Regardless, I created the Exemptions key under `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\SharedPC `
Then inside that key I created a new DWORD 32-bit value with the SID as the name and the value as 0
This will keep the account from being deleted at the set interval.

**Comment by jvsam** [comment] 2019-06-07 00:03
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-07-28 12:13
> Now, having written that, I am pleased to report that I seem to have figured out how the SID is to be entered in the registry—based on my reading of the script. It appears that the SID is to be entered simply as the name of a sub-key to 'Exemptions' and not as a value within it. Using this method produces the desired result, but I would appreciate it if someone in the know would confirm that it is correct.

Hello @DFLiddle hope all is well. I know it's been a while since this issue was opened so thank you for your patience. I just wanted to follow up to ask if you have suggestions—based on what you've experienced so far in using the docs—to improve the quality of this documentation? We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date so your feedback is appreciated, otherwise we can close this issue. 

Thank you as well @arpan3t for sharing that information. I am sure other users who'll stumble upon this thread will find that beneficial.  

Thank you both for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-08-04 08:43
Hi again @DFLiddle we didn’t hear back from you so I will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment] 2019-08-04 08:43
@officedocsbot close

**Closed by jvsam** 2019-08-04 08:43 UTC
Labels: assigned-to-author, configuration
