### ISSUE TITLE
Two links to the automation scripts at the top of the document are broken

### ISSUE THREAD

**Issue by rothschild86** [MicrosoftDocs/windows-itpro-docs#9153] opened 2021-02-16 14:27 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources#reset-windows-update-components-manually)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment] 2021-02-17 15:15
@rothschild86 . Same issue has been already esculated by other user with report #9104
This article already replied, he is working for new 
hosting location to update scripts.
so please close this again.

**Comment by illfated** [comment] 2021-02-21 21:12
Duplicate of #9104

#please-close

**Closed** 2021-02-22 20:15 UTC
Labels: deployment
