### ISSUE TITLE
Script link redirect

### ISSUE THREAD

**Issue by paulglavin** [MicrosoftDocs/windows-itpro-docs#10738] opened 2022-07-29 10:39 UTC
The location for the script links to https://gallery.technet.microsoft.com/Events-16962-16969-Reader-2eae5f1d 
This now redirects to https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=TechNet-Gallery however it does not seem to be possible to find the script in the new repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment] 2022-07-29 13:53
duplicate of #10726

**Closed by aczechowski** 2022-07-29 13:53 UTC
