### ISSUE TITLE
Full Disk Encryption vs Used Space Only

### ISSUE THREAD

**Issue by lXbalanque** [MicrosoftDocs/windows-itpro-docs#5754] opened 2019-12-27 18:17 UTC
Is it possible, through the use of these settings, to force Full Disk Encryption vs Used Space Only? I need to be able to force full disk encryption. I'm currently using a device configuration profile to apply BitLocker settings but it seems hit or miss whether it applies full disk encryption or used space only. I can apply the XTS-AES256 setting just fine but I need a foolproof method for applying full disk encryption every time during Autopilot setup.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment] 2019-12-29 19:44
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-12-29 20:05
Hi @lXbalanque, since this is a duplicate of #5755, we will close this and continue the conversation on the other issue that you have opened. Thank you.

**Comment by jvsam** [comment] 2019-12-29 20:06
@officedocsbot close

**Closed by jvsam** 2019-12-29 20:06 UTC
