### ISSUE TITLE
How can I identify which PCR bank is being used?

### ISSUE THREAD

**Issue by iweidner** [MicrosoftDocs/windows-itpro-docs#6036] opened 2020-02-12 08:21 UTC
Hi,
I try to find out, which PCR Banks are use on some of our computer (Windows 10 Enterprise with 1909 update).  The registry field TPMActivePCRBanks have the following values:
Computer 1 value: 1 (hex) 
Computer 2 value: 3 (hex)

The article goes on with: 

> Defines which PCR banks are currently active. (This value should be interpreted as a bitmap for which the bits are defined in the TCG Algorithm Registry Table 21 of Revision 1.27.).

When I look at table 21 in the linked document, I see the followin information:

> 6.10 Hash Algorithms Bit Field
This table defines a bit field to concisely convey a set of hash algorithms. An example of where
this could be useful is a parameter returning the set of hash algorithms an interface supports.
Table 21 — Definition of (UINT32) TPMA_HASH_ALGS Bits
Bit Name Action
0 hashAlgSHA1 SET (1): indicates the SHA1 hash algorithm
CLEAR (0): does not indicate SHA1
1 hashAlgSHA256 SET (1): indicates the SHA256 hash algorithm
CLEAR (0): does not indicate SHA256
2 hashAlgSHA384 SET (1): indicates the SHA384 hash algorithm
CLEAR (0): does not indicate SHA384
3 hashAlgSHA512 SET (1): indicates the SHA512 hash algorithm
CLEAR (0): does not indicate SHA512
4 hashAlgSM3_256 SET (1): indicates the SM3_256 hash algorithm
CLEAR (0): does not indicate SM3_256
31:5 Reserved Shall be zero

I don't know how this table help me to find out which PCR bank is being used?

Or is it so simple that I convert the HEX value into a binary number and use the bits to read which PCR Bank is active?
Example:
HEX 3 =  0011 = PCR Bank 0 and 1 active?

Best regards
Ingo Weidner
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ef76ba-7de8-11f1-f5aa-fc8b35d2c83e
* Version Independent ID: 27cc94ab-ee9d-39e0-c11b-dc32e576a0aa
* Content: [Understanding PCR banks on TPM 2.0 devices (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/switch-pcr-banks-on-tpm-2-0-devices)
* Content Source: [windows/security/information-protection/tpm/switch-pcr-banks-on-tpm-2-0-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/switch-pcr-banks-on-tpm-2-0-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment] 2020-02-13 15:56
Hello, @-

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by VLG17** [comment] 2020-03-17 18:41
@iweidner Hello Ingo, you are correct with your reasoning. In my case the HEX Value is 2 so i only have PCR Bank 1 active, meaning hashAlgSHA256.

This is confirmed also by looking at the value of "TPMDigestAlgID" which is in my case 0x0000000b which translates to "the SHA 256 algorithm" according to the TCG_Algorithm_Registry_Rev_1.27_FinalPublication.

![image](https://user-images.githubusercontent.com/41186174/76890249-acfb8c00-688f-11ea-8cf5-42111c1b38f4.png)

**Comment by e0i** [comment] 2020-04-08 21:20
The issue is being closed as the original question have been answered via the above comment. Thank you.

**Closed by e0i** 2020-04-08 21:20 UTC
Labels: information protection
