### ISSUE TITLE
Copy-Item : A positional parameter cannot be found that accepts argument '/Y'.

### ISSUE THREAD

**Issue by bdbais** [MicrosoftDocs/windows-itpro-docs#6846] opened 2020-05-31 09:30 UTC
[Enter feedback here]

mountvol X: /s
copy %WINDIR%\System32\SecConfig.efi X:\EFI\Microsoft\Boot\SecConfig.efi /Y
bcdedit /create {0cb3b571-2f2e-4343-a879-d86a476d7215} /d "DebugTool" /application osloader
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} path "\EFI\Microsoft\Boot\SecConfig.efi"
bcdedit /set {bootmgr} bootsequence {0cb3b571-2f2e-4343-a879-d86a476d7215}
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} loadoptions DISABLE-LSA-ISO
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} device partition=X:
mountvol X: /d
---------------

give me error:

Copy-Item : A positional parameter cannot be found that accepts argument '/Y'.
At line:1 char:1
+ copy %WINDIR%\System32\SecConfig.efi X:\EFI\Microsoft\Boot\SecConfig. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#turn-off-with-hardware-readiness-tool)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2020-05-31 11:17
Please read the documentation very closely. _The script is not supposed to be run in PowerShell._

4. Delete the Windows Defender Credential Guard EFI variables by using bcdedit. **From an elevated command prompt**, type the following commands:

Use `cmd.exe` and make sure to Run as Administrator ... to make the script work.

Please also make sure that the computer you run the command on is compatible with **Device Guard** and **Virtualization Based Security**. Too many users complain about the script not working, without checking of the computer they run the script on actually supports the feature. The problem is too often with the end user equipment and lack of verification before running the script.

**Comment by RAJU2529** [comment] 2020-05-31 16:02
All commands are worked . I have tested Many times.  NO issues .

**Comment by e0i** [comment] 2020-05-31 16:37
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Feel free to re-open this issue if you feel there is something needed to be updated within the article itself.

Thank you.

**Closed by e0i** 2020-05-31 16:37 UTC
