### ISSUE TITLE
M365 Business

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#3991] opened 2019-06-11 14:32 UTC
I believe this article should be updated to include M365 "Business" licenses, but if for some reason this isn't the case, that should be called out as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment] 2019-06-11 20:59
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-07-18 19:13
@greg-lindsay Would you be able to provide further directions for this issue in coming up with content changes? Thank you.

**Comment by e0i** [comment] 2019-08-01 17:15
@greg-lindsay We need authoritative input regarding whether license should be added to the document to move forward with this issue. Thanks.

**Comment by e0i** [comment] 2019-08-19 10:31
@Mike-Crowley The issue is still under investigation and you will be followed up with updates. Thanks.

**Comment by greg-lindsay** [comment] 2019-08-19 18:56
We are discussing this request internally and will make the necessary updates when the issue is resolved. I'm closing this issue for now.

**Closed by greg-lindsay** 2019-08-19 18:56 UTC

**Comment by greg-lindsay** [comment] 2019-08-20 21:42
Sorry, it appeared there was an MSFT logo on the original poster's avatar and his name was the same as an MSFT employee so I mistakenly thought I was forwarding the issue internally.

M365 Business license activates the Windows Business subscription, which is different from the Windows Enterprise subscription. But this license is not always purchased standalone so it gets complicated. I will try to follow up with licensing experts to get more details about this scenario if I can.

**Comment by Mike-Crowley** [comment] 2019-09-24 03:52
> 
> 
> Sorry, it appeared there was an MSFT logo on the original poster's avatar and his name was the same as an MSFT employee so I mistakenly thought I was forwarding the issue internally.
> 
> M365 Business license activates the Windows Business subscription, which is different from the Windows Enterprise subscription. But this license is not always purchased standalone so it gets complicated. I will try to follow up with licensing experts to get more details about this scenario if I can.

Greg, any update here? Its nuts that M365 Business is nearly a year old and we don't have documentation on how the Win10 part works. We've got technical support, for example, telling us that to use the license we must upgrade from windows 7 and that Win10 will never activate properly, if a hard drive fails (unless you reinstall Win7). I'm hoping this isn't correct, but there isn't any documentation...
