### ISSUE TITLE
Screenshot/description inconsistency

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-itpro-docs#6019] opened 2020-02-08 13:45 UTC
The screenshot does not match the *Use the following restricted mode* options described in step 3.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c826587d-2e65-083f-254d-75f188158f08
* Version Independent ID: 746596b5-c1df-9ea0-abcc-f6ff97874e40
* Content: [Protect Remote Desktop credentials with Windows Defender Remote Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-gb/windows/security/identity-protection/remote-credential-guard#feedback)
* Content Source: [windows/security/identity-protection/remote-credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/remote-credential-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment] 2020-02-11 16:47
@andrewwillett

The issue is under investigation. Thank you for the feedback.

**Comment by RAJU2529** [comment] 2020-02-13 06:12
. I confirmed the same optionsis  in Windows 10 preview .

**Comment by VLG17** [comment] 2020-03-23 18:33
Hi @andrewwillett, could you please let us know what exactly is missing? An explicit description for "Restrict Credential Delegation"? We could add that under step 3, although it's in the screenshot itself.

My understanding is that the screenshot shows the 3 options and because one of them is already selected (and described in the screenshot itself) it goes on to talk about other 2 options under step 3.

**Comment by e0i** [comment] 2020-05-13 15:39
Closing via #6415. ]

**Closed by e0i** 2020-05-13 15:39 UTC
Labels: identity protection
