### ISSUE TITLE
Allow does not guarantee remediation, and is not a whitelist action.

### ISSUE THREAD

**Issue by swellhunter** [MicrosoftDocs/windows-itpro-docs#8671] opened 2020-11-19 10:11 UTC
"Allow on device" results in a message that the file (I have a lot of copies of one detected as Trojan:JS/Sillyexpl) will never be remediated.
Detection does continue, especially after updates, and every detection carries a risk of remediation ?  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3963966b-1da0-0a54-dce4-ec10079cc61a
* Version Independent ID: cb30333a-e944-0cb1-a920-4efce2a922da
* Content: [What to do with false positives/negatives in Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/antivirus-false-positives-negatives)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/antivirus-false-positives-negatives.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/antivirus-false-positives-negatives.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment] 2021-01-25 07:55
@swellhunter Why do you want to go with "Allow on device" for the file detected as Trojan:JS/Sillyexpl? This is a valid thread, more details [here](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:JS/Sillyexpl).

Or the problem is that this threat was already identified and remediated in the past, but it still comes up although it's not there anymore?

In that case you can reference the steps described [here](https://answers.microsoft.com/en-us/protect/forum/all/windows-defender-identifies-the-same-pup-as-a/63f17794-3815-4784-b9cd-c6059c8e0828), to get rid of false positives.

Keep in mind that we can help with documentation issues, so if you feel that we need to add or change something regarding the article you shared, please let us know. For technical issues, please reach out to [Windows support](https://support.microsoft.com/contactus).

**Comment by swellhunter** [comment] 2021-01-26 00:16
@VLG17 The file concerned exists in multiplke places and also about 20 times in a very large zip file. I do not (did not) want the file corrupted. Nor do I want the zip file changed. I don't want to whitelist the threat, just the file. It is a validly archived file. It is not a trojan.  My issue is that every time I take a new Windows update, it needs to be manually dealt with again and this is tedious, especially since I have been promised that it would not be actioned in future.  Sadly I think this means storing it elsewhere now.  Thank you for your links in any case.

**Comment by VLG17** [comment] 2021-02-04 10:38
@swellhunter Thank you for coming back with more details. If there is anything you feel that we should add/change related to the linked artice, please let us know.

If installing a new Windows update changes your current configuration, i still think it's worth reaching out to support (link provided in previous reply) to have them look into this and at least confirm if it's normal or not, and if there is something that can be done about it.

**Comment by denisebmsft** [comment] 2021-02-08 21:26
Thank you @swellhunter for the feedback, and @VLG17 for your help. I am going to close this issue for now; however, please let us know if there are any other issues or questions pertaining to the documentation. A lot of updates have been done over the past month, and I think we've addressed the changes that needed to be made. But do let us know if we missed something.

**Closed by denisebmsft** 2021-02-08 21:26 UTC
Labels: antivirus
