### ISSUE TITLE
Event Type information would be great.

### ISSUE THREAD

**Issue by Jonathan0Doe** [MicrosoftDocs/windows-itpro-docs#1726] opened 2018-10-02 10:42 UTC
This is a really nice overview of events associated with ipsec. It would be great, if the event type (like success or failure) information would be added to the event ids. 

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9cd4539-eb4d-9d25-47fa-9f93b2584836
* Version Independent ID: 3a63fc40-b2ee-a73b-fe9b-9affac85dee0
* Content: [Audit IPsec Extended Mode (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-ipsec-extended-mode)
* Content Source: [windows/security/threat-protection/auditing/audit-ipsec-extended-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/audit-ipsec-extended-mode.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by shortpatti** [comment] 2018-10-02 15:12
Closing. Duplicate of [1728](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1728)

**Closed by shortpatti** 2018-10-02 15:12 UTC
