### ISSUE TITLE
Troubleshooting guide missing

### ISSUE THREAD

**Issue by MVDB1984** [MicrosoftDocs/windows-itpro-docs#5423] opened 2019-11-13 08:45 UTC
Hi,
We followed the "Windows Hello for Business Deployment Guide" step by step, this for the scenario "Hybrid Azure AD Joined with Key Trust Deployment", Pin registration works perfectly, but the authentication fails...
I checked also the "how windows Hello for Business Works" "technical deepdive" segment of this documentation, as well as the FAQ, but nowhere I could find decent troubleshooting information. 
Seems this information is missing from the "Windows Hello for Business" documentation.

Can this documentation be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ecd7ea-0ecb-cf7b-a1ab-9cda97e5cc0a
* Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
* Content: [Windows Hello for Business Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment] 2019-11-13 12:30
@MVDB1984. Will you send an email to  **whfbfeedback@microsoft.com**

**Comment by MVDB1984** [comment] 2019-11-13 13:47
Mail sent... thanks for the advice

**Comment by xcactusx** [comment] 2019-11-14 20:24
@MVDB1984  I'm not claiming to be an expert, by any means...but it sounds like you may have simply run into a timing issue.  We also setup hybrid mode and fortunately, I knew about sync delays so was not surprised.

In hybrid mode with a key trust a lot of syncs need to happen after enrollment for authentication to work.  If a user enrolls and then reboots or logs out before the syncs occur, authentication will fail.  For us, it is approximately 30 min before everything is available.  

Keep in mind the info needs to get from your local DC to the the one that runs ADConnect.  Then ADConnect needs to sync to Azure.  Our ADConnect runs every 30 min and that doesn't take into account syncs between DCs.

I don't believe this info is in any of the deployment guides and we only knew about it from our Microsoft reps.

**Comment by MVDB1984** [comment] 2019-11-14 20:28
I know about the delay.... This is not what is causing the issue...

**Comment by xcactusx** [comment] 2019-11-14 20:37
@MVDB1984 Gotcha.  If it helps, this is doc I used to get the cert part up and running: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki

**Comment by MVDB1984** [comment] 2019-11-14 20:51
Thx for the doc, but this is cert trust deployment, not key trust 😉

**Comment by MVDB1984** [comment] 2019-11-14 20:58
I believe you, but explains a lot.... Thanks for the tip. I'll double check on the doc.
Doc really isn't clear as it should be

**Comment by xcactusx** [comment] 2019-11-14 21:04
Good luck.  I agree, documentation was a bit rough.  Planning docs were great, setup…not so much.  There’s actually two different deployment guides from Microsoft on Hello Key Trust and they don’t match.  If you only used one, you were at a disadvantage.  We walked through setup comparing those along with that POC blog I linked and we managed to stumble through everything.

**Comment by e0i** [comment] 2019-12-24 18:46
@MVDB1984 Thank you for providing feedback. 

The issue is under investigation and you will be notified with any changes on the way.

**Comment by joinimran** [comment] 2020-02-14 14:56
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by JohanFreelancer9** [comment] 2020-02-14 17:17
I can only do copy edit after PR is opened.

**Comment by e0i** [comment] 2020-03-06 02:13
Closing via #6057

**Closed by e0i** 2020-03-06 02:13 UTC
Labels: hello-for-business
