### ISSUE TITLE
Error list is not (or no longer) comprehensive

### ISSUE THREAD

**Issue by anatomicunderground** [MicrosoftDocs/windows-itpro-docs#9181] opened 2021-02-19 19:06 UTC
The list of error messages in this document is no longer comprehensive. We are seeing the following error codes in our environment, which are not documented here. 

Is there another comprehensive list of WU error messages? Or possible an API where error information could be retrieved automatically? We are using event log collection to trigger alerts and automated fixes. Having a comprehensive list of error messages is critical.

SourceName:
Microsoft-Windows-WindowsUpdateClient

EventID:
20

errorCodes:
0xc190020e
0x80073d02
0x80070663
0x80070643
0x80073701
0x8007000d
0x80070070
0x80070057
0x80070005
0x80246010

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
* Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
* Content: [Windows Update error code list by component - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference)
* Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-error-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment] 2021-02-19 19:37
@arcarley can you help out here?

**Comment by jaimeo** [comment] 2021-02-24 16:25
@cinglis-msft can you help us get these error codes up to date?

**Comment by illfated** [comment] 2021-02-24 17:11
Thank you for following up on this question. There seems to be quite a few more tickets regarding those error codes, so I am really looking forward to have those lists updated in accordance with what the developers have been working on during the last year or so.

**Comment by jaimeo** [comment] 2021-02-24 17:16
@illfated do you have dev contacts I could connect with on this?

**Comment by illfated** [comment] 2021-02-24 17:18
Oooh, wish I had. I am merely an external user, but my willing attitude is often mistaken for much more direct involvement in Microsoft than what is real. Sorry about that.

**Comment by jaimeo** [comment] 2021-03-25 16:28
Update: I have contacted the relevant SMEs internally and have just reminded them that we still need help updating these errors.

**Comment by illfated** [comment] 2021-03-25 17:22
Thanks. Nice to see updated information, especially when information is shared with good colleagues in proper places.

**Comment by anatomicunderground** [comment] 2021-12-11 01:20
The documentation doesn't look to have changed at all since this issue was created. Why was it closed?

**Comment by e0i** [comment] 2021-12-11 01:32
@jaimeo Can we take another look into this? The issue is now managed by a different coordinator. Thanks.

cc @e0i

**Comment by jaimeo** [comment] 2021-12-13 16:23
I'm not in this area anymore either. @dougeby FYI. @arcarley @Alice-at-Microsoft can you assist or direct to people who can update the error list?

**Comment by Alice-at-Microsoft** [comment] 2021-12-13 17:42
I'm not familiar with WU client and am not sure who to redirect to.

**Comment by anatomicunderground** [comment] 2022-03-18 19:05
Hi. Any update on this? The list at https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference still does not include some pretty common WU error codes, at least in our environment.

If there is no expectation for the error list to be comprehensive, just indicate that in the document and close this issue.

**Comment by arcarley** [comment] 2022-03-21 07:04
Hi,

Can you please share the error codes that are still missing in your opinion? Note - I am not the right contact for this, but can try to find the correct person to address and update the documentation.

Best,
Aria

**Comment by aczechowski** [comment] 2022-11-17 17:45
This article was migrated to the Windows troubleshooting content library, which is owned by another team in support. I've shared this issue with them if they want to take action on it. I'm closing this issue as there's nothing actionable for my team since this content no longer exists in this repository.

**Closed by aczechowski** 2022-11-17 17:45 UTC
Labels: deployment, product-question, writer-input-required
