### ISSUE TITLE
FirewallRules/FirewallRuleName/LocalAddressRanges and RemoteAddressRanges not showing * correctly

### ISSUE THREAD

**Issue by kagillig** [MicrosoftDocs/windows-itpro-docs#8211] opened 2020-09-03 01:31 UTC
FirewallRules/FirewallRuleName/LocalAddressRanges and FirewallRules/FirewallRuleName/RemoteAddressRanges seem to be missing or not properly showing the * in the documentation for the default value or the any local or remote address value. Instead it shows empty quotes, but I believe it used to correctly show "*". See highlighted areas in the screenshot.
![csp](https://user-images.githubusercontent.com/37852744/92061193-a5f40780-ed63-11ea-8232-8d410bcbb457.JPG)

**Comment by RAJU2529** [comment] 2020-09-03 15:55
@kagillig . Which article are you referring?

**Comment by kagillig** [comment] 2020-09-03 15:57
Oh sorry, talking about the Firewall CSP docs here: https://docs.microsoft.com/en-us/windows/client-management/mdm/firewall-csp

**Comment by RAJU2529** [comment] 2020-09-03 16:01
i  checked the content, the issue is confirmed .
But i think remote IP  address will include in between " " 
for example   "43.157.24.189"

**Comment by kagillig** [comment] 2020-09-03 16:08
Thanks. I'm not quite sure what you mean? I think that everywhere pointed out above is meant to be the * symbol to indicate the default or to indicate any address.

**Comment by e0i** [comment] 2020-10-20 17:37
Closing via #8492

**Closed by e0i** 2020-10-20 17:37 UTC
Labels: Microsoft submitter
