### ISSUE TITLE
The title of this page is misspelled...

### ISSUE THREAD

**Issue by yanezrj** [MicrosoftDocs/windows-itpro-docs#9062] opened 2021-02-01 22:40 UTC
Just FYI
"Configure Windows diagnostic data in your organisation" - should be "organization" 
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c364e-fcf4-8667-17d7-f9a3ec71e1a9
* Version Independent ID: f98f8870-d594-f5df-f6b6-44c9806db7d8
* Content: [Configure Windows diagnostic data in your organisation (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-gb/windows/privacy/configure-windows-diagnostic-data-in-your-organization#feedback)
* Content Source: [windows/privacy/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment] 2021-02-01 23:23
I think you need to check your browser. The page title adapts to your browser language and version of English.

**Comment by illfated** [comment] 2021-02-01 23:25
https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization
## Configure Windows diagnostic data in your organization

https://docs.microsoft.com/en-gb/windows/privacy/configure-windows-diagnostic-data-in-your-organization
## Configure Windows diagnostic data in your organisation

**Comment by illfated** [comment] 2021-02-01 23:26
By the way, the GitHub page title is the /en-us/ version, so I had a little trouble figuring out where to look for the translation issue.

**Comment by nam31** [comment] 2021-02-28 06:01
@yanezrj, it seems that the question has been answered by the community, and thus the issue is being marked as resolved.
Thank you

**Closed by nam31** 2021-02-28 06:01 UTC
Labels: privacy
