### ISSUE TITLE
Need more info on recommended telemetry settings for Windows 7

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/windows-itpro-docs#1893] opened 2018-10-18 17:42 UTC
Under the heading "Recommended diagnostic data level settings" the article includes specific settings recommendations for various Windows 10 builds, presumably based on GDPR-compliance. However, the statement regarding Windows 7 reads simply, "For Windows 7, Microsoft recommends configuring enterprise devices for Windows Analytics to facilitate upgrade planning to Windows 10." There are no recommendations about what [highest] diagnostic level on Windows 7 is recommended vis a vis GDPR compliance. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2ae9eec-43a8-2263-bd96-1ae481e2ebdb
* Version Independent ID: 603f6aa4-740e-5944-8f78-0a88a8bcfe82
* Content: [Windows 10 and the GDPR for IT Decision Makers](https://docs.microsoft.com/en-us/windows/privacy/gdpr-it-guidance)
* Content Source: [windows/privacy/gdpr-it-guidance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/gdpr-it-guidance.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by jvsam** [comment] 2019-06-06 23:33
@officedocsbot assign @jvsam

**Comment by jvsam** [comment] 2019-06-09 23:32
Hi @adamgourd, thank you for your feedback. I will get this issue over to the Windows writing team for review. We want users to have the best Windows experience by ensuring the contents of the Microsoft Docs are accurate, relevant and up-to-date. 

I also requested the team to update this issue if additional information is needed or when the work is complete. Thank you for engaging with the community!

**Comment by TokyoScarab** [comment] 2019-06-13 16:45
@Dansimp I would really be interested to see your thoughts on this.  With Windows 7 very close to end of life, I feel the current documentation is correct in suggesting preparing any Windows 7 installation for an upgrade to Windows 10.

**Comment by jvsam** [comment] 2019-06-18 23:42
Hi @Dansimp we would love to hear what you think. Can you please take a look at @TokyoScarab's question so he would know how to proceed? We appreciate your help!

**Comment by DaniHalfin** [comment] 2019-06-19 01:10
Please note that the content referenced applies to Windows 10. Windows 7 references are mainly to mention the need to upgrade, in order to gain additional controls.
For Windows 7 specific information, please reach out through our official support channels.
We will re-examine if any more information can be added to reference Windows 7 specifically, and will update this topic accordingly.

**Comment by TokyoScarab** [comment] 2019-06-19 01:21
@DaniHalfin Thank you very much for writing back!  That reflects the initial thoughts I had on doing any potential edits.

**Comment by jvsam** [comment] 2019-06-21 23:52
> Please note that the content referenced applies to Windows 10. Windows 7 references are mainly to mention the need to upgrade, in order to gain additional controls. For Windows 7 specific information, please reach out through our official support channels. We will re-examine if any more information can be added to reference Windows 7 specifically, and will update this topic accordingly.

Hi @DaniHalfin we appreciate your time and thanks again for responding and providing helpful information.

@adamgourd, we hope all is well. As confirmed, this doc is still considered *up-to-date*. We will now close this issue and mark it as *resolved/answered*. You can always re-open it if you have additional questions or issues with regard to this documentation. Please be informed though that this site is intended for product documentation, but you can always contact [Windows 10 Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) or [Windows 7 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-7) if you need immediate assistance. Thank you again for your feedback and for engaging with the community! 

CC: Thank you too @TokyoScarab!

**Comment by jvsam** [comment] 2019-06-21 23:53
@officedocsbot close

**Closed by jvsam** 2019-06-21 23:53 UTC
Labels: assigned-to-author, gdpr, privacy
